### ISSUE TITLE
Fallure in installation - "/usr/bin/xcode-select: command not found"

### ISSUE THREAD

**Issue by ejalbania** [Homebrew/install#101]
hostname$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Failed to locate Homebrew!
hostname$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
Password:
==> Installing Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2
==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ El\ Capitan\ version\ 10.11)\ for\ Xcode-8.2
Software Update Tool
Copyright 2002-2015 Apple Inc.

Downloading Command Line Tools (macOS El Capitan version 10.11) for Xcode
Downloaded Command Line Tools (macOS El Capitan version 10.11) for Xcode
Installing Command Line Tools (macOS El Capitan version 10.11) for Xcode
Done with Command Line Tools (macOS El Capitan version 10.11) for Xcode
Done.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
Password:
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
sudo: /usr/bin/xcode-select: command not found
Failed during: /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools

**Comment by MikeMcQuaid** [comment]
You may need to reinstall macOS so you have `/usr/bin/xcode-select` present. Sorry!
