### ISSUE TITLE
Install does not create or link /usr/local/man

### ISSUE THREAD

**Issue by sparr** [Homebrew/install#109]
I recently encountered a problem with `pip install nose` which expects /usr/local/man to exist.

FHS 2.3 says "/usr/local/share/man and /usr/local/man directories must be synonomous (usually this means that one of them must be a symbolic link)".

https://github.com/Homebrew/install/blob/master/install#L206 is where /usr/local/* directories are created, and if we just wanted to create a directory it would be trivial. However I don't see any matching functionality for creating symlinked directories, so I think this will require some new code.

**Comment by JCount** [comment]
This is a fairly common misconception. macOS itself does not follow the FHS, it is a Linux standard. Instead macOS uses its own filesystem hierarchy, and by default, does not even have `/usr/local/man` in the `MANPATH`.

The default in `/etc/manpaths` is:
```
/usr/share/man
/usr/local/share/man
```

You are free to create and/or link a `/usr/local/man`, but for our current purposes, changing Homebrew's default behavior would in general be an unnecessary modification to the user environment, (and would be one more thing that could break.) Furthermore, any formula that attempts to install anything into `HOMEBREW_PREFIX/man` already experiences an audit failure.

-----
Given that this does not appear to be a common issue, and is one that you seem to know how to resolve, I am going to close this issue, but thank you for your involvement and engagement. 

If this issue does end up being more common and pervasive we can potentially revisit things, but it would likely be address by fixing formulae, not by adding code to create a new directory or symlink.

**Comment by sparr** [comment]
The problem in question is not in a formula. Homebrew installs python/pip just fine. The problem is in something else that pip installs later, insofar as "expects /usr/local/man to exist" is a problem.

I'm aware that macOS doesn't follow the FHS, but many Homebrew-installed apps were developed as linux apps that expect a FHS-compliant environment. It seems like a lot of decisions about where Homebrew puts things were based on this expectation.

**Comment by ilovezfs** [comment]
@sparr please take that up with upstream for that package.
