### ISSUE TITLE
Ctrl-C while installing confuses the install script

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/install#11]
_From @Ahti on October 24, 2013 22:28_

I just tried to install brew on a new machine. While it was doing the git checkout (`Downloading and Installing Homebrew...`), I noticed the network was way to slow, so I killed the installation with Ctrl-C.

After I fixed the network and re-tried to install brew, the installer script told me brew seemed to be installed already.

The installer script should catch being aborted and clean up after itself when this happened.

(Am I to blind to find it or is that script not under version control?)

_Copied from original issue: Homebrew/homebrew#23557_

**Comment by jacknagel** [comment]
_From @mistydemeo on October 24, 2013 22:34_

Good catch - that script needs to rescue `Interrupt` and do something sensible.

> (Am I to blind to find it or is that script not under version control?)

The script is in its own orphan branch, `go`: https://github.com/mxcl/homebrew/tree/go

**Comment by jacknagel** [comment]
This is tricky to do right, for example, what should happen when installing Homebrew on top of itself? The check for this isn't foolproof: https://github.com/Homebrew/homebrew/blob/4f7d6849e5fc5a27889af51246b34c88536521c8/install#L105-L109

We wouldn't want it to remove an existing installation. Perhaps it should just print out a warning.

**Comment by jacknagel** [comment]
_From @Ahti on July 7, 2014 14:47_

Well if there is an existing installation, the script will abort pretty fast, so there won't be much chance for the user to ctrl-c. Also at that point, git won't have started to run, so there is nothing to clean up.

I think the right thing to do would be to rescue `Interrupt` only inside the block that chdirs into `HOMEBREW_PREFIX`, and in the rescue handler, remove the `HOMEBREW_PREFIX/.git`.

This would leave everything else intact (if the user reinstalls homebrew and does not want his installed formulas removed), but will leave the prefix in a more sane state, which also allows retrying the installation without removing files manually.

**Comment by mikemcquaid** [comment]
Not convinced we need to fix this.
