### ISSUE TITLE
Brew install fails osx 10.12.5 SSL errors and stuff

### ISSUE THREAD

**Issue by imylomylo** [Homebrew/install#116]
Hi!

Tried this:

> https://raw.githubusercontent.com/Homebrew/install/master/install)"
> ...snipped...
> Press RETURN to continue or any other key to abort
> ==> Downloading and installing Homebrew...
> HEAD is now at 837ea74f4 Merge pull request #3543 from MikeMcQuaid/remove-env-unsets
> ==> Tapping homebrew/core
> Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
> fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': SSLRead() return error -9806
> Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --depth=1
> Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
> Failed during: /usr/local/bin/brew update --force
> Mylos-MacBook-Air:flutter mylo$ ruby -e "$(curl -fsSL 

Then this:
env GIT_SSL_NO_VERIFY=true ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

> Mylos-MacBook-Air:flutter mylo$ env GIT_SSL_NO_VERIFY=true ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
> ==> This script will install:
> /usr/local/bin/brew
> /usr/local/share/doc/homebrew
> /usr/local/share/man/man1/brew.1
> /usr/local/share/zsh/site-functions/_brew
> /usr/local/etc/bash_completion.d/brew
> /usr/local/Homebrew
> 
> Press RETURN to continue or any other key to abort
> ==> Downloading and installing Homebrew...
> HEAD is now at 837ea74f4 Merge pull request #3543 from MikeMcQuaid/remove-env-unsets
> fatal: unable to access 'https://github.com/Homebrew/brew/': SSLRead() return error -9806
> Error: Fetching /usr/local/Homebrew failed!
> ==> Tapping homebrew/core
> Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
> fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': SSLRead() return error -9806
> Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --depth=1
> Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
> Failed during: /usr/local/bin/brew update --force
> Mylos-MacBook-Air:flutter mylo$ pwd
> /Users/mylo/Dev/flutter
> 

Trying to muck around with flutter.  Cheers

**Comment by MikeMcQuaid** [comment]
You'll need to figure out yourself why `git` cannot access GitHub.
