### ISSUE TITLE
Brew installs CLI tools after complete Xcode install

### ISSUE THREAD

**Issue by JMSarDev** [Homebrew/install#120]
Clean installation of macOS High Sierra 10.13.3 + Xcode 9.2. 

I remember brew didn't need to install CLI tools if full Xcode was installed, and didn't find any news regarding this.

Even after installing Xcode and running it for first time, brew installs CLI tools. Checking the code I found this:

```
def should_install_command_line_tools?
   return false if force_curl?
   return false if macos_version < "10.9"
   !File.exist?("/Library/Developer/CommandLineTools/usr/bin/git") ||
      !File.exist?("/usr/include/iconv.h")
end
```

"/Library/Developer/CommandLineTools/" this directory does not exist. 

I see the latest commit makes this change but I do not see why is this necessary when having already CLI tools bundled with full Xcode

**Comment by MikeMcQuaid** [comment]
> I remember brew didn't need to install CLI tools if full Xcode was installed, and didn't find any news regarding this.

I doesn't need it on 10.13 (but will when 10.14 is released) but installing it does not cause any issues and makes Homebrew more reliable so we do it by default.

**Comment by ma11hew28** [comment]
I don't like this. How do you know it'll need it? [You ain't gonna need it (YAGNI)][1]. Homebrew could prompt the user to install it when it's needed. Does not cause any issues? It creates a bad user experience, takes up hard disk space, and uses command line tools that I don't think will get updated (when I update Xcode). More reliable? [Don't repeat yourself (DRY)][2]. You don't make software more reliable by adding cruft. You do it by writing good code (and good tests).

  [1]: https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it
  [2]: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Comment by ma11hew28** [comment]
I think the command below is how you uninstall the command-line tools.

    sudo rm -rf /Library/Developer/CommandLineTools

Source: [How can I uninstall the command-line tools?][1]


  [1]: https://developer.apple.com/library/content/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_

**Comment by MikeMcQuaid** [comment]
@ma11hew28 Please don't comment again on closed issues unless it describes a bug we've claimed to fix but isn't fixed. Please refrain from lecturing the Homebrew maintainers on basic software engineering principles we learned about 10 years ago.
