### ISSUE TITLE
Can't download brew installer from server

### ISSUE THREAD

**Issue by fobos** [Homebrew/install#126]
Hi folks,

I tried to install brew from instruction on home page but received next error:
`curl: (22) The requested URL returned error: 503 Backend is unhealthy`

It looks like your Varnish server is broken down.

**Comment by ilovezfs** [comment]
This is some kind of local configuration, network or ISP issue for you specifically that you'll need to troubleshoot.

https://raw.githubusercontent.com/Homebrew/install/master/install is reachable.

**Comment by fobos** [comment]
@ilovezfs Thanks! It was really our trouble. Now everything works well!

**Comment by ilovezfs** [comment]
@fobos you're welcome! I'm glad to hear you got it resolved.
