### ISSUE TITLE
Does the installer check for permissions in /usr/local?

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/install#141]
Seeing a couple of issues in discourse are caused one way or another by an already existing install being owned by root. Would it be feasible if the installer checked if it would be able to create/chown directories there before trying to? 

https://discourse.brew.sh/t/i-cant-seem-to-install-home-brew-on-version-10-13-6/2820
https://discourse.brew.sh/t/i-have-problem-with-installation-please-help/2895

**Comment by MikeMcQuaid** [comment]
> Would it be feasible if the installer checked if it would be able to create/chown directories there before trying to?

It should do this. It's possible there's been a regression.

**Comment by MikeMcQuaid** [comment]
@SMillerDev Are we still seeing a bunch of issues about this? I'd expect a continuing deluge if there's been a regression.

**Comment by SMillerDev** [comment]
There's not that many people reinstalling homebrew on an existing system and making issues about it on discourse unfortunately.

**Comment by MikeMcQuaid** [comment]
Closing this out for now but will reopen if we get a bunch more issues on this.
