### ISSUE TITLE
Wrong command line tools version installed in macOS Mojave

### ISSUE THREAD

**Issue by ghost** [Homebrew/install#146]
In macOS Mojave 10.14 (18A391) the Software Update Tool does not output items in ascending order. This causes the Homebrew (un)installer to install an outdated version of Command Line Tools.

https://github.com/Homebrew/install/blob/master/install#L312-L322

```
$ sw_vers
# => ProductName:    Mac OS X
# => ProductVersion: 10.14
# => BuildVersion:   18A391

$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# => ...
# => The Xcode Command Line Tools will be installed.
# => ...
# => Installing Command Line Tools (macOS High Sierra version 10.13) for Xcode
# => ...

$ brew install duti
# => Error: Your Command Line Tools are too outdated.
# => Update them from Software Update in the App Store.

$ sudo rm -rf /Library/Developer/CommandLineTools

$ /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
$ /usr/sbin/softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | tail -n1
# => Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4

$ softwareupdate -l | grep '* Command Line Tools'
# =>   * Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2
# =>   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.0
# =>   * Command Line Tools (macOS Mojave version 10.14) for Xcode-10.0
# =>   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.3
# =>   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4
```

**Comment by niclasgelin** [comment]
Perhaps a more reliable solution is to leverage `@macos_version`, as demonstrated in rtrouton's script.

https://github.com/Homebrew/install/blob/master/install#L114-L116

https://github.com/rtrouton/rtrouton_scripts/blob/master/rtrouton_scripts/install_xcode_command_line_tools/install_xcode_command_line_tools.sh

**Comment by niclasgelin** [comment]
Using `sort --version-sort` seems to do the trick. This will select the latest available version of Command Line Tools, given an unknown order of items in the SU feed, and given the SU feed contains only the latest version of Command Line Tools compatible with current macOS product version.

```sh
$ touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
$ softwareupdate -l \
	| grep '* Command Line Tools' \
	| sort -V \
	| tail -n 1 \
	| sed 's/.*\* //'
```

**Comment by niclasgelin** [comment]
Using sort `--version-sort` seems to do the trick.

This will select the latest available version of Command Line Tools, given an unknown order of items in the SU feed, and given the latest available version in the SU feed is compatible with current macOS product version.

```sh
$ touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
$ softwareupdate -l \
	| grep '* Command Line Tools' \
	| sort -V \
	| tail -n 1 \
	| sed 's/.*\* //'
```

**Comment by niclasgelin** [comment]
Using `sort --version-sort` seems to do the trick.

This will select the latest available version of Command Line Tools, given an unknown order of items in the SU feed, and given the latest available version in the SU feed is compatible with current macOS product version.

```
$ softwareupdate -l \
	| grep '* Command Line Tools' \
	| sort -V \
	| tail -n 1 \
	| sed 's/.*\* //'
```

**Comment by niclasgelin** [comment]
Using `sort --version-sort` seems to do the trick.

This change would enable the Homebrew (un)installer to select and install the latest available version of Command Line Tools, given an unknown order of items in the SU feed, and given the latest available version in the SU feed is compatible with current macOS product version.

```sh
$ softwareupdate -l \
	| grep '* Command Line Tools' \
	| sort -V \
	| tail -n 1 \
	| sed 's/.*\* //'
```
