### ISSUE TITLE
hacky way that commandlinetools is installed makes it very difficult to remove it properly

### ISSUE THREAD

**Issue by xzcvczx** [Homebrew/install#155]
as commandlinetools is hackily installed by default using softwareupdate a receipt is placed in 

```/System/Library/Receipts/com.apple.pkg.CLTools_*```

The only way to remove this requires rebooting into recovery mode and disabling SIP otherwise even if you remove /Library/Developer/CommandLineTools you will continue to get asked to update.

it seems the softwareupdate method is used to avoid the gui dialog, however would it not be better to install the commandlinetools properly using xcode-select by default (which doesn't install the receipt file) with an option (either commandline or env var) for a headless install

**Comment by MikeMcQuaid** [comment]
We’re not interested in making this optional or having another code path for headless installs. We’ll review a PR if you can figure out a headless way to do this that works everywhere the current way does.
