### ISSUE TITLE
uninstaller doesn't check if the directories were deleted or not.

### ISSUE THREAD

**Issue by maxamilion** [Homebrew/install#16]
When I uninstall homebrew, the uninstaller prompts it will delete /Library/Caches/Homebrew/ but it fails because the permission of /Library/Caches/Homebrew/Formula was of another user that had already installed homebrew. Unless manually deleting /Library/Caches/Homebrew/ directory, installing rvm will fail while installing libraries. It will be better if homebrew uninstaller checks if all the directories supposed to be deleted actually were deleted or not. 
Mac OS X 10.10.3
uninstaller: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

**Comment by mikemcquaid** [comment]
@DomT4 Maybe the uninstaller should ask for `sudo` just to be able to definitely delete all these directories?

**Comment by DomT4** [comment]
Sorry, I didn't see the ping here. @xu-cheng wrote this version of the uninstall script, but given the `install` script requires `sudo` I think it's reasonable that we require the same level of permissions to destroy the `brew` installation as well.
