### ISSUE TITLE
Should use git's `--depth 1` flag to reduce installation time and download size

### ISSUE THREAD

**Issue by knocte** [Homebrew/install#195]
When installing brew via `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`, if using a slow connection, it could take a big while. Using `--depth 1` would be recommended when using git to download (because an installation shouldn't need to fetch history).

**Comment by MikeMcQuaid** [comment]
That speeds up the first installation but is inefficient for every `brew update` after that point and produces issues with e.g. calculating the version based on tags.
