### ISSUE TITLE
Cant install homebrew on mac os 10.14

### ISSUE THREAD

**Issue by curtisconner** [Homebrew/install#205]
Trying to install homebrew on my new install of macOS 10.14 and get the following error, any ideas

Press RETURN to continue or any other key to abort
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
Password:
==> Installing Command Line Tools (macOS Mojave version 10.14) for Xcode-10.2
==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ Mojave\ version\ 10.14)\ for\ Xcode-10.2
Software Update Tool

Downloading Command Line Tools (macOS Mojave version 10.14) for Xcode
Downloaded Command Line Tools (macOS Mojave version 10.14) for Xcode
Installing Command Line Tools (macOS Mojave version 10.14) for Xcode
Error downloading Command Line Tools (macOS Mojave version 10.14) for Xcode: “Command Line Tools (macOS Mojave version 10.14) for Xcode” could not be verified.
Done.

Error downloading updates.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
xcode-select: error: invalid developer directory '/Library/Developer/CommandLineTools'
Failed during: /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools

**Comment by MikeMcQuaid** [comment]
> Error downloading Command Line Tools (macOS Mojave version 10.14) for Xcode: “Command Line Tools (macOS Mojave version 10.14) for Xcode” could not be verified.

Try to manually run `xcode-select --install`.
