### ISSUE TITLE
When installing - Error: Permission denied - /Library/Caches/Homebrew/Formula

### ISSUE THREAD

**Issue by DomT4** [Homebrew/install#21]
_From @fbucek on August 7, 2015 12:35_

When I follow web page brew.sh to install HomeBrew
1) Install HomeBrew: 
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
OK - working

2) Install wget
brew install wget
Error: Permission denied - /Library/Caches/Homebrew/Formula

I have to "fix" this using command found here ( found here in issues somewhere )
sudo chown -R $USER:admin $(brew --cache)

Another mention of this problem:
http://stackoverflow.com/questions/17610417/permission-denied-library-caches-homebrew-formula-nmap-brewing
Answer helped some people.

OS: OSX 10.10.5

_Copied from original issue: Homebrew/homebrew#42606_

**Comment by DomT4** [comment]
_From @dunn on August 7, 2015 15:44_

Thanks for the report.  This is probably something we can check during installation.

**Comment by dunn** [comment]
I wasn't sure whether to move it because this is something that _could_ be addressed in `formulary.rb` (https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formulary.rb#L130).  But my guess it that we should figure out a way to preempt the issue here, since it might need `sudo`.

**Comment by DomT4** [comment]
Yeah, my reading was that since the user didn't do anything to the cache before `brew install wget` the error, if it is an error, was the installer's. I could be wrong on that reading though.

We already create the [cache](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/config.rb#L1-L24) to be world-writeable unless it already exists, although only the top level directory.

I'm not quite sure how it could end up in this situation, unless `HOMEBREW_CACHE+"Formula"` already exists for some reason and isn't getting generated after the cache is created with world permissions.

Generally I'm not a fan of cross-user world-writeable cache's being supported for this and other reasons, and would prefer for our default to be a per-user cache, but I haven't won that argument to date.

**Comment by mikemcquaid** [comment]
This could be fixed in https://github.com/Homebrew/install/pull/23 I guess?
