### ISSUE TITLE
Add the ability to provide sudo password through env

### ISSUE THREAD

**Issue by Cyberbeni** [Homebrew/install#229]
I have a bash script that installs all the useful stuff after a clean install where I read in the sudo password at the start and use it like this later on:

```
asSudo() {
 echo $PASSWORD | sudo -Sk "$@"
}
```

It would be cool to be able to provide this password to the Homebrew installer, so I don't need to pay attention to type in my password manually multiple times.

**Comment by reitermarkus** [comment]
`SUDO_ASKPASS` is already supported.
