### ISSUE TITLE
Clarify license wording/formatting

### ISSUE THREAD

**Issue by mikesep** [Homebrew/install#246]
This repo has a `LICENSE.txt` file that GitHub cannot identify as a known license type, though it appears to be nearly identical to the BSD 2-Clause License, which is used on many other Homebrew repos (Homebrew/brew, Homebrew/homebrew-core, Homebrew/homebrew-cask). Having GitHub clearly identify the license type would ease the path toward contributing to this repo, in my opinion.

The important difference seems to be the use of "author" instead of "copyright holder and contributor". If this license was intended to be BSD 2-Clause, would it make sense to simply copy the `LICENSE.txt` file from Homebrew/brew to this repo? If the maintainers agree, I'm happy to make such a pull request.

**Comment by MikeMcQuaid** [comment]
> If this license was intended to be BSD 2-Clause, would it make sense to simply copy the `LICENSE.txt` file from Homebrew/brew to this repo? If the maintainers agree, I'm happy to make such a pull request.

Yes, that'd be great, thanks!
