### ISSUE TITLE
Installer is wrong about permissions

### ISSUE THREAD

**Issue by jmussman** [Homebrew/install#257]
The installer merely checks directory ownership, it doesn't really check permissions. And, it is a security failure to suggest that the ownership /usr/local/? should be changed. The real answer is that the installing user should be a member of the group that owns /usr/local/?: wheel or admin.

$ brew install mongodb-community
Error: The following directories are not writable by your user:
/usr/local/include
/usr/local/lib
/usr/local/lib/pkgconfig

You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/include /usr/local/lib /usr/local/lib/pkgconfig

And make sure that your user has write permission.
  chmod u+w /usr/local/include /usr/local/lib /usr/local/lib/pkgconfig
$ ls -ld /usr/local/include
drwxrwxr-x  143 root  wheel  4576 Jan 25 08:51 /usr/local/include
$ id | grep wheel
uid=501(jmussman) gid=20(staff) groups=20(staff),401(com.apple.sharepoint.group.1),501(access_bpf),0(wheel),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),704(com.apple.sharepoint.group.5),701(com.apple.sharepoint.group.3),705(com.apple.sharepoint.group.6),702(com.apple.sharepoint.group.2),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),703(com.apple.sharepoint.group.4)
$ cd /usr/local/include
$ touch test
$ rm test

Clearly I have access to write in /usr/local/include (and the other directories) but the installer is not making the effort to check it properly and fails inappropriately.

**Comment by MikeMcQuaid** [comment]
> The real answer is that the installing user should be a member of the group that owns /usr/local/?: wheel or admin.

No. Our installer (and Homebrew itself) is built around the (almost always correct) assumption that you're running it on a single-user system and if you wish to do otherwise you can (and indeed should) modify the permissions as desired yourself.

**Comment by jmussman** [comment]
Hi!

Please take a closer look at my issue before you just arbitrarily close it. You answer states that I can change permissions as I chose. My permissions are set correctly, that’s what the capture I posted shows. I was pointing out that the installer does not work under those circumstances. So all I was asking was that you might want to consider allowing for that. I acknowledge that I did suggest that it was wrong to tell people to arbitrarily change the ownership, but that was incidental to the issue.

Instead you went off flaming :( Geez, I’ve been a Unix systems programmer for over forty years. It should take what, a couple of more statements to make the correct check?

Thanks!
Joel Mussman


If you want to tell people to do an unsafe change to fix the problem you have that right.  under all circumstances, not just the assumptions that you make.

On Jan 25, 2020, at 11:37 AM, Mike McQuaid <notifications@github.com<mailto:notifications@github.com>> wrote:


The real answer is that the installing user should be a member of the group that owns /usr/local/?: wheel or admin.

No. Our installer (and Homebrew itself) is built around the (almost always correct) assumption that you're running it on a single-user system and if you wish to do otherwise you can (and indeed should) modify the permissions as desired yourself.

**Comment by MikeMcQuaid** [comment]
Please reread our [Code of Conduct](https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md) and adjust your tone accordingly on future issues as I found and find it quite rude.

On a purely pragmatic basis (as I expect you may disagree): if your tone does not produce the results you desire from the volunteers who run this (or any other) project in their spare time then you may find it more productive to change it.

> It should take what, a couple of more statements to make the correct check?

If it is very simple to make the checks you consider correct: please submit a pull request rather than an issue.

**Comment by jmussman** [comment]
I have. Maybe you should review your own writing, you were a lot ruder to me in your original response.

On Jan 26, 2020, at 7:38 PM, Mike McQuaid <notifications@github.com<mailto:notifications@github.com>> wrote:


Please reread our Code of Conduct<https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md> and adjust your tone accordingly on future issues as I found and find it quite rude.

On a purely pragmatic basis (as I expect you may disagree): if your tone does not produce the results you desire from the volunteers who run this (or any other) project in their spare time then you may find it more productive to change it.

It should take what, a couple of more statements to make the correct check?

If it is very simple to make the checks you consider correct: please submit a pull request rather than an issue.

**Comment by jmussman** [comment]
Mike,

I apologize. I let your responses get the better of me, and I’m wrong for that and I should be better than that.

You and I should be better at working together to solve a problem. Given our backgrounds we’d probably be friends. If you would like me to correct it and do a pull request I’ll be happy to. I’m having difficulty in the code finding where the check is done. I will be able to work my way through it, but it would be a lot easier if someone just pointed me to the right code.

Thanks,
Joel

On Jan 26, 2020, at 7:38 PM, Mike McQuaid <notifications@github.com<mailto:notifications@github.com>> wrote:


Please reread our Code of Conduct<https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md> and adjust your tone accordingly on future issues as I found and find it quite rude.

On a purely pragmatic basis (as I expect you may disagree): if your tone does not produce the results you desire from the volunteers who run this (or any other) project in their spare time then you may find it more productive to change it.

It should take what, a couple of more statements to make the correct check?

If it is very simple to make the checks you consider correct: please submit a pull request rather than an issue.

**Comment by MikeMcQuaid** [comment]
> I apologize.

Thanks, I appreciate the apology.

> I will be able to work my way through it, but it would be a lot easier if someone just pointed me to the right code.

https://github.com/Homebrew/brew/blob/e47a6ac4cb8810ab687096f224e1fc4c0f0f980e/Library/Homebrew/diagnostic.rb#L344-L360
