### ISSUE TITLE
Install should add homebrew paths to /etc/paths.d

### ISSUE THREAD

**Issue by jediorange** [Homebrew/install#26]
The recommended procedure for adding to the PATH in OS X is to add a file to /etc/paths.d

The installer should create a file: `/etc/paths.d/sh.brew.homebrew` with the following contents:
```
/usr/local/bin
/usr/local/sbin
```

**Comment by jediorange** [comment]
Also, if the installer is going to create such a file, the uninstaller should remove it.

**Comment by mikemcquaid** [comment]
> The recommended procedure for adding to the PATH in OS X is to add a file to /etc/paths.d

Do you have a source for that recommendation?

**Comment by mistydemeo** [comment]
We intentionally suggest against setting the PATH in `/etc/paths.d` in order to avoid inadvertantly publishing these paths for things which run as other users; our suggestion is to set the PATH in the user's shell and [using `launchctl setenv`](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#my-mac-apps-dont-find-usrlocalbin-utilities) for software running as that user outside of a shell.

**Comment by jediorange** [comment]
@mikemcquaid It is considered best practice for individual applications to use `paths.d` and `manpaths.d` as [path_helper](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/path_helper.8.html) uses these folders to build the path variables.

The reason for this is that the files can be easily removed during an uninstall process without having to edit profiles or rc files.

@mistydemeo I would argue that your reasoning is exactly why it should be used. `/etc/paths.d` only effects interactive shells, so it doesn't inadvertently effect other things running, unless a user is looking for that tool in their shell. Since homebrew is installing tools and applications which are available system-wide (not user specific), the applications should be automatically available to all users.  It's a poor user experience to install something via `brew install` and not be able to run it.

It is already difficult enough for a user to have to go to a website and manually copy and paste an install command to their shell, so why add more manual steps?  If anything, make it a prompt:
```
Would you like to add the homebrew path to the system-wide PATH variables? (Y/n)
```

**Comment by mikemcquaid** [comment]
> @mikemcquaid It is considered best practice for individual applications to use paths.d and manpaths.d as path_helper uses these folders to build the path variables.

Considered by whom?

I do agree with @mistydemeo here; it's a Homebrew design principle to not modify system files but instead point users to modify things in their `$HOME` instead.

**Comment by jediorange** [comment]
@mikemcquaid by Apple. See Server.app for an example (one of the few apps which includes command line tools)

Also, I guess I understand the hesitation, but the installer is already making system wide changes. Giving an option like this only makes it easier for the users (and isn't that the whole point of homebrew?) by removing an extra necessary step.

**Comment by mikemcquaid** [comment]
@jediorange It only makes system wide changes that are absolutely necessary to run Homebrew. I think it's fine as-is but will let other maintainers chime in.

**Comment by mikemcquaid** [comment]
Passing on this.
