### ISSUE TITLE
CLT installed regardless of Xcode

### ISSUE THREAD

**Issue by texastoland** [Homebrew/install#263]
I ran into this last time I installed too but never reported it. Last time I manually edited the script. This time I created a symlink to `xcode-select -p`.
https://github.com/Homebrew/install/blob/7091d58c5870cbb7efa903e5d35ecb51a352074c/install#L118

**Comment by MikeMcQuaid** [comment]
This is not a bug. The CLT is not the same as what is provided by Xcode and different packages require different things so we always install the CLT. If you don't want the CLT: use one of the documented alternate installation methods.
