### ISSUE TITLE
Port uninstaller to Bash

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/install#266]
A less urgent follow-up to https://github.com/Homebrew/install/issues/217. 

Similarly, the best strategy to begin with would be a line-by-line port and add Linux support in a later PR.

CC @itchyny if you'd like to pick this up.

**Comment by gromgit** [comment]
I'd be happy to take this up. I was about to submit a PR for preliminary Linux support anyway; was gobsmacked when I ran it on a test box, and it tried to nuke `.DS_Store`s. 8-)

**Comment by gromgit** [comment]
Just submitted PR #276 to verify the additional Ruby logic that supports Linux uninstall. Once that's confirmed, I'll submit the "translated" Bash script.

**Comment by MikeMcQuaid** [comment]
Done, nice work @gromgit!
