### ISSUE TITLE
Installer leaves behind root-owned .cache folder 

### ISSUE THREAD

**Issue by jswny** [Homebrew/install#279]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

Output from inside the Docker container noted below:

**`brew doctor`**:
```sh
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale
: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /bin/apt-config
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

**`brew config`**:
```sh
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
HOMEBREW_VERSION: 2.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 48a1637b24a0c329905a981f4cff547c7fa47943
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 6d15f07b97daad79f8140629c91d6286317ac3dc
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/user1/.cache/Homebrew
HOMEBREW_LOGS: /home/user1/.cache/Homebrew/Logs
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.20.1 => /bin/git
Curl: 7.65.3 => /usr/bin/curl
Kernel: Linux 4.19.76-linuxkit x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.30
/usr/bin/gcc: 9.2.1
glibc: N/A
gcc: N/A
xorg: N/A
```

## What you were trying to do (and why)
Install Homebrew on Ubuntu, and then use the `~/.config` folder as a non-root user.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

```
mkdir: cannot create directory ‘/home/user1/.cache/fisher’: Permission denied
```

  </pre>
</details>

## What you expected to happen

`~/.cache` to be owned by the user (not root) after running the install script.

## Step-by-step reproduction instructions (by running `brew` commands)
1. Delete `~/.cache`
2. Run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
3. Check the permissions of `~/.cache`

Minimal Dockerfile to reproduce:
```dockerfile
FROM ubuntu:19.10

# Install brew deps and sudo
RUN apt-get update \
    && apt-get install -y \
    sudo \
    libc6 \
    gcc \
    make \
    curl \
    file \
    git

# Add a new user and add them to sudoers
# Setup sudo to be used without a password
RUN useradd --create-home user1 \
    && usermod -aG sudo user1 \
    && echo "user1 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER user1
WORKDIR /home/user1

# Commenting this out will cause a /home/user1/.cache directory to be created which is owned by root:root
# When it is not commented out, the directory is left owned by the correct user
# RUN mkdir /home/user1/.cache

RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

RUN ls -l -a /home/user1
```
Output without creating `~/.cache` first:
```sh
Step 7/7 : RUN ls -l -a /home/user1
 ---> Running in 076bd2ed92cf
total 24
drwxr-xr-x 1 user1 user1 4096 Mar 11 06:11 .
drwxr-xr-x 1 root  root  4096 Mar 11 06:11 ..
-rw-r--r-- 1 user1 user1  220 May  5  2019 .bash_logout
-rw-r--r-- 1 user1 user1 3771 May  5  2019 .bashrc
drwxr-xr-x 3 root  root  4096 Mar 11 06:11 .cache
-rw-r--r-- 1 user1 user1  807 May  5  2019 .profile
-rw-r--r-- 1 user1 user1    0 Mar 11 06:11 .sudo_as_admin_successful
```

Output with creating `~/.cache` first:
```sh
Step 8/8 : RUN ls -l -a /home/user1
 ---> Running in 346bcf4c3fcf
total 24
drwxr-xr-x 1 user1 user1 4096 Mar 11 06:14 .
drwxr-xr-x 1 root  root  4096 Mar 11 06:14 ..
-rw-r--r-- 1 user1 user1  220 May  5  2019 .bash_logout
-rw-r--r-- 1 user1 user1 3771 May  5  2019 .bashrc
drwxr-xr-x 1 user1 user1 4096 Mar 11 06:14 .cache
-rw-r--r-- 1 user1 user1  807 May  5  2019 .profile
-rw-r--r-- 1 user1 user1    0 Mar 11 06:14 .sudo_as_admin_successful
```

I think the problem is that [the line that creates `$HOMEBREW_CACHE`](https://github.com/Homebrew/install/blob/master/install.sh#L415) creates with `mkdir -p`, which creates `~/.cache` if it doesn't exist. However, [the line that runs`chown` on `$HOMEBREW_CACHE`](https://github.com/Homebrew/install/blob/master/install.sh#L421) only owns the last directory in the tree, leaving behind `~/.cache` owned by root if it didn't exist before the `mkdir` line.

**Comment by dawidd6** [comment]
Can you create a PR to fix that?

**Comment by jswny** [comment]
@dawidd6 I would be happy to try, but I'm not sure I know how you'd like to handle this. The problematic code is here:
```sh
if ! [[ -d "${HOMEBREW_CACHE}" ]]; then
  execute_sudo "/bin/mkdir" "-p" "${HOMEBREW_CACHE}"
fi
if exists_but_not_writable "${HOMEBREW_CACHE}"; then
  execute_sudo "/bin/chmod" "g+rwx" "${HOMEBREW_CACHE}"
fi
if file_not_owned "${HOMEBREW_CACHE}"; then
  execute_sudo "$CHOWN" "$USER" "${HOMEBREW_CACHE}"
fi
if file_not_grpowned "${HOMEBREW_CACHE}"; then
  execute_sudo "$CHGRP" "$GROUP" "${HOMEBREW_CACHE}"
fi
```

My idea for a fix would be to check if the script is running on linux and if `$HOME/.cache` doesn't exist, and if so:
1. Create `$HOME/.cache`
2. `chown` it to the current user
3. `chgrp` it to the current user

Because as it stands, any modifications to the current code would affect Mac installs too, which I think should probably be left alone as this bug only affects Linux installs. 

The only problem with hardcoding `$HOME/.cache` for the fix would mean that if the default dirctory for`$HOMEBREW_CACHE` is changed to somewhere else in `$HOME`, we'd need to remember to update this fix too. A more robust approach would be to use `dirname` to get the parent directory, and then use the same steps as above, but that wouldn't work if for some reason the `$HOMEBREW_CACHE` is changed down the road to be multiple directories deep which may not exist, the fix would only create the direct parent with correct permissions.

I'm not sure if it's okay to just hardcode it, but let me know what you think and I'll see if I can make a PR.

**Comment by dawidd6** [comment]
To be honest I would just go for something like that:

```sh
if ! [[ -d "${HOMEBREW_CACHE}" ]]; then
  if [[ -z "${HOMEBREW_ON_LINUX-}" ]]; then
    execute_sudo "/bin/mkdir" "-p" "${HOMEBREW_CACHE}"
  else
    /bin/mkdir "-p" "${HOMEBREW_CACHE}"
  fi
fi
```

IMO there is no need to execute sudo here.

**Comment by jswny** [comment]
@dawidd6 That would definitely work. Now that I think about it, since it is in the user's home directory, I'm also not sure why you'd need to use sudo at all.

**Comment by itchyny** [comment]
By the way the issue title looks like confusing, the installer does not create **.config** directory.

**Comment by jswny** [comment]
@itchyny Thanks! Updated.

**Comment by MikeMcQuaid** [comment]
> IMO there is no need to execute sudo here. Curious what @MikeMcQuaid would say about that.

Makes sense to me!

**Comment by jswny** [comment]
@dawidd6 @MikeMcQuaid Cool! I will submit a PR for this, hopefully tomorrow.
