### ISSUE TITLE
ruby version of `uninstall --force` now freezes

### ISSUE THREAD

**Issue by jeroen** [Homebrew/install#299]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

The travis log linked below runs on 10.13.6 (as can be seen in the log file)

## What you were trying to do (and why)

Our CI is using the recommended procedure to automatically uninstall a preinstalled homebrew:

```
curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall
sudo ruby uninstall --force
```

For example: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb#L568-L576

## What happened (include command output)

As of yesterday running this script in CI freezes at the user prompt:

```
Warning: This script will remove:
/Users/travis/Library/Caches/Homebrew/
/Users/travis/Library/Logs/Homebrew/
/usr/local/Caskroom/
/usr/local/Cellar/
/usr/local/bin/brew -> /usr/local/bin/brew
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] 
```

Example: https://travis-ci.org/github/ropensci/xslt/jobs/675283572

From the commits I infer that the uninstall script was ported to bash (which is great) but perhaps it would be possible to keep the ruby version working as well for existing deployments?

## What you expected to happen

Uninstall homebrew without prompting user confirmation.

**Comment by MikeMcQuaid** [comment]
Please migrate to the Bash version instead, thanks.

**Comment by jeroen** [comment]
We're working on the migration, but is there anyway you can keep the ruby version working for now? 

It is still used in the faq: https://github.com/Homebrew/brew/blob/master/docs/FAQ.md#how-do-i-uninstall-homebrew

**Comment by MikeMcQuaid** [comment]
The Ruby version works but doesn't pass through arguments. I'll review a PR to pass through the arguments. I've got a PR open to update the FAQ, thanks for the catch.

**Comment by jeroen** [comment]
OK thanks, I filed a PR here: https://github.com/Homebrew/install/pull/301
