### ISSUE TITLE
SIP tweak is too strict

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/install#30]
@mikemcquaid 
There is a minor bug with https://github.com/Homebrew/install/commit/09a5b19f8650b163c241fb3503ed7c8106fed58.

If <code>/usr/local</code> doesn't exist and SIP is disabled, it is still possible to mkdir /usr/local, even if /usr/local is not in /System/Library/Sandbox/Compatibility.bundle/Contents/Resources/paths.

Therefore, the current test 
```
!(File.exist?(sandbox_paths_file) && IO.read(sandbox_paths_file).include?("/usr/local\n"))
```
is too hasty to abort.

One fix would be to explicitly check if the SIP file system restriction is enabled or disabled. This can be done as shown here: https://github.com/Piker-Alpha/csrstat/blob/master/csrstat.c

The relevant configuration flag to check for is CSR_ALLOW_UNRESTRICTED_FS. (SIP can be selectively enabled. For example, to enable all restrictions except for the file system restriction and the dtrace restriction <code>csrutil enable --without fs,dtrace</code> or <code>csrutil enable --without fs --without dtrace</code>). 

The less "sophisticated" approach would be to actually try mkdir /usr/local before aborting.

**Comment by mikemcquaid** [comment]
I'd probably rather not fix this as I don't want SIP being disabled to be a supported configuration that we encourage.

**Comment by ilovezfs** [comment]
@mikemcquaid There's also a more serious bug with the conditional within the heredoc.

It seems that, at least with the ruby that ships with El Capitan, the test needs to be on one line to work.
```
diff --git a/install b/install
index 7d75e99..d4fdfda 100755
--- a/install
+++ b/install
@@ -148,8 +148,7 @@ Xcode.app or running:
     sudo xcodebuild -license
 EOABORT
 sandbox_paths_file = "/System/Library/Sandbox/Compatibility.bundle/Contents/Resources/paths"
-abort <<-EOABORT if !File.directory?(HOMEBREW_PREFIX) && macos_version >= "10.11" \
-  && !(File.exist?(sandbox_paths_file) && IO.read(sandbox_paths_file).include?("/usr/local\n"))
+abort <<-EOABORT if !File.directory?(HOMEBREW_PREFIX) && macos_version >= "10.11" && !(File.exist?(sandbox_paths_file) && IO.read(sandbox_paths_file).include?("/usr/local\n"))
 Your OS X 10.11 install requires an additional step to write into #{HOMEBREW_PREFIX}.
 Please follow the steps described here and then run the install script again:
   https://git.io/vnC7w
```

**Comment by ilovezfs** [comment]
@mikemcquaid I opened a pull request for the second bug I mentioned: https://github.com/Homebrew/install/pull/31

**Comment by mikemcquaid** [comment]
Given my comment and your fix for the second bug I think we can close this out. Please shout if you disagree!
