### ISSUE TITLE
https://raw.githubusercontent.com/Homebrew/install/master/install.sh can not be visited.

### ISSUE THREAD

**Issue by jackpgao** [Homebrew/install#303]
- https://raw.githubusercontent.com/Homebrew/install/master/install.sh can not be visited.

**Comment by MikeMcQuaid** [comment]
Works for me.

**Comment by jackpgao** [comment]
It's the problem of IPv6.
https://stackoverflow.com/questions/48987512/ssl-connect-ssl-error-syscall-in-connection-to-github-com443
