### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by swordsly** [Homebrew/install#311]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)
Install homebrew via terminal.
OS: 10.14.5 Mojave

## What happened (include command output)
Unable to install.

<details>
  <summary>Command output</summary>
  <pre>

-e:5: syntax error, unexpected '=', expecting ']'
if [[ "$(uname)" = "Linux" ]]; then
                  ^
-e:5: syntax error, unexpected ']', expecting end-of-input
if [[ "$(uname)" = "Linux" ]]; then
                            ^

  </pre>
</details>

## What you expected to happen

Installation should proceed without issue.

## Step-by-step reproduction instructions (by running `brew` commands)

Ran the following in terminal:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

**Comment by MikeMcQuaid** [comment]
> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

This is wrong. Use the command from the homepage.
