### ISSUE TITLE
SUDO_ASKPASS support broken

### ISSUE THREAD

**Issue by johngun3** [Homebrew/install#313]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I was trying to install homebrew via chef. I set the SUDO_ASKPASS variable correctly, and before this commit was merged installation worked correctly: https://github.com/Homebrew/install/commit/568437e7fe5005ffc5c4a1465ecd50a3f9d581ed
The sudo check that the `have_sudo_access` function performs does not incorporate the optionally supplied SUDO_ASKPASS variable like the rest of the sudo commands do (see `execute_sudo`). Therefore, `/usr/bin/sudo -l mkdir &>/dev/null` will fail because the SUDO_ASKPASS option is not specified, leading to `HAVE_SUDO_ACCESS` being set to false and installation failing.

## What happened (include command output)

Running the homebrew cookbook on chef fails with `Need sudo access on macOS!`

## What you expected to happen

I would expect the installation to work correctly if I correctly specify the SUDO_ASKPASS variable.

**Comment by MikeMcQuaid** [comment]
CC @dawidd6 for this. https://github.com/Homebrew/install/pull/306 was a previous attempted fix. Your best best is probably to submit a pull request yourself @johngun3.

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/install/pull/314, nice work @johngun3!
