### ISSUE TITLE
[Documentation Request] "${HAVE_SUDO_ACCESS}" & "${CI}" for headless / noninterative installs

### ISSUE THREAD

**Issue by mstr3336** [Homebrew/install#332]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] **NA** ~after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?~ 

# TL;DR

Please document `CI` and `HAVE_SUDO_ACCESS` env var usage explicitly.

## What you were trying to do (and why)

I want to set up a sudoless, noninteractive linuxbrew install as part of a [dotbot](https://github.com/anishathalye/dotbot) bootstrap.
I want this to work on my work's HPC (For which I don't have sudo).

My work's HPC does allow use of "sudo" and will ask for a password from stdin, but will refuse after that point. I'd rather the installer just not bother trying to sudo at all.

## What happened (include command output)

Through investigation, mainly by exploring the source of the install script, I was able to find two env vars that must be set in order to allow true non-interactive install. 

```bash
CI="set to anything"
HAVE_SUDO_ACCESS="set to anything but 0"
```

as such, I determined I should install homebrew using:

```bash
CI="headless" HAVE_SUDO_ACCESS="sadly not" /bin/bash -c "$(curl -fsSL "${homebrew_url}")"
```

However, I couldn't find these env vars documented anywhere, really, and google results for both of these were pretty sparse. 
It would be helpful if the requirements for forcing a noninteractive, rootless install could be documented explicitly somewhere, or commented, or echo'd in the install script.

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

<details>
  <summary>Command output</summary>
  <pre>

  ==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew
==> The following existing directories will be made writable by user only:
/home/linuxbrew/.linuxbrew/share/zsh
/home/linuxbrew/.linuxbrew/share/zsh/site-functions

Press RETURN to continue or any other key to abort
  </pre>
</details>

## What you expected to happen

**The usage of the CI and HAVE_SUDO_ACCESS env vars are documented somewhere**

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

```
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew
==> The following existing directories will be made writable by user only:
/home/linuxbrew/.linuxbrew/share/zsh
/home/linuxbrew/.linuxbrew/share/zsh/site-functions

To force linuxbrew to install to your home directory ~/.linuxbrew, set the env var HAVE_SUDO_ACCESS=1

To run this installation without confirmation, set the env var CI="headless"

Press RETURN to continue or any other key to abort
```

## Step-by-step reproduction instructions (by running `brew` commands)

**NA**

**Comment by MikeMcQuaid** [comment]
> However, I couldn't find these env vars documented anywhere, really, and google results for both of these were pretty sparse.
> It would be helpful if the requirements for forcing a noninteractive, rootless install could be documented explicitly somewhere, or commented, or echo'd in the install script.

This isn't something we support explicitly, sorry.
