### ISSUE TITLE
Unable to Completely Uninstall Homebrew and its components, i am not a programmer, please help. 

### ISSUE THREAD

**Issue by meteorwave** [Homebrew/install#333]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I was trying to uninstall homebrew.  I ended up not using the software i wanted for it.  And yesterday, my MAC experienced a bad crash where it could not identify the hard drive.  I want to uninstall the software in case it is causing any issues. 

## What happened (include command output)

The following is the text i received from terminal upon trying the suggested uninstall line found here on GitHub

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Michaels-Air:~ meteorwave$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
Warning: This script will remove:
/Users/meteorwave/Library/Caches/Homebrew/
/Users/meteorwave/Library/Logs/Homebrew/
/usr/local/Caskroom/
/usr/local/Cellar/
/usr/local/bin/brew -> /usr/local/bin/brew
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] y
==> Removing Homebrew installation...
Warning: Failed to delete /usr/local/Caskroom
rm: /usr/local/Caskroom: Permission denied
Warning: Failed to delete /usr/local/Cellar
rm: /usr/local/Cellar: Permission denied
==> Removing empty directories...
Password:
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Caskroom /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks -name .DS_Store -delete
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Caskroom /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks -depth -type d -empty -exec rmdir {} ;
==> Homebrew uninstalled!
The following possible Homebrew files were not deleted:
/usr/local/.com.apple.installer.keep
/usr/local/Frameworks/
/usr/local/Homebrew/
/usr/local/bin/
/usr/local/etc/
/usr/local/include/
/usr/local/lib/
/usr/local/opt/
/usr/local/sbin/
/usr/local/share/
/usr/local/var/
You may wish to remove them yourself.

Michaels-Air:~ meteorwave$ brew bundle dump
-bash: brew: command not found
Michaels-Air:~ meteorwave$ 

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

i expected all of the homebrew files to be deleted but instead i'm left with many different files, as well as some files that I "don't have the authorization to delete"

## Step-by-step reproduction instructions (by running `brew` commands)

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"

**Comment by meteorwave** [comment]
Note, i never ran "brew config" or "brew doctor."  I am not a programmer, i had someone on GitHub show me how to install homebrew so i could run an emulator called FCEUX.  I ended up not using the program, and yesterday my computer crashed HARD, where it could not find the hard drive.  I am concerned the installed files aren't jiving with my (Macbook Air 13-inch, 2017 2.2GHz Dual-Core Intel Core i7; 8 GB 1500 MHz DDR3; Version 10.15.6.  Please don't close my ticket, i just want some assistance with uninstalling the remaining packages left behind from the uninstall process.

**Comment by MikeMcQuaid** [comment]
Homebrew isn't crashing your system. You'll need to figure it out yourself, sorry, we don't provide support here.
