### ISSUE TITLE
[macOS Catalina] Homebrew CLI installation doesn't work without GUI

### ISSUE THREAD

**Issue by strega-nil** [Homebrew/install#334]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

Host OS version:
```
ProductName:    Mac OS X
ProductVersion: 10.15.6
BuildVersion:   19G2021
```

Target OS version:
```
ProductName:    Mac OS X
ProductVersion: 10.15.1
BuildVersion:   19B88
```

VagrantFile:
```rb
Vagrant.configure('2') do |config|
  # give them extra time to boot up
  config.vm.boot_timeout = 600

  config.vm.box = 'ramsey/macos-catalina'
  config.vm.hostname = 'vcpkgmm'
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
```

## What you were trying to do (and why)

I was trying to install homebrew vagrant VM, for vcpkg's CI system.

## What happened (include command output)

Brew failed to install xcode

<details>
  <summary>Command output</summary>
  <pre>
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/bin
/usr/local/etc
/usr/local/include
/usr/local/lib
/usr/local/sbin
/usr/local/share
/usr/local/var
/usr/local/opt
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var/homebrew
/usr/local/var/homebrew/linked
/usr/local/Cellar
/usr/local/Caskroom
/usr/local/Homebrew
/usr/local/Frameworks
==> The Xcode Command Line Tools will be installed.

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /usr/sbin/chown vagrant /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /Users/vagrant/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/vagrant/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown vagrant /Users/vagrant/Library/Caches/Homebrew
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
objc[652]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11bf62cc0) and /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11bd7ece8). One of the two will be used. Which one is undefined.
==> Installing the Command Line Tools (expect a GUI popup):
==> /usr/bin/sudo /usr/bin/xcode-select --install
xcode-select: error: no developer tools were found, and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
Press any key when the installation has completed.
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
xcode-select: error: invalid developer directory '/Library/Developer/CommandLineTools'
Failed during: /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
  </pre>
</details>

## What you expected to happen

Brew to install xcode, and then install itself.

## Step-by-step reproduction instructions (by running `brew` commands)

`vagrant up` with that VagrantFile on macOS, then

```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

**Comment by strega-nil** [comment]
I'm going to be working around this by building my own box that has xcode installed already, but I just hoped to let you know.

**Comment by strega-nil** [comment]
Update: I'm pretty sure someone at Apple screwed up here; I can no longer run `xcode-select --install` at all, even with a GUI.

**Comment by MikeMcQuaid** [comment]
This is a known issue, sorry.

**Comment by strega-nil** [comment]
@MikeMcQuaid it is? I don't see it anywhere...

**Comment by MikeMcQuaid** [comment]
@strega-nil Sorry, we don't have a documented list anywhere of known issues such as this 😭
