### ISSUE TITLE
Uninstall failing on new Yosemite build

### ISSUE THREAD

**Issue by mafrosis** [Homebrew/install#34]
Sometimes a Homebrew `install` will fail (due to slow network, I think), leaving me with a broken install. As suggested, I attempt to `uninstall`. This is the output:

    bash-3.2# ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
    Warning: This script will remove:
    /Library/Caches/Homebrew/
    /usr/local/.git/
    Are you sure you want to uninstall Homebrew? [y/N] y
    ==> Removing Homebrew installation...
    /usr/bin/find: illegal option -- r
    usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
           find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
    Warning: Failed during: /usr/bin/find -E -regex .*/info/([^.][^/]*.info|dir) -exec /bin/bash -c /usr/bin/install-info\ --delete\ --quiet\ {}\ "$(dirname\ {})/dir" ;
    /usr/bin/find: illegal option -- t
    usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
           find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
    Warning: Failed during: /usr/bin/find -type l -lname */Cellar/* -exec unlink {} ;
    ==> Removing empty directories...
    /usr/bin/find: illegal option -- n
    usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
           find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
    Warning: Failed during: /usr/bin/find -name .DS_Store -delete
    /usr/bin/find: illegal option -- e
    usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
           find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
    Warning: Failed during: /usr/bin/find -depth -type d -empty -exec rmdir {} ;
    Warning: Homebrew partially uninstalled (but there were steps that failed)!
    To finish uninstalling rerun this script with `sudo`.

Notice I'm running the script as root.

**Comment by mikemcquaid** [comment]
What's the output of `which find`?

**Comment by mafrosis** [comment]
`/usr/bin/find` - as shown in the "illegal option" messages

**Comment by mikemcquaid** [comment]
CC @xu-cheng @DomT4 for thoughts

**Comment by xu-cheng** [comment]
What's he output of `find --version`?

**Comment by mikemcquaid** [comment]
@xu-cheng It'll be `illegal option` :sob:

**Comment by DomT4** [comment]
Unless `find` has been replaced with GNU's `find`, which may be what Xu wanted to double check.

**Comment by mikemcquaid** [comment]
Aah.

**Comment by mafrosis** [comment]
> find --version
    find: illegal option -- -
    usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
           find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

This is a base Yosemite image being spun up in VMWare - nothing should be out of the OSX ordinary...

**Comment by xu-cheng** [comment]
Yes. I do want to check whether is a gnu or bsd find.  I don't have Mac access for now to check for myself. So what is the equivalent argument for bsd find?

**Comment by mafrosis** [comment]
It looks to me like the path is missing in the params to `find`:

    /usr/bin/find -name .DS_Store -delete
    /usr/bin/find: illegal option -- n

Adding in a dot succeeds:

    /usr/bin/find . -name .DS_Store -delete

**Comment by xu-cheng** [comment]
I see what's happening. You don't have any path for find to search for. We need to check whether the check list of paths are empty.

**Comment by DomT4** [comment]
>  So what is the equivalent argument for bsd find?

To my knowledge BSD `find` has no `--version` output or equivalent. BSD are proudly stubborn about producing utilities that are functional and not much else heh.

Xu beat me to the reasoning behind the failure :smile:.
