### ISSUE TITLE
install.sh: broken no_usable_ruby

### ISSUE THREAD

**Issue by maxim-belkin** [Homebrew/install#342]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install Homebrew after #338

## What happened (include command output)

quick reproducer (extracted two functions from install.sh + added a few debugging messages):

```sh
# Please sync with 'test_ruby()' in 'Library/Homebrew/utils/ruby.sh' from Homebrew/brew repository.
test_ruby () {
  if [[ ! -x $1 ]]
  then
    return 1
  fi

  "$1" --enable-frozen-string-literal --disable=gems,did_you_mean,rubyopt -rrubygems -e \
    "abort if Gem::Version.new(RUBY_VERSION.to_s.dup).to_s.split('.').first(2) != \
              Gem::Version.new('$REQUIRED_RUBY_VERSION').to_s.split('.').first(2)" 2>/dev/null
}

no_usable_ruby() {
  local ruby_exec
  which -a ruby | while read -r ruby_exec; do
    if test_ruby "$ruby_exec"; then
      echo $ruby_exec works
      return 1
    else
      echo $ruby_exec does not work
    fi
  done
  echo still here
  return 0
}

no_usable_ruby
```

on a Mac with /usr/bin/ruby == ruby 2.6.3p62 outputs
```
/Users/mbelkin/.rbenv/shims/ruby does not work
/usr/local/opt/ruby/bin/ruby does not work
/usr/bin/ruby works
still here
```

## What you expected to happen

not see `still here` in the above message (well, install Homebrew, actually).

## Step-by-step reproduction instructions (by running `brew` commands)

See "What happened" section above.

Also, we need to update the title of this section because one can't run `brew` commands until after they install Homebrew.

**Comment by MikeMcQuaid** [comment]
Is this because the `return` is leaving the `while` and not the function?

**Comment by maxim-belkin** [comment]
the body of the `which -a ruby | while read...` block is executed in a subshell, so a `return` can't exit from the function.

**Comment by MikeMcQuaid** [comment]
Doh 🤦🏻

**Comment by gromgit** [comment]
Good point. Should've used a process substitution instead.
