### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by brunoamorim13** [Homebrew/install#35]
Hello, every time I try to run a command with brew, I keep getting this error:

`-bash: /usr/local/bin/brew: /bin/bash^M: bad interpreter: No such file or directory`

I'm currently running it on El Capitan, and I can't seem to find any way to fix this. I've tried re-installing it several times but it won't work. 

THank you!

**Comment by ilovezfs** [comment]
@brunoamorim13 Did you ever open the file in an editor? How did you obtain brew?

Can you check this too?
```
git config --global -l | grep crlf
```
and
```
cd /usr/local ; git config -l | grep crlf
```

**Comment by brunoamorim13** [comment]
@ilovezfs 

I opened it yes, but it was really messed up, nothing possible comprehensible.

As for the commands you asked, here is the result
`core.autocrlf=input
core.autocrlf=false`

**Comment by ilovezfs** [comment]
I was unaware (but I haven't checked) that brew doctor can do any read-write operations. That doesn't sound correct.

**Comment by mikemcquaid** [comment]
@brunoamorim13 Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information in https://github.com/Homebrew/homebrew/issues/new so we can help you with your problem.

Thanks!
