### ISSUE TITLE
Sanity check prevents installation on Linux Arm

### ISSUE THREAD

**Issue by steveh** [Homebrew/install#363]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

Raspbian 10 (Debian buster) on a Raspberry Pi 2

## What you were trying to do (and why)

Install Homebrew on Linux ARM, which appears to be a [supported configuration](https://docs.brew.sh/Homebrew-on-Linux).

This appears to be a [recent change](https://github.com/Homebrew/install/pull/347) to warn Arm Mac users.

## What happened (include command output)

"Homebrew is only supported on Intel processors!"

<details>
  <summary>Command output</summary>
  <pre>
$ uname -sm
Linux armv7l

$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
Homebrew is only supported on Intel processors!
  </pre>
</details>

## What you expected to happen

Installation to proceed

## Step-by-step reproduction instructions (by running `brew` commands)

1. Obtain an ARM Linux machine, e.g. a Raspberry Pi
2.`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by MikeMcQuaid** [comment]
This is intentional, we do not support Homebrew ARM on Linux. Use another installation option: https://docs.brew.sh/Installation
