### ISSUE TITLE
PR #361 appears to have broken non-interactive install

### ISSUE THREAD

**Issue by techmaven** [Homebrew/install#364]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x ] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Run non-interactive brew install:
```sudo su - admin -c "set -x; export CI=1; echo | $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"```
MacOS Catalina
## What happened (include command output)

Relevant portion of `install.sh` log with -x:
```
+zsh:299> have_sudo_access
+have_sudo_access:1> local -a args
+have_sudo_access:2> [[ -n '' ]]
+have_sudo_access:4> [[ -n 1 ]]
+have_sudo_access:5> args=( -n )
+have_sudo_access:8> [[ -z '' ]]
+have_sudo_access:9> [[ -n -n ]]
+have_sudo_access:10> SUDO='/usr/bin/sudo -n'
+have_sudo_access:14> [[ -n 1 ]]
+have_sudo_access:15> '/usr/bin/sudo -n' -l mkdir
+have_sudo_access:19> HAVE_SUDO_ACCESS=127
+have_sudo_access:22> [[ -z '' ]]
+have_sudo_access:22> [[ 127 -ne 0 ]]
+have_sudo_access:23> abort 'Need sudo access on macOS (e.g. the user admin to be an Administrator)!'
+abort:1> printf '%s\n' 'Need sudo access on macOS (e.g. the user admin to be an Administrator)!'
Need sudo access on macOS (e.g. the user admin to be an Administrator)!
+abort:2> exit 1
```
Combining sudo command and arg into a single variable (`install.sh` line 79) causes them to be parsed as a single word, resulting in `"/usr/bin/sudo -n" file not found` error (errno 127).

<details>
  <summary>Command output</summary>
  <pre>

See previous section
  </pre>
</details>

## What you expected to happen

Normal Homebrew install, which functioned normally on Nov 30, 2020.

## Step-by-step reproduction instructions (by running `brew` commands)

See command line above

**Comment by gromgit** [comment]
It looks like you're using zsh to run the install script, which is not supported. Please run the script under bash instead.

**Comment by MikeMcQuaid** [comment]
> It looks like you're using zsh to run the install script, which is not supported. Please run the script under bash instead.

Yes, this.
