### ISSUE TITLE
Installation without hitting "ENTER"

### ISSUE THREAD

**Issue by andygrunwald** [Homebrew/install#44]
Hey,

i install Homebrew with my dotfiles and encountered, that during an installation a Return enter type is necessary. See https://github.com/Homebrew/install/blob/master/install#L186

Is there any way how to avoid the manual return (during the keyboard) and automate the installation?
Is there a small trick how we can "fake" STDIN.tty?

**Comment by UniqMartin** [comment]
Assuming you have a local copy of the installer, you can do something like `echo | INSTALLER`. This will send a single return via `STDIN` to the installer, but more importantly `STDIN.tty?` will return false and cause the installer to run in non-interactive mode. Substitute `INSTALLER` with you preferred way of invoking the Homebrew installer.

A similar effect can be achieved by redirecting `STDIN` to a file, e.g. `INSTALLER < /dev/null`. (I haven't tested this locally, but it should work.)
