### ISSUE TITLE
error creating HOMEBREW_CACHE tree

### ISSUE THREAD

**Issue by graemej** [Homebrew/install#48]
It looks like this change (https://github.com/Homebrew/install/commit/d7423c3feec9ca8b0f0c15ef3f7a84dcfd9da406)  to `HOMEBREW_CACHE` causes a path through the installer to fail due to missing directories.

I believe the root cause is the cache location changing from `/Library/Caches/Homebrew` to `$HOME/Library/Caches`.

There's no guarantee that the user will have a `~/Library/Caches` directory so the setup fails at the first `mkdir` call.  The commands issued look like:

```
  /usr/bin/sudo /bin/chmod g+rwx /usr/local/.
  /usr/bin/sudo /usr/sbin/chown myuser /usr/local/.
  /usr/bin/sudo /usr/bin/chgrp mygroup /usr/local/.
  /usr/bin/sudo /bin/mkdir /Users/myuser/Library/Caches/Homebrew
  mkdir: /Users/myuser/Library/Caches: No such file or directory
```

If moving the cache from a shared to user-specific location was intentional the the `mkdir` invocation should probably have a `-p` to create missing parent directories.  ping: @xu-cheng.

**Comment by ilovezfs** [comment]
>There's no guarantee that the user will have a ~/Library/Caches

That strains credulity.

**Comment by graemej** [comment]
fiw: a packer build created the user and home directories that lacked the `~/Library/Caches` tree.

**Comment by ilovezfs** [comment]
OS X creates ~/Library/Caches before a user even logs in for the first time, so that sounds like a packer bug to me.

**Comment by MikeMcQuaid** [comment]
> OS X creates ~/Library/Caches before a user even logs in for the first time, so that sounds like a packer bug to me.

Agreed, sorry!
