### ISSUE TITLE
Alternative Homebrew uninstaller script

### ISSUE THREAD

**Issue by SteveBenner** [Homebrew/install#51]
Hi, I just wanted to share [a script that I wrote as a Homebrew uninstaller and diagnostic tool](https://gist.github.com/SteveBenner/11254428). It has proven robust and effective for myself and others, and I thought it would be good to include mention of this somewhere on an official Homebrew repo/wiki/website in case it might benefit anyone.

My personal aspiration is to become a regular contributor to the Homebrew project at some point down the road, but for now I would especially love to hear from anyone on the team interested in collaborating on the uninstaller code. Let me know what you think.

**Comment by MikeMcQuaid** [comment]
Would you consider adding the additional features to the script in this repo?

**Comment by DomT4** [comment]
I partially played with your script before now, before it was GPLv3'd, as an alternative to what became our current `uninstall` script. The changes I made still sit in a tap [here](https://github.com/DomT4/homebrew-removal/blob/master/cmd/brew-selfdestruct.rb), which I'd forgotten about till I saw your name & wondered why it sounded familiar.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this.
