### ISSUE TITLE
Install blocked on linux arm (aarch64) but [documentation](https://docs.brew.sh/Homebrew-on-Linux#arm) claims it should work

### ISSUE THREAD

**Issue by dmccaffery** [Homebrew/install#514]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

Unable to install: Ubuntu 20.10 (Aarch64)

## What you were trying to do (and why)

Attempt to install homebrew on ubuntu 20.10 arm64 (aarch64) as per documentation: 

https://docs.brew.sh/Homebrew-on-Linux#arm

## What happened (include command output)

Execute the following:

```sh
sudo apt-get install build-essential curl file git ruby
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Receive immediate output indicating arm is not supported.

<details>
  <summary>Command output</summary>
  <pre>

  Homebrew is only supported on Intel processors!

  </pre>
</details>

## What you expected to happen:

1. Homebrew should install successfully *OR* documentation should be updated to indicate that ARM is not supported on Linux anymore

## Step-by-step reproduction instructions (by running `brew` commands)

```sh
sudo apt-get install build-essential curl file git ruby
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Looking at recent commits, this was added (related to supporting apple silicon):

https://github.com/Homebrew/install/blame/c2cfecf3e32181f04f83c68a2e0c06d78951f310/install.sh#L353-L356

**Comment by MikeMcQuaid** [comment]
This is intentional, the installer will not install in unsupported configurations, sorry.
