### ISSUE TITLE
Brew install suggest impossible actions

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/install#516]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install and use brew

## What happened (include command output)
Brew told me to run an impossible command

<details>
  <summary>Command output</summary>
  <pre>
==> Next steps:

    Run brew help to get started
    Further documentation:
    https://docs.brew.sh
    Add Homebrew to your PATH in /Users/sean/.zprofile:
    echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/sean/.zprofile
    eval $(/opt/homebrew/bin/brew shellenv)
  </pre>
</details>

## What you expected to happen

Have brew tell me to add the command to my path BEFORE telling me to use `brew help`, or have brew at itself to my path once

## Step-by-step reproduction instructions (by running `brew` commands)

```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by SMillerDev** [comment]
I'm not able to make a pull request today, but this issue will hopefully remind me to make one.

**Comment by MikeMcQuaid** [comment]
@carlocab could you take a look at tweaking these instructions?

**Comment by carlocab** [comment]
Sure, looking into it.

**Comment by quackduck** [comment]
That should fix it.
