### ISSUE TITLE
installation fails with HOMEBREW_FORCE_BREWED_{CURL,GIT}=1 HOMEBREW_NO_AUTO_UPDATE=1

### ISSUE THREAD

**Issue by andreineculau** [Homebrew/install#522]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I'm bootstrapping CI runs by installing dependencies via homebrew/linuxbrew.
I have recently widened the types of machines to include older ubuntu/debian which fail the curl/git minimum version checks. So I have enabled `HOMEBREW_FORCE_BREWED_{CURL,GIT}=1` without realizing that the default behavior is "if minimum version is not met, then install brewed curl/git" anyway, so the last error still remained `Error: Curl must be installed and in your PATH!
2500. Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force` https://github.com/rokmoln/support-firecloud/runs/1682906099?check_suite_focus=true#step:4:2499

It turns out that I was pre-setting `HOMEBREW_NO_AUTO_UPDATE=1` (since determinism is ideal in CI) before installing homebrew.

**UPDATE: there's another detail that plays an important role!** The failure in the CI happens because *linuxbrew* is pre-installed by Github Actions, I run the `uninstall` script in this repo, and then proceed to reinstall. I don't see any errors while uninstalling https://github.com/rokmoln/support-firecloud/runs/1682906099?check_suite_focus=true#step:4:2224 , but I'm guessing it is an important detail. Locally, I can reproduce by cancelling a homebrew installation while `Tapping homebrew/core...` and trying to install again.

## What happened (include command output)

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

<details>
  <summary>Command output</summary>
  <pre>

 * [new tag]             2.7.2      -> 2.7.2
2497
 * [new tag]             2.7.3      -> 2.7.3
HEAD is now at b29c27b9a Merge pull request #10251 from SeekingMeaning/bump-pr-match
Error: Curl must be installed and in your PATH!
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force
Error: Process completed with exit code 1.

  </pre>
</details>

## What you expected to happen

To proceed with downloading/installing bottled curl&git and finish installing brew.

## Step-by-step reproduction instructions (by running `brew` commands)

```
docker run -it --rm debian:8
# ---
apt-get update
apt-get install -y curl git sudo
useradd -m -s /bin/bash linuxbrew
echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
su linuxbrew
# ---
export HOMEBREW_FORCE_BREWED_CURL=1
export HOMEBREW_FORCE_BREWED_GIT=1
export HOMEBREW_NO_AUTO_UPDATE=1
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# WAIT FOR Tapping homebrew/core AND HIT CTRL-C
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by andreineculau** [comment]
I think the check needs to be stricter

https://github.com/Homebrew/install/blob/b778679/install.sh#L623-L639 runs `brew update` (and thus tapping homebrew/core) if the directory doesn't exist but it does - at least locally I have a `.git` there.

And now I understand what's with `HOMEBREW_NO_AUTO_UPDATE=1` as well. Because the folder exists, there's no `brew update` triggered by this installation script, but then we will invoke brew later on, which will check "should i auto-update? yes!" and runs `brew update` which will autofix the homebrew/core tap.

**Comment by MikeMcQuaid** [comment]
This falls very much into an edge case produced by your unique way of doing things here. We'll review a pull request to fix this behaviour but this isn't something we'll be working on, sorry.
