### ISSUE TITLE
Speeding up install times

### ISSUE THREAD

**Issue by carlocab** [Homebrew/install#523]
On a 1 Mbps Internet connection, installing Homebrew would, in theory, take about ~1 hour. As a one-time setup cost, this isn't _too_ bad. However, it would be nice to make this better, especially given that most of the data transferred is `git` metadata that most users won't be making direct use of themselves.

Here are some ideas (not all mine, especially not the good parts) for making this better, but feel free to chime in with alternatives:
1. Download a `tar`/`zip` of the homebrew/core repo to bootstrap the installation. `brew update` could then perhaps be done in the background after installation.
2. At install time, fetch only the `tree` and `commit` objects, but not the `blob` objects. A complete fetch could be deferred to a post-install `brew update`. (Cf. https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/)

Some other related but somewhat orthogonal ideas are mentioned in the following discussions:
https://github.com/Homebrew/discussions/discussions/225
https://github.com/Homebrew/discussions/discussions/226

**Comment by sjackman** [comment]
> At install time, fetch only the tree and commit objects, but not the blob objects. A complete fetch could be deferred to a post-install brew update. (Cf. https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/)

I suspect that a complete fetch of the blobs may never be necessary.

**Comment by alebcay** [comment]
> At install time, fetch only the tree and commit objects, but not the blob objects. A complete fetch could be deferred to a post-install brew update. (Cf. github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors)

I'm encouraged by the clone speedup on the client side from those statistics, but am a bit concerned about the performance impact on GitHub's side, seeing as they asked us to unshallow our clones recently.

From that blog post, it also looks like (if I'm reading this right, anyways) there is a penalty on performance in subsequent fetches. Not sure how that would impact subsequent `brew update` operations, but I think that it should be taken into consideration.

Finally, I doubt that it would be too big of an issue (hopefully), but it's also mentioned that blobless partial clones may trigger automatic GC more often than a full clone. Not sure about how that may impact us but I figure it's something to look out for.

Generally, I do like this option since the changes are minimal, but I do think some more investigation may be needed with regard to not only how it impacts install performance but also update performance.

**Comment by sjackman** [comment]
> From that blog post, it also looks like (if I'm reading this right, anyways) there is a penalty on performance in subsequent fetches. Not sure how that would impact subsequent brew update operations, but I think that it should be taken into consideration.

Compare `apple/swift fetch performance` of `T5 full fetch in a fully cloned repository` to `T10 full fetch in a blobless partially cloned repository`.

Test# | scenario | git fetch avgRT | git reset –hard | git CPU spent per fetch
--- | --- | --- | --- | ---
T5 | full fetch in a fully cloned repository | 350ms | 80ms | 20ms (Lowest)
T10 | full fetch in a blobless partially cloned repository | 300ms | 150ms | 35ms (1.5x more than to T5)

Wall time of `git fetch` decreases by 14% from 350 to 300 ms, and CPU time increases by 75% from 20 to 35 ms.

**Comment by alebcay** [comment]
> Wall time of git fetch decreases by 14% from 350 to 300 ms, and CPU time increases by 75% from 20 to 35 ms.

Looks like I did misunderstand that section of the post. Thanks for pointing it out to me. As you've pointed out, this does increase the git CPU usage on GitHub's end. So I guess my primary concern now is just the impact it poses to GitHub.

**Comment by sjackman** [comment]
Ah, I had assumed `git CPU spent` was client CPU time, but looks like it's GitHub server CPU time.

> *We are investigating ways to reduce this CPU cost in partial clones.*

Emphasis theirs. Looks like they're working on it.

**Comment by Rylan12** [comment]
Something to keep in mind: the structure of the homebrew/core repository is such that trees take up more space than blobs.

See the output of [`git sizer`](https://github.com/github/git-sizer):

```
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Commits                    |           |                                |
|   * Count                    |   216 k   |                                |
|   * Total size               |  70.8 MiB |                                |
| * Trees                      |           |                                |
|   * Count                    |   433 k   |                                |
|   * Total size               |  32.0 GiB | *****************              |
|   * Total tree entries       |   889 M   | *****************              |
| * Blobs                      |           |                                |
|   * Count                    |   238 k   |                                |
|   * Total size               |   486 MiB |                                |
| * Annotated tags             |           |                                |
|   * Count                    |     0     |                                |
| * References                 |           |                                |
|   * Count                    |     5     |                                |
```

So a blobless partial clone will only help to a degree. It may be worth running some more thorough tests to confirm that this is a solution that makes enough of a difference to be worth it.

A treeless clone would reduce this load significantly, but isn't a good option for our users for reasons stated in the [blog](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) [posts](https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/).

---

Separately, we should probably reach out to GitHub before making a switch to blobless partial clones given that it does appear that CPU usage is higher for both clones and fetches.

> Blobless partial clones do increase the Git CPU costs on the server somewhat, but the network data transfer is much less than a full clone or a full fetch from a shallow clone. The extra CPU cost is likely to become less important if your repository has larger blobs than our test repositories.

Glancing at [the data in the article](https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/#user-content-test-repository-characteristics), Homebrew/homebrew-core seems pretty similar in size to apple/swift (the middle option), so this probably doesn't apply.

---

Lastly, as was mentioned:

> It is worth noting that blobless partial clones might trigger automatic garbage collection more often than a full clone. This is a natural byproduct of splitting the data into a larger number of small requests. We have work in progress to make Git’s repository maintenance be more flexible, especially for large repositories where a full repack is too time-consuming. Look forward to more updates about that feature here on the GitHub blog.

It's probably worth noting that our use case differs slightly from what the articles are discussing. We are expecting that the vast majority of users will never need to do anything other than fetch via `brew update`. There is also a `brew log` command that will still work with blobless clones. I don't think that potential issues like the `gc` issue will be a big deal for us. Howe ofter are there objects that are cleaned for non-developers anyway?

Homebrew developers should probably continue to use a full clone, though.

**Comment by MikeMcQuaid** [comment]
> * Download a `tar`/`zip` of the homebrew/core repo to bootstrap the installation. `brew update` could then perhaps be done in the background after installation.

This still requires a full fetch of the Git repository so doesn't seem to speed things up.

---

I've been (slowly) working on some of these issues with the GitHub folks. I don't think we or GitHub are at the point where we can use partial clones yet. https://github.com/Homebrew/brew/pull/8885 was my previous experiment but I couldn't make it work.

The option that we can/could adopt that will definitely speed things up in future is to rewrite the history (again) of the repositories.

In particular making Homebrew/homebrew-core do these things would result in a large speedup and avoid degradation in future:
- use merge commits instead of rebase or squash merges (to avoid breaks in history between PRs and the `master` merges)
- split formulae into e.g. 26 directories by first letter of their name so `Formulae/w/wget.rb` etc.
- potentially truncate some of the history

**Comment by sjackman** [comment]
>> Download a tar/zip of the homebrew/core repo to bootstrap the installation. brew update could then perhaps be done in the background after installation.

> This still requires a full fetch of the Git repository so doesn't seem to speed things up.

The proposal here is to extract https://github.com/Homebrew/homebrew-core/archive/master.tar.gz to bootstrap and get the user up and running quickly. The user can start using `brew install` right away. In the mean time, `git fetch` can download the `.git` directory, potentially in the background. Simpler though is to keep this process in the foreground, and display a message explaining that the user can open a new terminal and `brew install` there, while the download is happening.

**Comment by MikeMcQuaid** [comment]
> The user can start using `brew install` right away. In the mean time, `git fetch` can download the `.git` directory, potentially in the background. Simpler though is to keep this process in the foreground, and display a message explaining that the user can open a new terminal and `brew install` there, while the download is happening.

It won't make the overall installer any faster (actually: it'll be slower) and doing `brew install` requires a network connection do anything useful which will mean we have competing demands on the same (slow) network connection.

Additionally, running this in the background and displaying progress/status/recovering from failure to the user is non-trivial and will add new failure cases that I'm not sure justifies the relatively small number of people we have complaining about a one-time speed issue.

**Comment by sjackman** [comment]
> Something to keep in mind: the structure of the homebrew/core repository is such that trees take up more space than blobs.

Good catch! That hadn't occurred to me.

```console
$ git cat-file -p e4c7c20286cfbb537af28916203f30c2f692222a | head -n3
100644 blob fc8024b5cdc7acf7fe8ae1a892af48a8a4583ddc	a2ps.rb
100644 blob f09e03d70aa29ae40c86ecf8a59cb5a9cd56d747	a52dec.rb
100644 blob 3d216bcbff415db8ffe19d6053f32801578ce0f8	aacgain.rb
$ git cat-file tree e4c7c20286cfbb537af28916203f30c2f692222a | wc -c
  210539
$ git cat-file tree e4c7c20286cfbb537af28916203f30c2f692222a | gzip | wc -c
  145766
$ calc 145766/210539
	~0.69234678610613710524
$ git log --oneline | wc
  216174  983646 8210965
$ git rev-list --objects --filter=blob:none 7529b21a30 | git cat-file --batch-check='%(rest)' | grep -cx Formula
215441
$ calc '145766*215441/1e9'
	31.403972806
$ git rev-list --objects --filter=blob:none 7529b21a30 | git cat-file --batch-check='%(objectsize) %(rest)' | awk '$2 == "Formula" {sum += $1} END {print sum / 1e9}'
34.278
```
So each compressed `Formula` tree object is 165 kb, and we have 215,441 such objects. Without Git pack files, we'd expect these tree objects to take 31.4 GB! Which is 🤯. @Rylan12 reported above in https://github.com/Homebrew/install/issues/523#issuecomment-759209685  that the actual size is 32 GB. We are super lucky that pack files are a thing, and that these pack files of tree objects compress so well, because an individual tree objects do not compress well (one compressed tree object is 70% of its uncompressed size).

**Comment by sjackman** [comment]
> use merge commits instead of rebase or squash merges (to avoid breaks in history between PRs and the master merges)

I don't believe that will help users, as the commit objects in PRs are not transferred to users by default. Using merge commits could make the situation worse in fact, as it would add more `Formula` tree objects if there were multiple commits in the PR.

The PR commits do exist on the GitHub server side. They are transferred to the client if the `.git/config` has been configured to fetch `refs/remotes/origin/pr/*`, which is not typical.

**Comment by sjackman** [comment]
To add to @Rylan12 's data in https://github.com/Homebrew/install/issues/523#issuecomment-759209685

| Clone    | Time  | Received | du -hs .git/ |
|----------|------:|---------:|-------------:|
| Full     | 151 s |   355 MB |       382 MB |
| Blobless | 108 s |   298 MB |       319 MB |
| Treeless |  37 s |    57 MB |        64 MB |
| Shallow  |  18 s |     5 MB |         6 MB |

MacBook Pro (13-inch 2019) 1.7 GHz Quad-Core Intel Core i7
macOS Catalina 10.15.7
git version 2.24.3 (Apple Git-128)
Google Internet speed test 33.5 Mbps download 26.5 Mbps upload
Vancouver 🇨🇦

@Rylan12 Our full and blobless times are in the same realm, but our treeless and shallow times are not.

**Comment by Rylan12** [comment]
For my previous test, I used Homebrew's `git` so here are some updated metrics using system `git`. They're very similar to yours. I actually can't reproduce the incredibly short clone times that I reported above, though, so I think I may have copied the wrong number or something...

| Clone | Time | Received | `du -hs .git/` |
| --- | ---: | ---: | ---: |
| Full | 227 s | 352 MB | 367 MB |
| Blobless | 113 s | 301 MB | 327 MB |
| Treeless | 28 s | 52 MB | 65 MB |
| Shallow | 16 s | 5 MB | 6 MB |

MacBook Pro (13-inch, Early 2015) 2.7 GHz Dual-Core Intel Core i5
macOS Big Sur 11.1
git version 2.24.3 (Apple Git-128)
Google Internet speed test 33.5 Mbps download 26.5 Mbps upload
Cleveland, OH 🇺🇸

**Comment by MikeMcQuaid** [comment]
> I don't believe that will help users, as the commit objects in PRs are not transferred to users by default. Using merge commits could make the situation worse in fact, as it would add more `Formula` tree objects if there were multiple commits in the PR.

It will help users because the `refs/prs` are still part of the ref space used by the server when negotiating that needs to be sent to the client and because GitHub currently (not announced or documented so never rely on this behaviour) does not prune/garbage collect unconnected commits after 30 days (as is it the Git default.

--- 

Our slowness problems for the vast majority of users are a problem with fetches rather than fresh clones. Bear in mind given our load that the CPU time on GitHub's side will be a major factor in any outcome we adopt.

**Comment by shifujun** [comment]
Why Homebrew cannot use a CDN solution like CocoaPods? https://github.com/CocoaPods/cdn.cocoapods.org

**Comment by MikeMcQuaid** [comment]
@shifujun It's possible but it would be a lot of work.

**Comment by andreineculau** [comment]
> a bit concerned about the performance impact on GitHub's side, seeing as they asked us to unshallow our clones recently.

This is rather curious since https://github.com/actions/checkout (written by Github themselves) clones by default with `depth: 1`, which is what "~everyone" on Github Actions uses to checkout, including the homebrew repos. The only difference is if you run `git clone --depth` (without the newer `--single-branch`) and the setup to `git fetch` only one ref in actions/checkout, but that is something that can easily be ported. Hope this bit of info helps.

**Comment by carlocab** [comment]
It's not that curious, I think. The load on GitHub's servers depends on
- the structure of the GitHub repository being accessed; and,
- the frequency of `fetch`es from that repository.

It seems that, in the vast majority of cases, shallow clones aren't that taxing on GitHub servers, so it's fine for the checkout action to clone shallowly by default. See the blog entry [linked above](https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/).

**Comment by MikeMcQuaid** [comment]
> This is rather curious since https://github.com/actions/checkout (written by Github themselves)

I also work at GitHub.

> which is what "~everyone" on Github Actions uses to checkout, including the homebrew repos

No, we (Homebrew) don't use that to checkout either in the actions we provide, in our CI, when Homebrew is being run in CI elsewhere and the GitHub Actions images where Homebrew is already included.

> Hope this bit of info helps.

Sorry, given it was entirely incorrect, it didn't help.

**Comment by MikeMcQuaid** [comment]
> It seems that, in the vast majority of cases, shallow clones aren't that taxing on GitHub servers

Yes. This is specific for us to homebrew-cask and homebrew-core. Regardless, though, if you are doing a shallow clone it should be because you don't expect it to update it as the update process will get increasingly slow and expensive (for client and server) over time. This makes sense for CI images which are discarded but not the Homebrew installer.

**Comment by sjackman** [comment]
> split formulae into e.g. 26 directories by first letter of their name so Formulae/w/wget.rb etc.

This seems like the proper fix to reduce the size of the tree objects in the long run.

**Comment by jonchang** [comment]
On a fresh clone of homebrew/core:

```console
% du -d0 -h .
416M	.

% git filter-repo --filename-callback '
if filename.startswith(b"Formula/"):
  return b"Formula/" + filename[8:9] + b"/" + filename[8:]
else:
  return filename
'

Parsed 217674 commits
New history written in 114.26 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
Updating files: 100% (10920/10920), done.
HEAD is now at 944c8a05722 wget: update 1.21.1 bottle.
Enumerating objects: 1113919, done.
Counting objects: 100% (1113919/1113919), done.
Delta compression using up to 4 threads
Compressing objects: 100% (248108/248108), done.
Writing objects: 100% (1113919/1113919), done.
Total 1113919 (delta 862716), reused 1113858 (delta 862661), pack-reused 0
Completely finished after 641.81 seconds.

% du -d0 -h .
213M	.

% git sizer --verbose
Processing blobs: 239731                        
Processing trees: 656514                        
Processing commits: 217674                        
Matching commits to trees: 217674                        
Processing annotated tags: 0                        
Processing references: 3                        
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Commits                    |           |                                |
|   * Count                    |   218 k   |                                |
|   * Total size               |  59.7 MiB |                                |
| * Trees                      |           |                                |
|   * Count                    |   657 k   |                                |
|   * Total size               |  2.04 GiB | *                              |
|   * Total tree entries       |  58.1 M   | *                              |
| * Blobs                      |           |                                |
|   * Count                    |   240 k   |                                |
|   * Total size               |   490 MiB |                                |
| * Annotated tags             |           |                                |
|   * Count                    |     0     |                                |
| * References                 |           |                                |
|   * Count                    |     3     |                                |
...
```

**Comment by sjackman** [comment]
I'm surprised (and sad) that using the initial character of the formula name only saved us roughly half the disk space. Does using the first two initial characters somehow magically have a more substantial effect?

**Comment by MikeMcQuaid** [comment]
> I'm surprised (and sad) that using the initial character of the formula name only saved us roughly half the disk space.

I don't think the disk space is the main thing worth optimising for but instead the `git clone`/`git fetch` speed.

**Comment by jonchang** [comment]
The clone time is definitely improved with the sharded repository.

**Comment by MikeMcQuaid** [comment]
@jonchang Yup, sorry, I agree there and wasn't disagreeing with anything you said above. I guess my point is just for us all to remember what variables are being optimised for and why.

**Comment by jonchang** [comment]
Qualitatively, the time savings for initial clone for a sharded repository is mostly on the local time, and not from the reduced repository size. I'll have to do some instrumentation and ideally set something up where I can look at server CPU usage before I have any real results though. This was mostly just to see what a sharded repository would look like in comparison to our current repository.

**Comment by sjackman** [comment]
>> I'm surprised (and sad) that using the initial character of the formula name only saved us roughly half the disk space.

> I don't think the disk space is the main thing worth optimising for but instead the git clone/git fetch speed.

Size on disk is a very good proxy for data transferred, and I'm working on the assumption that data transferred is a good proxy for clone speed, when during a `git clone` the amount of data being transferred is large. `git fetch` speed is trickier, as I'm assuming GitHub server CPU time plays more of a factor when the data being transferred is less.

**Comment by Bo98** [comment]
Something related worth mentioning is that I'm seeing significant a number of reports now of people unable to install Homebrew because the `git clone` takes longer than 30 seconds and something in their network is killing the request.

There is definitely something not right on the user's end (I blame proxies and bad routers) but we may have to consider allowing workarounds - such as supporting SSH clones (since it will dodge some proxies).

**Comment by carlocab** [comment]
More of these have been popping up recently than before, though. It's possible that the announcement of Homebrew 3.0 just increased the adoption rate, which explains the greater incidence of errors.

However, it may also be the case that something else changed (almost certainly not in Homebrew) that's causing more of these errors for more users.

**Comment by MikeMcQuaid** [comment]
> There is definitely something not right on the user's end (I blame proxies and bad routers) but we may have to consider allowing workarounds - such as supporting SSH clones (since it will dodge some proxies).

Unless they are enforced consistently everywhere (i.e. every time you `brew tap`) it's not going to fix anything. If users have proxy issues connecting to GitHub: I don't think that's on us to fix.

**Comment by Bo98** [comment]
It's more the case that HTTP requests are treated quite differently than a SSH tunnel. But yes, I get the point of fix responsibility.

The problem with it all is reproducibility. There are many reports of install failures but very little information to work on. I simply don't know why some people are simply unable to keep long running requests to GitHub without it being terminated.

**Comment by sjackman** [comment]
Anecdotal, but I'm experience more dropped HTTPS connections to the Akamai CDN of Bintray. `brew install brewsci/bio/ntjoin` in a clean Linux container fetches 54 bottles, and the transfer of 3 of 54 (~6%) bottles was interrupted by a dropped HTTPS connection. Homebrew responds by downloading the source tarball and installing that (I think only for developers though). Perhaps it should try resuming the bottle download once or twice first.

**Comment by XuehaiPan** [comment]
I think the bottleneck of Homebrew installation is the `git fetch` operation of the `homebrew-core` repository, not `brew` repository itself. But for normal users, they do not care about the version history of fomula manifests. They just want to use the latest ones.

[conda](https://github.com/conda/conda) and [choco](https://github.com/chocolatey/choco) do not store the manifest files (`homebrew-core` for `brew`) locally. Every time users perform a search or update operation, the latest **metadata** will be downloaded from the server. For conda, it is `repodata.json`, which contains all available package names with version numbers. For package installation and uninstallation, the manager download and execute **only the corresponding manifests** from the source channel. But this requires users to give package names they want as much as possible in one time during installation to reduce the number of requests for metadata. It could be slow to download the metadata too often. And `conda` and `choco` do not support `edit` command like `brew edit`.

The Windows Package Manager from Microsoft, aka `winget`, splits the client ([winget-cli](https://github.com/microsoft/winget-cli)) and the manifests ([winget-pkg](https://github.com/microsoft/winget-pkg)) into two repos, just like homebrew does. `winget` requsets metadata of manifests instead of storing all files locally like `conda` and `choco` do. But `winget` exposes all manifests to users, while `conda` and `choco` do not. And [winget-pkg](https://github.com/microsoft/winget-pkg) is a community driven repo too. I think the size of [winget-pkg](https://github.com/microsoft/winget-pkg) repo will grow over time in the future. Currently, `winget` supports *search*, *show* and *install* packages. Soon they will have *uninstall*, *list* and *update*.

If we make `brew` to store only the metadata rather than all manifests, it can reduce much time of Homebrew installation process. But that requires a lot of refactorization work. And it can be slow for daliy use because of the downloading time of metadata. In order to reduce the one-time installation time, but make daily use more cumbersome, I think the gain is not worth the loss.

**Comment by sjackman** [comment]
https://formulae.brew.sh/api/formula.json

Homebrew has this JSON formatted manifest of the available formula. It's 10 MB uncompressed, 1.80 MB GZIP compressed, and 1.35 MB BZIP2 compressed, and it downloads in about seven seconds on my Internet connection. Just today the Homebrew maintainers discussed the possibility of Homebrew/brew using this JSON manifest rather cloning Homebrew/homebrew-core. @alebcay is interested in exploring this option more.

**Comment by XuehaiPan** [comment]
> https://formulae.brew.sh/docs/api/
> https://formulae.brew.sh/api/formula.json
> 
> Homebrew has this JSON formatted manifest of the available formula. It's 10 MB uncompressed, 1.80 MB GZIP compressed, and 1.35 MB BZIP2 compressed.

It seams like a combination of all JSON formatted manifest of formulae's `*.rb` manifest convertion. The size of the metadata (`9.6MB`) is similar to a shallow clone (`6.7MB`). For me, the shallow clone operation takes `10.74s` and the downloading time of `formula.json` is `9.45s`.

```console
$ git clone --depth 1 https://github.com/Homebrew/homebrew-core.git
Cloning into 'homebrew-core'...
remote: Enumerating objects: 5754, done.
remote: Counting objects: 100% (5754/5754), done.
remote: Compressing objects: 100% (5513/5513), done.
remote: Total 5754 (delta 54), reused 373 (delta 17), pack-reused 0
Receiving objects: 100% (5754/5754), 5.24 MiB | 1.22 MiB/s, done.
Resolving deltas: 100% (54/54), done.

$ wget https://formulae.brew.sh/api/formula.json
--2021-02-27 14:39:53--  https://formulae.brew.sh/api/formula.json
Connecting to 127.0.0.1:7890... connected.
Proxy request sent, awaiting response... 200 OK
Length: 10060049 (9.6M) [application/json]
Saving to: ‘formula.json’

formula.json                    100%[=======================================================>]   9.59M  1.54MB/s    in 8.3s

2021-02-27 14:40:02 (1.15 MB/s) - ‘formula.json’ saved [10060049/10060049]

$ du -d 1 -h homebrew-core
 12K	homebrew-core/cmd
 24K	homebrew-core/style_exceptions
 23M	homebrew-core/Formula
 72K	homebrew-core/.github
 48K	homebrew-core/audit_exceptions
6.7M	homebrew-core/.git
  0B	homebrew-core/Aliases
 30M	homebrew-core

$ ls -lh formula.json
-rw-r--r--  1 PanXuehai  staff   9.6M Feb 27 13:35 formula.json
```

The entire metadata file probabily be redownload, even if there is only one formula has been updated. I am a little bit worried about the working load and bandwith of the server that https://formulae.brew.sh/api/ hosted on.

> Just today the Homebrew maintainers discussed the possibility of Homebrew/brew using this JSON manifest rather cloning Homebrew/homebrew-core.

When this work is done, please provide a sync entry of `https://formulae.brew.sh/api/*.json` for other open source mirrors to synchronize. And add a environment variable `HOMEBREW_API_DOMAIN` like `HOMEBREW_BOTTLE_DOMAIN` does. Thank you!

**Comment by maxim-belkin** [comment]
I'm glad we're considering breaking the Formula directory down into subdirectories -- I remember proposing this some time ago and, IIRC, only @javian liked the idea at that time. This is a more dependable file hierarchy that provides nice benefits, such as browsable Formula directory in the GitHub interface and (as @jonchang showed above) better disk usage.

> I'm surprised (and sad) that using the initial character of the formula name only saved us roughly half the disk space. Does using the first two initial characters somehow magically have a more substantial effect?

Git itself uses two characters for directory names:
```sh
$ cd $(brew --repo)
$ git log -1 --format=%H
3e15503e4ce61424558803b225143308a8ef735d
$ cd .git/objects/3e
$ file 15503e4ce61424558803b225143308a8ef735d
15503e4ce61424558803b225143308a8ef735d: zlib compressed data
```

However, for Homebrew-core using the first two characters of formulae names as directory names results in worse improvements (see the table below) than what @jonchang achieved with one-character directory names:

```sh
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Commits                    |           |                                |
|   * Count                    |   222 k   |                                |
|   * Total size               |  61.2 MiB |                                |
| * Trees                      |           |                                |
|   * Count                    |   678 k   |                                |
|   * Total size               |  3.65 GiB | *                              |
|   * Total tree entries       |   131 M   | **                             |
| * Blobs                      |           |                                |
|   * Count                    |   250 k   |                                |
|   * Total size               |   513 MiB |                                |
| * Annotated tags             |           |                                |
|   * Count                    |     0     |                                |
| * References                 |           |                                |
|   * Count                    |   222 k   | ********                       |
```

As for the best course of action, I think "[What does this mean for you?](https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/#user-content-what-does-this-mean-for-you)" section summarizes it pretty well: we should consider the most relevant modes of operations:

1. developers/maintainers (full clones + full fetches)
2. Homebrew users (blobless clones).
3. CI (shallow clones)

**Comment by MikeMcQuaid** [comment]
> Homebrew has this JSON formatted manifest of the available formula. It's 10 MB uncompressed, 1.80 MB GZIP compressed, and 1.35 MB BZIP2 compressed, and it downloads in about seven seconds on my Internet connection. Just today the Homebrew maintainers discussed the possibility of Homebrew/brew using this JSON manifest rather cloning Homebrew/homebrew-core. @alebcay is interested in exploring this option more.

It's also worth nothing that this data could be trivially reduced in size to be more efficient.

> I am a little bit worried about the working load and bandwidth of the server that https://formulae.brew.sh/api/ hosted on. Because I think [choco](https://github.com/chocolatey/choco) is slow for me on _update_, it downloads the metadata for every individual transaction which is mentioned above. 

This is (currently) hosted by GitHub on S3 with Fastly in front of it. It's incredibly efficient to transfer so the bandwidth requirements are not really a concern.

> The metadata should be cached to avoid downloading too frequently.

Agreed. We can use the `etag` header for this.

**Comment by MikeMcQuaid** [comment]
It's also worth noting here: almost everything that applies here to `homebrew-core` also applies to `homebrew-cask`. It's also (very) slow to clone/fetch for the same reasons.
