### ISSUE TITLE
Clean install fail due to master/main branch change of dependency

### ISSUE THREAD

**Issue by claudiuvintila** [Homebrew/install#525]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

MacOS 11.1
I used the official uninstall script and the install one because I had problems installing and older version of helm.

## What happened (include command output)

It seems /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext is using main git branch instead of master now and can't fetch

<details>
  <summary>Command output</summary>
  <pre>

╰─➤  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"                                                                                                                                                                       ()
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown claudiuvintila:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 50cd83642 Merge pull request #10351 from SeekingMeaning/sig-braces
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext failed!
Failed during: /usr/local/bin/brew update --force --quiet

  </pre>
</details>

## What you expected to happen

Clean install

## Step-by-step reproduction instructions (by running `brew` commands)

I used the official uninstall script and the install one.

**Comment by MikeMcQuaid** [comment]
This is a failure with that tap and should be reported there.

> I used the official uninstall script and the install one.

This won't reproduce without that tap.

**Comment by gromgit** [comment]
@claudiuvintila , try:
```
brew untap kabel/php-ext
brew tap kabel/php-ext
brew update
```

**Comment by claudiuvintila** [comment]
> @claudiuvintila , try:
> 
> ```
> brew untap kabel/php-ext
> brew tap kabel/php-ext
> brew update
> ```

that worked. Thank you!
