### ISSUE TITLE
Path to uname should be hardcoded

### ISSUE THREAD

**Issue by mikepqr** [Homebrew/install#531]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

See https://github.com/Homebrew/discussions/discussions/885.

It looks like the install script is using the first `uname` it finds in PATH. This should be hardcoded to `/usr/bin/uname`, which is guaranteed to be a universal binary that respects `arch` or the "Run in Rosetta" terminal app options.

If the user has already used another installation of brew to install single architecture build of `coreutils`, and added that to their PATH, then they get the behavior below.

## What you were trying to do (and why)

Install Rosetta brew in /usr/local

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

```
$ arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
==> Checking for `sudo` access (which may request your password).
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew
stat: cannot read file system information for '%A': No such file or directory
stat: cannot read file system information for '%A': No such file or directory
stat: cannot read file system information for '%u': No such file or directory
stat: cannot read file system information for '%g': No such file or directory
stat: cannot read file system information for '%u': No such file or directory
stat: cannot read file system information for '%g': No such file or directory
==> The following existing directories will be made writable by user only:
/opt/homebrew/share/zsh
/opt/homebrew/share/zsh/site-functions
==> The following existing directories will have their owner set to mike:
/opt/homebrew/share/zsh
/opt/homebrew/share/zsh/site-functions
==> The following existing directories will have their group set to admin:
/opt/homebrew/share/zsh
/opt/homebrew/share/zsh/site-functions
```

Press RETURN to continue or any other key to abort

  </pre>
</details>

## What you expected to happen

brew installs to /usr/local

## Step-by-step reproduction instructions (by running `brew` commands)

 - Install arm64 brew in /opt/homebrew
 - Install coreutils package and follow optional instructions to add it to your path
 - Run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"` with `arch -x86_64` prefix or in a Rosetta terminal

**Comment by carlocab** [comment]
Would you know if we can expect `uname` on Linux to also be `/usr/bin/uname`?

**Comment by mikepqr** [comment]
Good point. In the current latest docker images Ubuntu and Centos both have /bin/uname and /usr/bin/uname (two copies of the same file), but Debian only has /bin/uname.

**Comment by MikeMcQuaid** [comment]
We can add to https://github.com/Homebrew/install/blob/750f6bd7d9ce63d9b47a5f3930d9408577c1c9ce/install.sh#L41-L57

We'll review a PR for this. Closing for now as it seems to only affect you so far and the PR should be fairly straightforward.
