### ISSUE TITLE
On installation using curl, it get stuck on an error

### ISSUE THREAD

**Issue by prezine** [Homebrew/install#535]
On installation `curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/master/install.sh`

I get this error

HEAD is now at 4d88d1004 Merge pull request #10726 from Bo98/gem-path-no-env
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by MikeMcQuaid** [comment]
You'll need to just retry until this works.
