### ISSUE TITLE
Support for ARM on Linux unclear

### ISSUE THREAD

**Issue by strafe** [Homebrew/install#539]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)
Attempting to install Homebrew following the instructions on brew.sh.
1. >[Instructions for a supported install of Homebrew on Linux are on the homepage.](https://docs.brew.sh/Homebrew-on-Linux#install)
1. >[Install Homebrew](https://brew.sh)

```bash
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

## What happened (include command output)
```bash
==> Checking for `sudo` access (which may request your password).
Homebrew on Linux is only supported on Intel processors!
```
## What you expected to happen
[Homebrew to be installed](https://docs.brew.sh/Homebrew-on-Linux#arm):
> Homebrew can run on 32-bit ARM (Raspberry Pi and others) and 64-bit ARM (AArch64), but no binary packages (bottles) are available. Support for ARM is on a best-effort basis. Pull requests are welcome to improve the experience on ARM platforms.
>
> You may need to install your own Ruby using your system package manager, a PPA, or rbenv/ruby-build as we no longer distribute a Homebrew Portable Ruby for ARM.

## Step-by-step reproduction instructions (by running `brew` commands)
1. Attempt to install Homebrew on an ARM Linux machine.

---
This is confusing because the documentation states that Homebrew _can_ run on ARM but the installer will not allow you to install it in the first place. A warning/prompt about the issues on ARM would be preferable to a hard block. https://github.com/Homebrew/install/issues/363#issuecomment-735768294 states that Homebrew on ARM Linux is not supported at all. Would be great to get clarification on this and have everyone's views comments line up on what the actual situation is.

**Comment by MikeMcQuaid** [comment]
> This is confusing because the documentation states that Homebrew _can_ run on ARM but the installer will not allow you to install it in the first place.

Yes. It can be run but is not supported. This also applies for older macOS versions too.

**Comment by carlocab** [comment]
Homebrew on Linux requires an Intel processor. This is in the [documentation](https://docs.brew.sh/Homebrew-on-Linux#requirements).

The documentation that says Homebrew can run on ARM applies to macOS only.

If you really want to run Hombrew on Linux with an ARM processor, you will need to use the [untar-anywhere](https://docs.brew.sh/Installation#untar-anywhere) install method. This is, however, an unsupported configuration, and you will not be able to install the macOS pre-built binaries.

**Comment by strafe** [comment]
> Yes. It can be run but is not supported. This also applies for older macOS versions too.
Interesting, so Homebrew must be installed using the `Alternative Installation` section below?

@carlocab either you're wrong on the documentation is, the quote I provided lives on the `Homebrew on Linux` page - https://docs.brew.sh/Homebrew-on-Linux#arm

**Comment by carlocab** [comment]
I'm really not sure what to tell you. I've linked you to the list of requirements, which explicitly says you need an Intel processor. The section on ARM is also exactly what I've said. Perhaps you interpret the words there differently: in which case, let me make it clear. What the words there mean is what I said in [this comment](https://github.com/Homebrew/install/issues/539#issuecomment-817180636).

**Comment by strafe** [comment]
I appreciate your recommendation to use untar-anywhere and won't comment further on this but what I'm referring to is you said:
> The documentation that says Homebrew can run on ARM applies to macOS only.

and the website (**on the Homebrew for _Linux_**) page says:
> Homebrew can run on 32-bit ARM (Raspberry Pi and others) and 64-bit ARM (AArch64).

**Comment by carlocab** [comment]
Right -- I mistyped. I meant to say "Homebrew _is supported_ on ARM". Apologies for the confusion.
