### ISSUE TITLE
Use depth 1 when cloning home brew

### ISSUE THREAD

**Issue by Altiano** [Homebrew/install#541]
https://github.com/Homebrew/install/blob/a1d820fc8950312c35073700d0ea88a531bc5950/install.sh#L43

`Tapping homebrew/core`

seems to download the entire git histories,

Which is about 300 MB ?

Probably should use git clone depth 1 ?

**Comment by MikeMcQuaid** [comment]
GitHub have asked us not to do this. It makes the initial clone faster but further fetches much slower.
