### ISSUE TITLE
Wrong file permissions for zsh completion directory /usr/local/share/zsh/site-functions

### ISSUE THREAD

**Issue by tangestani** [Homebrew/install#549]
The install script creates the `/usr/local/share/zsh` and `/usr/local/share/zsh/site-functions` directories with the wrong permission the first time it is executed. They are created as group writable, which prevents the completion scripts in those directories from being used.

Running the install script for a second time will fix the permissions.

I suspect that the command that creates the directories and the ones that ensure their correct permissions are not in the correct order.

The issue can be verified using compaudit on a fresh installation:
```
autoload -Uz compaudit
compaudit
```

**Comment by MikeMcQuaid** [comment]
What permissions are you seeing before and after (`ls -l` output, please) and what are you expecting? Thanks!

> I suspect that the command that creates the directories and the ones that ensure their correct permissions are not in the correct order.

Would you be able to submit a pull request for this?

**Comment by tangestani** [comment]
Here's the output of `ls -al` after running `install.sh` for the first time:
```
/usr/local/share/zsh ❯❯❯ ls -al
total 0
drwxrwxr-x  3 mo  admin   96 23 Jun 18:29 .
drwxrwxr-x  6 mo  admin  192 23 Jun 18:35 ..
drwxrwxr-x  3 mo  admin   96 23 Jun 18:35 site-functions
```
Notice that the `share/zsh` and `share/zsh/site-functions` directories have group write permissions.

Here's the output after the second time:
```
/usr/local/share/zsh ❯❯❯ ls -al
total 0
drwxr-xr-x  3 mo  admin   96 23 Jun 18:29 .
drwxrwxr-x  6 mo  admin  192 23 Jun 18:35 ..
drwxr-xr-x  3 mo  admin   96 23 Jun 18:35 site-functions
```
The issue is fixed by running the script a second time.

The code in `install.sh` clearly tried to ensure that the directories had the correct permission, but it doesn't work properly the first time around for some reason:
```
# zsh refuses to read from these directories if group writable
directories=(share/zsh share/zsh/site-functions)
zsh_dirs=()
for dir in "${directories[@]}"; do
  zsh_dirs+=("${HOMEBREW_PREFIX}/${dir}")
done
```

> Would you be able to submit a pull request for this?

I'll give it a shot.

**Comment by tangestani** [comment]
Here's the output of `ls -al` after running `install.sh` for the first time:
```
/usr/local/share/zsh ❯❯❯ ls -al
total 0
drwxrwxr-x  3 mo  admin   96 23 Jun 18:29 .
drwxrwxr-x  6 mo  admin  192 23 Jun 18:35 ..
drwxrwxr-x  3 mo  admin   96 23 Jun 18:35 site-functions
```
Notice that the `share/zsh` and `share/zsh/site-functions` directories have group write permissions.

Here's the output after the second time:
```
/usr/local/share/zsh ❯❯❯ ls -al
total 0
drwxr-xr-x  3 mo  admin   96 23 Jun 18:29 .
drwxrwxr-x  6 mo  admin  192 23 Jun 18:35 ..
drwxr-xr-x  3 mo  admin   96 23 Jun 18:35 site-functions
```
The issue is fixed by running the script a second time.

The code in `install.sh` clearly tried to ensure that the directories had the correct permission, but it doesn't work properly the first time around for some reason:
```
# zsh refuses to read from these directories if group writable
directories=(share/zsh share/zsh/site-functions)
zsh_dirs=()
for dir in "${directories[@]}"; do
  zsh_dirs+=("${HOMEBREW_PREFIX}/${dir}")
done
```

> Would you be able to submit a pull request for this?

I'll give it a shot.

**Comment by MikeMcQuaid** [comment]
Thanks for the debugging information!

> > Would you be able to submit a pull request for this?
> 
> I'll give it a shot.

That'd be great, shout if you need any help!
