### ISSUE TITLE
Command Line Tools always install (even if already installed)

### ISSUE THREAD

**Issue by viking1304** [Homebrew/install#552]
## What you were trying to do (and why)

Everything works, but installer needs improvement.

## What happened (include command output)

Even Command Line Tools were already installed on system unnecessary installation occurred.

<details>
  <summary>Command output</summary>
  <pre>

Downloading Command Line Tools for Xcode
Downloaded Command Line Tools for Xcode
Installing Command Line Tools for Xcode
Done with Command Line Tools for Xcode
Done.

  </pre>
</details>

## What you expected to happen

Installer should check if Command Line Tools or Xcode are already installed, and skip new (re)installation.

## Step-by-step reproduction instructions (by running `brew` commands)

Brew works fine.

**Comment by carlocab** [comment]
Some formulae (e.g. `python@3.x`, `llvm`, `gcc`) have bottles that require a CLT installation (i.e. an Xcode installation is not sufficient), so I think it's perfectly fine for the installer to install the CLT by default so that `brew install` always just works.

If you don't want to install the CLT, you can use one of the [other installation methods](https://docs.brew.sh/Installation).

**Comment by viking1304** [comment]
> Some formulae (e.g. `python@3.x`, `llvm`, `gcc`) have bottles that require a CLT installation (i.e. an Xcode installation is not sufficient), so I think it's perfectly fine for the installer to install the CLT by default so that `brew install` always just works.

I absolutely agree with your point, but even if you already have CLT 12.5 on your system, this will still occur:

<pre>
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> Installing Command Line Tools for Xcode-12.5
==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ for\ Xcode-12.5
</pre>

If /Library/Developer/CommandLineTools/usr/bin exists CLT probably should not be installed again.
