### ISSUE TITLE
Idempotent setup instructions

### ISSUE THREAD

**Issue by carlocab** [Homebrew/install#559]
On Linux and ARM macOS, we ask users to run some variation of these commands:
```
echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> ~/.zprofile
eval $(/opt/homebrew/bin/brew shellenv)
```
These commands provide no feedback, so it becomes tempting for users to run them more than once (cf. Homebrew/discussions#1871). This is not ideal because the first command is not idempotent.

I suggest we find a way to make adding `brew` to a user's `PATH` 1) idempotent, and 2) provide feedback that this has been completed successfully.

Achieving both of these things might require adding a new command to `brew`, but it would be nicer if we could get this done with just the install script.

If we don't want to add a new command, we may want to consider tweaking our post-installation instructions to be a bit more handhold-y for users who are less comfortable with working in the terminal. (We'll probably have to give up idempotence, but we can maybe live without it.)

**Comment by gromgit** [comment]
Getting it done in the install script shouldn't be too difficult, and I'd be happy to take a crack at it, but perhaps we should first revisit the reason why this was _not_ automated in the first place.

And I have no idea what that reason is. :man_shrugging:

**Comment by carlocab** [comment]
I really don't want to automate the first line:

The different ways you can configure your startup scripts are manifold: maybe you use `.{z,bash_}profile`, `.{z,ba}shrc`, or maybe even `.zshenv` (but hopefully not). The structure of these scripts can vary too, and it's too hard to modify them in a way that respects that structure.

I also just remembered the following: we don't write outside `HOMEBREW_PREFIX`, and I think it's good to keep things that way. Writing to a user's shell profile has security implications I'd rather not explore. This is, I think, a strike against my idea to add an extra command that does this.

**Comment by gromgit** [comment]
I understand your concerns, and here's my POV:

1. We're already telling the user where to write that line, so if that happens to be the wrong place, that needs to be fixed regardless.
2. Asking the user to manually run the multiple commands needed to check-then-apply-then-check-again is probably even harder to fool-proof than the current instructions.
3. The install script is already writing outside `HOMEBREW_PREFIX` in a manner of speaking: `HOMEBREW_CACHE` is automatically created under the install user's home directory.

So here's what I'm proposing the install script should do:
1. Search each shell's set of _interactive login_ startup files for `brew shellenv`.
2. If not found anywhere, auto-append line 1 to the first one that exists (default: `~/.profile`), check that it was written correctly, and report to user what was done.
3. If found, report to user where it was found, and noting that no change was made.

For uninitiated CLI users, that should maximize the chance of It Just Works. For the experienced, they're given enough information to tweak after the fact if needed.

**Comment by XuehaiPan** [comment]
I think we can learn from the setup method of `conda`:

```bash
$ conda init -h 
usage: conda init [-h] [--all] [--reverse] [--json] [-v] [-q] [-d] [shells [shells ...]]

Initialize conda for shell interaction. [Experimental]

Options:

positional arguments:
  shells         One or more shells to be initialized. If not given, the default value is 'bash' on unix and 'cmd.exe' on
                 Windows. Use the '--all' flag to initialize all shells. Currently compatible shells are {bash, fish,
                 powershell, tcsh, xonsh, zsh}

optional arguments:
  -h, --help     Show this help message and exit.
  --all          Initialize all currently available shells.
  -d, --dry-run  Only display what would have been done.

setup type:
  --reverse      Undo past effects of conda init.

Output, Prompt, and Flow Control Options:
  --json         Report all output as json. Suitable for using conda programmatically.
  -v, --verbose  Use once for info, twice for debug, three times for trace.
  -q, --quiet    Do not display progress bar.

Key parts of conda's functionality require that it interact directly with the shell
within which conda is being invoked. The `conda activate` and `conda deactivate` commands
specifically are shell-level commands. That is, they affect the state (e.g. environment
variables) of the shell context being interacted with. Other core commands, like
`conda create` and `conda install`, also necessarily interact with the shell environment.
They're therefore implemented in ways specific to each shell. Each shell must be configured
to make use of them.

This command makes changes to your system that are specific and customized for each shell.
To see the specific files and locations on your system that will be affected before, use the
'--dry-run' flag.  To see the exact changes that are being or will be made to each location,
use the '--verbose' flag.

IMPORTANT: After running `conda init`, most shells will need to be closed and restarted
           for changes to take effect.

$ conda init
no change     /home/PanXuehai/Miniconda3/condabin/conda
no change     /home/PanXuehai/Miniconda3/bin/conda
no change     /home/PanXuehai/Miniconda3/bin/conda-env
no change     /home/PanXuehai/Miniconda3/bin/activate
no change     /home/PanXuehai/Miniconda3/bin/deactivate
no change     /home/PanXuehai/Miniconda3/etc/profile.d/conda.sh
no change     /home/PanXuehai/Miniconda3/etc/fish/conf.d/conda.fish
no change     /home/PanXuehai/Miniconda3/shell/condabin/Conda.psm1
no change     /home/PanXuehai/Miniconda3/shell/condabin/conda-hook.ps1
no change     /home/PanXuehai/Miniconda3/lib/python3.8/site-packages/xontrib/conda.xsh
no change     /home/PanXuehai/Miniconda3/etc/profile.d/conda.csh
modified      /home/PanXuehai/.bashrc

==> For changes to take effect, close and re-open your current shell. <==
```

We can provide a command (e.g. `brew init [shell]`) in brew for the users. And the installer script just prompts that:

> ==> Next steps:
> Run the following command to add Homebrew to your PATH:
>         ~/.linuxbrew/bin/brew init

I think this is more clear for users and the `brew init` command can check the dotfiles and avoid duplicate initialization.

**Comment by MikeMcQuaid** [comment]
> I really don't want to automate the first line:

Agreed and other commenters online seem to.

> I suggest we find a way to make adding `brew` to a user's `PATH` 1) idempotent, and 2) provide feedback that this has been completed successfully.

Simple solution: don't add it to their `PATH` if their `PATH` already contains it.
