### ISSUE TITLE
Installer should provide option for just re-freshing the git files

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/install#56]
I ran into an issue where ````$ brew update```` claimed to be done but it was not actually updating to the latest formulae for some reason and I wasn't smart enough to debug the real issue (either brew or git issue).

Doing a ````$ git reset --hard HEAD```` was also not fixing things - formulae were still not getting updated when doing ````$ brew update````

I looked into running the brew uninstaller script but it *un-helpfully* offered to delete everything including all of my Cellar installs when all I was looking for was a way to force a clean brew re-install.

In the end I had to ````$ rm -rf /usr/local/bin/.git```` and then run the homebrew installer which got things working fine again.

Suggestion/enhancement - the installer and/or uninstaller scripts should make it possible to achieve this kind of fix/reset of the homebrew git project files without deleting all of the user's installed packages.

**Comment by MikeMcQuaid** [comment]
We'd review a PR to fix this up but no-one will be working on this right now. Good idea, though.
