### ISSUE TITLE
Homebrew on Linux is only supported on Intel processors!

### ISSUE THREAD

**Issue by JCzz** [Homebrew/install#560]
Unable to install Homebrew on Linux running arm64

https://docs.brew.sh/Homebrew-on-Linux#arm

"
Homebrew can run on 32-bit ARM (Raspberry Pi and others) and 64-bit ARM (AArch64), but no binary packages (bottles) are available.
"

But when running:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

I get:
 `  Homebrew on Linux is only supported on Intel processors!`

**Comment by carlocab** [comment]
Our install script works only on platforms we provide binary packages for. It is not designed to work everywhere that Homebrew can run on.

If you wish to install Homebrew anyway, please see: https://docs.brew.sh/Installation
