### ISSUE TITLE
Brew Install Leads to Error with Finding Remote Ref

### ISSUE THREAD

**Issue by purplepotatodonkey** [Homebrew/install#562]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [Y] your problem was from running the official `install` or `uninstall` script?
- [Y] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

<I was trying to uninstall then reinstall homebrew to update my version of git. I ran into an error message I didn't know how to resolve at the time, but I found a command to resolve it that I want to share. This is my first time doing something like this so I wanted to share!>

## What happened (include command output)

<I got this error message.
fatal: Couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/simple2d/homebrew-tap failed!
Failed during: /usr/local/bin/brew update --force --quiet

I tried all sorts of commands to fix this. The one that ended up working was
brew untap simple2d/homebrew-tap && brew tap simple2d/homebrew-tap

For other errors that are similar, I think this will work as long as the simple2d/homebrew-tap is replaced with whatever the last two steps in the path are in the error message.
>

<details>
  <summary>Command output</summary>
  <pre>

  <==> Checking for `sudo` access (which may request your password).
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Caskroom

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /bin/chmod u=rwx,g=rwx /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/sbin/chown josephwang /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/sbin/chown -R josephwang:admin /usr/local/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /Users/josephwang/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/josephwang/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown -R josephwang /Users/josephwang/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 5ec335188 Merge pull request #11754 from Rylan12/update-preinstall-check
fatal: Couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/simple2d/homebrew-tap failed!
Failed during: /usr/local/bin/brew update --force --quiet>

  </pre>
</details>

## What you expected to happen

<I got this error message.
fatal: Couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/simple2d/homebrew-tap failed!
Failed during: /usr/local/bin/brew update --force --quiet

I tried all sorts of commands to fix this. The one that ended up working was
brew untap simple2d/homebrew-tap && brew tap simple2d/homebrew-tap

For other errors that are similar, I think this will work as long as the simple2d/homebrew-tap is replaced with whatever the last two steps in the path are in the error message.>

## Step-by-step reproduction instructions (by running `brew` commands)

</bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)">

**Comment by MikeMcQuaid** [comment]
> For other errors that are similar, I think this will work as long as the simple2d/homebrew-tap is replaced with whatever the last two steps in the path are in the error message.

Report this to that tap, our installer won't use it.

**Comment by purplepotatodonkey** [comment]
Hi! This so cool interacting with someone in the industry! I read through some of the github files like the contribution guide but I'm still not sure how to specifically report this to tap. If you're not busy, could you guide me to the instructions? Thank you for this amazing software btw!

**Comment by MikeMcQuaid** [comment]
https://github.com/simple2d/homebrew-tap is the relevant URL.
