### ISSUE TITLE
Unable to install HomeBrew on my Mac

### ISSUE THREAD

**Issue by HuseyinAA** [Homebrew/install#563]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
- When running brew doctor:
`Error: No available tap homebrew/core.`

- When I run brew config:
`HOMEBREW_VERSION: 3.2.5-19-gbdc3391
ORIGIN: https://github.com/Homebrew/brew
HEAD: bdc3391a1319f1c40a108d14a077ca0964b33a3f
Last commit: 20 hours ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: 12.5.1`
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

When I tried installing HomeBrew on my Mac after a factory reset I have been getting this issue. When I run the install command listed on the HomeBrew page `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` it installs some of the content but fails at some point. It managed to install the Xcode tools but fails after- see below for more information. I have searched online for a solution but unfortunately, it seems that HomeBrew has not been fully installed on my mac as I am unable to use brew doctor as the error message I get is `Error: No available tap homebrew/core.`. The reason for installing brew is for upgrading my git on my mac. The problem seems to be the homebrew/core.  I did try one solution that tries installing only the tap homebrew/core but that fails too.

### What happened (include all command output)?

The install fails at a certain point. At first, it installed the basic things relating to Xcode. But it failed after that and I even tried running --force on it.  

- So when I run: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` with force aswell
I get:
`Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown -R mydetails:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at bdc3391a1 Merge pull request Homebrew/linuxbrew-core#11793 from Homebrew/revert-11781-remove_homebrew_bottle_domain
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: 4070 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
fatal: invalid upstream 'origin/master'
Failed during: /usr/local/bin/brew update --force --quiet`
![Screenshot 2021-07-30 at 18 19 11](https://user-images.githubusercontent.com/51432818/127689132-002c87ec-7c97-4a13-92b9-32515b548b9d.png)

### What did you expect to happen?

I expected brew to install properly. But it failed and bear in mind that my Mac was recently factory reset so there have been no configurations or anything to my mac that could affect the install process.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
What I did:

1) Running brew install command `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

2) Fails to install

3) Tried finding more information online, tried brew update-reset, brew update, and some of the solutions which I mention above.
```

**Comment by SMillerDev** [comment]
See https://github.com/Homebrew/discussions/discussions/666 it probably has a solution

**Comment by MikeMcQuaid** [comment]
Will need to figure this out yourself, it's specific to your machine, sorry.

**Comment by ThadHouse** [comment]
I'm having this same issue. I don't think its limited to just a single machine.

**Comment by SMillerDev** [comment]
You work for a very rich company. I'm sure they can spare some resources to help you figure out why a connection to one of their own tools isn't working correctly.
