### ISSUE TITLE
Feature Request: choose install location

### ISSUE THREAD

**Issue by maxim-belkin** [Homebrew/install#57]
I suggest allowing user to choose the location where he or she wishes to install Homebrew. This can be done in the beginning of the install script with a simple prompt for the path. The install script would then check if the provided path exists and, if it does not, ask the user if he wants Homebrew to create that directory or specify a different one. This will be useful for users with little to no space left on the main hard drive or those who want to reduce load on / wear of the hard disk.

**Comment by MikeMcQuaid** [comment]
People can pick where to install currently but we don't want to recommend/support it here as the non-default location is not able to use many bottles which increases our support burden.
