### ISSUE TITLE
When using "sudo -v" the install script fails with the error "a terminal is required to read the password"

### ISSUE THREAD

**Issue by acecilia** [Homebrew/install#585]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I am trying to run the installation script without any interaction. I tried:
```
echo "my_pass" | sudo -S -v
echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

## What happened (include command output)

It failed to use the cached sudo password

<details>
  <summary>Command output</summary>
  <pre>
==> Checking for `sudo` access (which may request your password).
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Homebrew
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
  </pre>
</details>

## What you expected to happen

The installation script to successfully run

## Step-by-step reproduction instructions (by running `brew` commands)

I could not reproduce it locally, but I could reproduce it in multiple CI machines. Maybe this is because the CI machines use a non-interactive, non-login shell.

I troubleshooted the issue, and this is what I found. Running this on the CI machines:

```
#!/bin/zsh
echo "my_pass" | sudo -S -v
sudo echo "something1"
/bin/bash -c "/usr/bin/sudo echo something2"
if ! /usr/bin/sudo echo something3;then echo something4;fi
/bin/bash -c "if ! /usr/bin/sudo echo something5;then echo something6;fi"
```

Prints the following:

```
something1
something2
something3
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
something6
```

Seems to be an unexpected behaviour of the `sudo` command, and not so much `brew`.
Workaround: use `SUDO_ASKPASS` instead
OS: `MacOS 11.5.1 (20G80)`

**Comment by MikeMcQuaid** [comment]
> It failed to use the cached sudo password

This is intentional behaviour. 

> Workaround: use `SUDO_ASKPASS` instead

Is this a workaround that you're using successfully? If so: that's what we'd recommend.
