### ISSUE TITLE
Unable to install on MacOS

### ISSUE THREAD

**Issue by richard-scott** [Homebrew/install#590]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)
I attempted to run the install script on a new system.

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

## What happened (include command output)
CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

==> Checking for `sudo` access (which may request your password).
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> /usr/bin/sudo /usr/sbin/chown -R vagrant:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
Updating files: 100% (2714/2714), done.
HEAD is now at b14078a41 Merge pull request #12342 from carlocab/java-bottle-relocation
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
^CFailed during: /usr/local/bin/brew update --force --quiet

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

I was expecting to have brew installed ;-(

## Step-by-step reproduction instructions (by running `brew` commands)

Run the installer:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by MikeMcQuaid** [comment]
This is an issue with your connection to GitHub. You'll need to figure it out yourself.

**Comment by logiota** [comment]
Run:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

then try again

**Comment by richard-scott** [comment]
Hmmm, ok. I'm in the UK, and it appears that my ISP (VirginMedia) has a virus & child safe scanning service that for some reason doesn't like Github. Adding github.com and raw.githubusercontent.com to the whitelist has resolved my issue.
