### ISSUE TITLE
brew install --build-from-source gdb Error, pease help me

### ISSUE THREAD

**Issue by Dopa4** [Homebrew/install#596]
<img width="1301" alt="iShot2021-11-14 20 48 29" src="https://user-images.githubusercontent.com/37179931/141681779-72a4d5a4-86ec-4b94-8d98-cbac9ea5d297.png">

**Comment by carlocab** [comment]
Please [don't use screenshots](https://meta.stackoverflow.com/a/285557) when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse (e.g. when looking up error messages). Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.

GDB does not build on M1.

**Comment by Dopa4** [comment]
your mean is gdb cannot used on M1 ? I just want to&nbsp;confirm，I try many times




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Homebrew/install"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 晚上8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Homebrew/install] brew install --build-from-source gdb Error, pease help me (Issue #596)





 
Please don't use screenshots when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse (e.g. when looking up error messages). Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.
 
GDB does not build on M1.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by carlocab** [comment]
It cannot be used natively on M1. You may be able to use it with a Rosetta installation of Homebrew in `/usr/local`. You will likely only be able to use it to debug x86_64 executables, though.

**Comment by Dopa4** [comment]
no offense but&nbsp;I still want to ask whether the ecology of M1 is being improved. I hope to use M1 as easily as using x86 architecture，
Lack of support at the software level, and the purchase of hardware will also become a concern




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Homebrew/install"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 晚上10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Homebrew/install] brew install --build-from-source gdb Error, pease help me (Issue #596)





 
It cannot be used natively on M1. You may be able to use it with a Rosetta installation of Homebrew in /usr/local. You will likely only be able to use it to debug x86_64 executables, though.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
