### ISSUE TITLE
Documentation or Install script issue about ARM Linux

### ISSUE THREAD

**Issue by xuqingkuang** [Homebrew/install#607]
Hi.

Follow the guide of https://docs.brew.sh/Homebrew-on-Linux#arm seems brew is supported Linux ARM(aarch64).

> Homebrew can run on 32-bit ARM (Raspberry Pi and others) and 64-bit ARM (AArch64), but no binary packages (bottles) are available.

But the install script writes NO - https://github.com/Homebrew/install/blob/master/install.sh#L529

```
$ uname -a
Linux VM-147-26-centos 5.4.32-19-0001 #1 SMP Thu Jul 23 19:08:43 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

$ uname -m
aarch64
```

```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> Select a Homebrew installation directory:
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /home/xqkuang/.linuxbrew
- Press Control-C to cancel installation
Sorry, user xqkuang may not run sudo on VM-147-26-centos.
Homebrew on Linux is only supported on Intel processors!
```

How to figure out what's the problem, is the document or install script have a mistake ?

**Comment by MikeMcQuaid** [comment]
> Follow the guide of https://docs.brew.sh/Homebrew-on-Linux#arm seems brew is supported Linux ARM(aarch64).

It can run but is not supported, so the installer won't install it.

**Comment by kingdonb** [comment]
The message refers to an alternate installation method and links to more information:

```
Homebrew on Linux is not supported on ARM processors.
You can try an alternate installation method instead:
  https://docs.brew.sh/Homebrew-on-Linux#arm
```

but there is not more information there, except to tell you that you will have to install your own Ruby.

Is there any entrypoint to this? I understand this is unsupported and I'm on my own if I have issues, but it seems strange to dangle the carrot like this if we didn't really mean to provide an alternate installation method for users who want to try.
