### ISSUE TITLE
The uninstall script fails if $HOMEBREW_PREFIX/.git doesn’t exist

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/install#61]
I believe this is due to https://github.com/Homebrew/install/commit/7220feb5d667e2173377d9b24c33fc4c858ab27e.

Reported by [someone on Quora](https://www.quora.com/How-does-one-uninstall-Homebrew/answer/Baptiste-Fontaine/comment/22469675):

```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
-e:100:in `realpath': No such file or directory - /usr/local/.git (Errno::ENOENT)
from -e:100:in `realpath'
from -e:100:in `<main>')
```

**Comment by MikeMcQuaid** [comment]
CC @DomT4

**Comment by DomT4** [comment]
Saw Baptiste create the Issue last night but hadn't had the chance to push a fix yet. Thanks for doing so!
