### ISSUE TITLE
Issues Installing Brew Via DotnetCore App

### ISSUE THREAD

**Issue by aaronbergerM** [Homebrew/install#611]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ X] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

We are trying to setup developer environments via a one stop shop dotnet core app. One piece of this is installing homebrew. The install is just being triggered by starting a process that calls '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`. For purposes of what we are trying to do, it is irrelevant if the brew install is interactive or not (the app we deploy requires interactivity at other steps) but we run into an issue trying to do this interactively and non-interactively, which I will detail below.

Disclaimer: There may well be some super obvious solution to running this non-interactively that I'm missing but I haven't found any documentation guiding me to the proper way to do it.

## What happened (include command output)

Issue 1 (installing interactively via this method):
This just doesn't seem to be possible currently. Any attempt to run the install script from within a spawned process from dotnet and allow input redirection triggers the test on line 24 to set NONINTERACTIVE=1 in install.sh.

Issue 2(installing non interactively):
We can get through the bulk of the installation by priming the sudo cache immediately before kicking of the run of install.sh, but the cache doesn't stay primed long enough to handle elevation for the commands towards the end of install.sh.  On a standard workstation machine with a normal user account, I'm not sure how to get around this issue without mucking with sudo timeout params which is non-ideal.

Here's command output from a noninteractive run spawned directly after priming sudo cache
<details>
  <summary>Command output</summary>
  <pre>

==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/usr/local/bin/brew

/usr/local/share/doc/homebrew

/usr/local/share/man/man1/brew.1

/usr/local/share/zsh/site-functions/_brew

/usr/local/etc/bash_completion.d/brew

/usr/local/Homebrew

==> The following existing directories will be made group writable:
/usr/local/bin

/usr/local/share

==> The following existing directories will have their owner set to rsiemens:
/usr/local/bin

/usr/local/share

==> The following existing directories will have their group set to admin:
/usr/local/bin

/usr/local/share

==> The following new directories will be created:
/usr/local/etc

/usr/local/include

/usr/local/lib

/usr/local/sbin

/usr/local/var

/usr/local/opt

/usr/local/var/homebrew

/usr/local/var/homebrew/linked

/usr/local/Cellar

/usr/local/Caskroom

/usr/local/Frameworks

==> The Xcode Command Line Tools will be installed.
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin /usr/local/share

==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/share

==> /usr/bin/sudo /usr/sbin/chown rsiemens /usr/local/bin /usr/local/share

==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/share

==> /usr/bin/sudo /bin/mkdir -p /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Frameworks

==> /usr/bin/sudo /bin/chmod ug=rwx /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Frameworks

==> /usr/bin/sudo /usr/sbin/chown rsiemens /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Frameworks

==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Frameworks

==> /usr/bin/sudo /bin/mkdir -p /usr/local/Homebrew

==> /usr/bin/sudo /usr/sbin/chown -R rsiemens:admin /usr/local/Homebrew

==> /usr/bin/sudo /bin/mkdir -p /Users/rsiemens/Library/Caches/Homebrew

==> /usr/bin/sudo /bin/chmod g+rwx /Users/rsiemens/Library/Caches/Homebrew

==> /usr/bin/sudo /usr/sbin/chown -R rsiemens /Users/rsiemens/Library/Caches/Homebrew

==> Searching online for the Command Line Tools

==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress

==> Installing Command Line Tools for Xcode-13.2

==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ for\ Xcode-13.2

Software Update Tool

Finding available software

Downloading Command Line Tools for Xcode

Downloaded Command Line Tools for Xcode

Installing Command Line Tools for Xcode

Done with Command Line Tools for Xcode

Done.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress

Password:
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools

==> Downloading and installing Homebrew...

HEAD is now at 633202dac Merge pull request #12704 from Homebrew/dependabot/bundler/Library/Homebrew/rainbow-3.1.1

==> Tapping homebrew/core

HEAD is now at aa2f643fd42 chmlib: update 0.40 bottle.

Failed during: /usr/local/bin/brew update --force --quiet

  </pre>
</details>

## What you expected to happen

There are several ways to resolve this on our side without updates to install.sh. Although, it appears install.sh has some pretty frequent updates and ideally would like to just get a fix implemented at the source rather than dealing with it on our end which is susceptible to breaking (which has happened once already and now leads me to creating this issue).

It seems to me the easiest way to solve this would allow some sort of manual override of the test on line 24 of isntall.sh. Perhaps if presence of some specific environment variable that would allow for interactive regardless of  `[ ! -t 0  ]`. Much like CI can be used to force non-interactive behavior, a different env var to force interactive.

But I also am not sure of all the use cases needed to support nor the intricacies of the install script so I'm opening this issue.

## Step-by-step reproduction instructions (by running `brew` commands)

No brew commands needed to repro. I can provide dotnet code if desired, but I don't know if it is beneficial for purposes of this issue.

**Comment by gromgit** [comment]
I suspect it's the CLT download that's pushing the install to sudo credentials timeout, so preloading the CLT package is probably your best bet.

Try implementing the equivalent of https://github.com/Homebrew/install/blob/abe5c4fe830cf6c36d1916b9eaac3ee818c949b8/install.sh#L820-L831 in DotNetCore, but doing a `softwareupdate -d` (download) instead of `softwareupdate -i`. This can be done without sudo privileges (at least, it worked for me when I tried it on Catalina). Then prime the sudo cache, and run the installer as before. It should not trigger credentials timeout this way.

**Comment by MikeMcQuaid** [comment]
Sorry, I can't really understand the issue as described here and @gromgit has provided a workaround so: closing.

**Comment by aaronbergerM** [comment]
This issue can be boiled down simply into the ask. Can a flag be setup to force interactive behavior in install.sh? Just as there is machination to force noninteractive behavior via the CI or NONINTERACTIVE env vars.

**Comment by gromgit** [comment]
If you're talking about your Issue 1, at what points are you expecting your DotNetCore app to interact with the installer?

**Comment by XuehaiPan** [comment]
@aaronbergerM To enforce interactive behavior, you can unset `CI` and `NONINTERACTIVE`:

```bash
sudo -k  # clear sudo password cache
CI='' NONINTERACTIVE='' /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

This will always run in interactive mode and ask for a `sudo` passward.

**Comment by MikeMcQuaid** [comment]
@gromgit @XuehaiPan would love if one of you could add a `--noninteractive` flag.

**Comment by XuehaiPan** [comment]
> @gromgit @XuehaiPan would love if one of you could add a `--noninteractive` flag.

@MikeMcQuaid This is easy to implement, with some small modifications to fecf22b6173e97e2ff6c0a04c3baa32d76fc7ff4. But it is enough for me to use the environment variable `NONINTERACTIVE`. We can either document variable `NONINTERACTIVE` or implement command-line options for the installer. If we introduce new command-line options, what about reconsidering the options in fecf22b6173e97e2ff6c0a04c3baa32d76fc7ff4: `--{brew,core}-git-remote` suppress `HOMEBREW_{BREW,CORE}_GIT_REMOTE`.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid This is easy to implement, with some small modifications to [fecf22b](https://github.com/Homebrew/install/commit/fecf22b6173e97e2ff6c0a04c3baa32d76fc7ff4). But it is enough for me to use the environment variable `NONINTERACTIVE`. We can either document variable `NONINTERACTIVE` or implement command-line options for the installer. If we introduce new command-line options, what about reconsidering the options in [fecf22b](https://github.com/Homebrew/install/commit/fecf22b6173e97e2ff6c0a04c3baa32d76fc7ff4): `--{brew,core}-git-remote` suppress `HOMEBREW_{BREW,CORE}_GIT_REMOTE`.

Yeh, I think it'd be enough to document `NONINTERACTIVE` and add and document a `INTERACTIVE` to force the opposite.

**Comment by carlocab** [comment]
It seems enough for `INTERACTIVE` to do nothing but fail your install inside

https://github.com/Homebrew/install/blob/abe5c4fe830cf6c36d1916b9eaac3ee818c949b8/install.sh#L22-L27

**Comment by MikeMcQuaid** [comment]
@carlocab Sorry, you've lost me a bit there. I'm thinking `INTERACTIVE` could bypass the TTY requirement. Don't know if that'll actually work for receiving input, though, if not: it doesn't make any sense to add.

**Comment by carlocab** [comment]
Hmm, yea, I don't know how the script will receive input if stdin is not a TTY, so I guess this might be better left to someone who has that as a use-case (i.e. wants an interactive install but their stdin is detached from their terminal for some reason).

**Comment by MikeMcQuaid** [comment]
Yeh, that's fair. In that case: just documenting `NONINTERACTIVE` seems like a good idea.

**Comment by aaronbergerM** [comment]
> @carlocab Sorry, you've lost me a bit there. I'm thinking `INTERACTIVE` could bypass the TTY requirement. Don't know if that'll actually work for receiving input, though, if not: it doesn't make any sense to add.

This is exactly what I want as stdin is detached from the terminal as a result of how we are triggering this. My thinking is just that an INTERACTIVE flag would be able to override the [[! -t 0]] tests. It doesn't matter at all to me if its' via an Environment Variable or cli option.


@XuehaiPan 
> When the `stdin` is not a terminal, the installer will set `NONINTERACTIVE` at line 24 (`[[ ! -t 0 ]]`):

This is the issue unfortunately in my use case


@gromgit 
> If you're talking about your Issue 1, at what points are you expecting your DotNetCore app to interact with the installer?

Sorry I should have been more clear in my initial outline of the issue. Essentially, I don't care if the install is interactive or non-interactive. Non-interactive poses a problem due to the sudo cache timeout on our dev machines (i appreciate the workaround suggestion of pre-installing clt). 
Interactive poses a problem because the install script doesn't allow a way to override the [[! -t 0]] check. So regardless of other environment variables, if I'm triggering from a process spawned from dotnet and re-directing stdin for interaction I will get defaulted to non-interactive behavior.

**Comment by aaronbergerM** [comment]
Just saw the latest commits with the Interactive flag added! Thanks a bunch!

**Comment by aaronbergerM** [comment]
Quick report back. I have kicked off the script with INTERACTIVE=1 set and now am potentially running into an issue. Input redirection is working for the first sudo elevation butI  can't seem to get my confirmation of brew install options to re-direct properly. 

I am not fluent in bash and am unsure of what all is going on here but highlighting the pertinent code to see if there's potentially room to address this odd scenario of detached tty.

https://github.com/Homebrew/install/blob/458c3d2834f40cf00992b2fca3f08ad1cdf0bf78/install.sh#L240-L266


Output to where I got stuck.

`Warning: Running in interactive mode despite `stdin` not being a TTY because `$INTERACTIVE` is set.
==> Checking for `sudo` access (which may request your password)...
Password:
Sorry, try again.
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/sbin
/usr/local/opt
/usr/local/var/homebrew/linked
/usr/local/Cellar
/usr/local/Caskroom
/usr/local/Frameworks

Press RETURN to continue or any other key to abort:`

**Comment by MikeMcQuaid** [comment]
@aaronbergerM Sorry but has gone into "you're going to need to figure it out yourself" territory. If you're forcing interactive mode without a TTY: it's pretty understandable that you're going to have issues with reading from stdin.

**Comment by XuehaiPan** [comment]
> Input redirection is working for the first `sudo` elevation but I can't seem to get my confirmation of brew install options to re-direct properly.

Command `stty` requires `stdin` to be a TTY. A tricky solution can be re-direct `stderr` as `stdin`:

```bash
stty cbreak -echo <&2
```

The best approach is to check `[[ -t 0 ]]` again in `getc`.

```bash
getc() {
  if [[ -t 0 ]]
  then
    local save_state
    save_state="$(/bin/stty -g)"
    /bin/stty raw -echo
    IFS='' read -r -n 1 -d '' "$@"
    /bin/stty "${save_state}"
  else
    IFS='' read -r -n 1 -d '' "$@"
  fi
}
```

Alternatively, just comment `wait_for_user` to bypass the confirmation.

Change

https://github.com/Homebrew/install/blob/458c3d2834f40cf00992b2fca3f08ad1cdf0bf78/install.sh#L762-L766

To

```bash
if [[ -z "${NONINTERACTIVE-}" ]]
then
  ring_bell
  # wait_for_user
fi
```

**Comment by aaronbergerM** [comment]
@MikeMcQuaid reasonable enough, the alerting messages around the Interactive flag when not spawned from a TTY might benefit from a tweak given there is dependency on TTY for interactivity later on in the script.

Thanks everyone for your assistance!
