### ISSUE TITLE
Install brew on my mac OS montery m1

### ISSUE THREAD

**Issue by HanyMKhalil** [Homebrew/install#613]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ install] your problem was from running the official `install` or `uninstall` script?
- [-bash: brew: command not found, macOS monterey m1 ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What happened (include command output)

<details>
(base) 192:~ hanykhalil$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R hanykhalil:admin /opt/homebrew
==> Downloading and installing Homebrew...
HEAD is now at 51da118a9 Merge pull request #12789 from Homebrew/revert-12758-cleanup_readable_symlinks
Warning: /opt/homebrew/bin is not in your PATH.
  Instructions on how to configure your shell for Homebrew
  can be found in the 'Next steps' section below.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run these two commands in your terminal to add Homebrew to your PATH:
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/hanykhalil/.bash_profile
    eval "$(/opt/homebrew/bin/brew shellenv)"
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

(base) 192:~ hanykhalil$ brew help
-bash: brew: command not found
(base) 192:~ hanykhalil$ echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/hanykhalil/.bash_profile
-bash: /Users/hanykhalil/.bash_profile: Permission denied
(base) 192:~ hanykhalil$ echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/hanykhalil/.bash_profile
-bash: /Users/hanykhalil/.bash_profile: Permission denied
(base) 192:~ hanykhalil$ 

## Step-by-step reproduction instructions (by running `brew` commands)

(base) 192:~ hanykhalil$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R hanykhalil:admin /opt/homebrew
==> Downloading and installing Homebrew...
HEAD is now at 51da118a9 Merge pull request #12789 from Homebrew/revert-12758-cleanup_readable_symlinks
Warning: /opt/homebrew/bin is not in your PATH.
  Instructions on how to configure your shell for Homebrew
  can be found in the 'Next steps' section below.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run these two commands in your terminal to add Homebrew to your PATH:
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/hanykhalil/.bash_profile
    eval "$(/opt/homebrew/bin/brew shellenv)"
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

(base) 192:~ hanykhalil$ brew help
-bash: brew: command not found
(base) 192:~ hanykhalil$ echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/hanykhalil/.bash_profile
-bash: /Users/hanykhalil/.bash_profile: Permission denied
(base) 192:~ hanykhalil$ echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/hanykhalil/.bash_profile
-bash: /Users/hanykhalil/.bash_profile: Permission denied
(base) 192:~ hanykhalil$

**Comment by gromgit** [comment]
You forgot the second command:
```
eval "$(/opt/homebrew/bin/brew shellenv)"
```
Run that in your current shell, and you should be able to `brew ...` in that shell. The first commands adds the same thing to your shell's login startup file, so that it applies to _all_ your shells, but only after you log in again.

However...
>```
>-bash: /Users/hanykhalil/.bash_profile: Permission denied
>```

that's not right at all. What's the output of `ls -l /Users/hanykhalil/.bash_profile`?

**Comment by HanyMKhalil** [comment]
after i used the first line
eval "$(/opt/homebrew/bin/brew shellenv)"
 i think it works

for the second command i typed

(base) hanys-mbp:~ hanykhalil$ ls -l /Users/hanykhalil/.bash_profile
-rw-r--r--  1 root  staff  447 Jan 25  2021 /Users/hanykhalil/.bash_profile

**Comment by HanyMKhalil** [comment]
but then every time i need to brew i have to fisrt run the line
eval "$(/opt/homebrew/bin/brew shellenv)"

**Comment by carlocab** [comment]
What is the output of `whoami` and `echo $HOME`?

**Comment by gromgit** [comment]
>```
>hanykhalil$ ls -l /Users/hanykhalil/.bash_profile
>-rw-r--r-- 1 root staff 447 Jan 25 2021 /Users/hanykhalil/.bash_profile
>```

That's _definitely_ not right. Users' files should be owned by themselves, not root. `chown $(whoami): ~/.bash_profile` should fix that up.

**Comment by carlocab** [comment]
Probably needs `sudo`, since it's owned by `root`.

**Comment by gromgit** [comment]
> Probably needs `sudo`, since it's owned by `root`.

Whoopsie. I blame post-prandial stupor. :laughing:

**Comment by HanyMKhalil** [comment]
i did that and after i typed

brew config

i got:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) hanys-mbp:~ hanykhalil$ brew config
HOMEBREW_VERSION: 3.3.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 768b172393339b4654107dc6a840a2cd08dc64b9
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4c4ac53b27cfb2517b4982d8cc8b96ab44f527ca
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.55Q3v5SlHb/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false
(base) hanys-mbp:~ hanykhalil$

**Comment by HanyMKhalil** [comment]
guys can i ask something else? regarding installation of h5py on my mac? after sucessfuly install brew now i use it to download my numerical code i need to install h5py which is part of python environment the developer gave these lines to do it:

# Install dependencies
pip3 install numpy cython pkgconfig mpi4py
HDF5_DIR=/opt/homebrew/Cellar/hdf/1.12.1 pip3 install h5py --no-build-isolation --no-binary :all:

but also gave me error saying 

ERROR: Failed building wheel for h5py
Failed to build underworld h5py
ERROR: Could not build wheels for underworld, h5py, which is required to install pyproject.toml-based projects

**Comment by carlocab** [comment]
Looks like you're all set with `brew`. I can't help you with the `pip3` install failure, however. You might be better off asking the `h5py` project.

One thing I will mention is that you'll want to avoid `Cellar` paths when referencing formulae: these can change without notice. For a stable path, you should use
```sh
HDF5_DIR=/opt/homebrew/opt/hdf5
```

**Comment by HanyMKhalil** [comment]
sure thanks alot so much
