### ISSUE TITLE
brew install stuck for hours

### ISSUE THREAD

**Issue by kavyabhargava** [Homebrew/install#620]
My brew install stuck at "/usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress" I kept laptop on for almost a day but its not moving forward

This script will install:

/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The Xcode Command Line Tools will be installed.

Press RETURN to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R alpanabhargava:admin /usr/local/Homebrew
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress

"Stuck here"

**Comment by MikeMcQuaid** [comment]
It's trying to install the CLT. Either wait or do so manually yourself.
