### ISSUE TITLE
Unable to install inside Docker container on macOS

### ISSUE THREAD

**Issue by ky1vstar** [Homebrew/install#621]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I was trying to install Homebrew inside Docker container running on macOS host.

## What happened (include command output)

Install script aborts with message `Don't run this as root!`.

<details>
  <summary>Command output</summary>
  <pre>
    macOS 11.5.2, Docker Desktop 4.5.0 (74594)
    $ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    Warning: Running in non-interactive mode because `$CI` is set.
    ==> Checking for `sudo` access (which may request your password)...
    Don't run this as root!
  </pre>
</details>

## What you expected to happen

Homebrew is successfully installed.

## Step-by-step reproduction instructions (by running `brew` commands)

Install latest Docker Desktop for macOS, try installing Homebrew inside container.
This error happend due to `grep -E "azpl_job|actions_job|docker|garden|kubepods" -q /proc/1/cgroup` line inside install script. Seems like latest version of Docker uses cgroups v2.
```
# cat /proc/1/cgroup
0::/
```
This is expected behaviour, according to the [cgroups-v2 documentation](https://www.kernel.org/doc/Documentation/cgroup-v2.txt):
>If legacy cgroup is in use in the system, this file may contain multiple lines, one for each hierarchy. The entry for cgroup v2 is always in the format "0::$PATH"

**Comment by MikeMcQuaid** [comment]
@ky1vstar Could you submit a pull request to update this `grep` line? Thanks!

**Comment by koumuking** [comment]
macOS Monterrey 12.3
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
curl: (35) error:02FFF036:system library:func(4095):Connection reset by peer

**Comment by EricFromCanada** [comment]
The primary suggested fix for detecting being in a Docker container using cgroups v2 is to [check for `/.dockerenv`](https://groups.google.com/g/linux.debian.maint.boot/c/Z5FUwTeZ4ok), but this [isn't always reliable](https://github.com/GoogleContainerTools/kaniko/issues/1592#issuecomment-861254141).

**Comment by SirNova01** [comment]
facing thesame issue too, I'm on a macOs Monterey

[ -f /.dockerenv ] || grep -Eq '(lxc|docker)' /proc/1/cgroup
this line outputs:
grep: /proc/1/cgroup: No such file or directory

**Comment by mictram** [comment]
Same issue here running Docker on MacOS and Linux when trying to install brew to debian-11:slim.
