### ISSUE TITLE
Problem with reinstalation

### ISSUE THREAD

**Issue by g1b3r** [Homebrew/install#622]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ yes] your problem was from running the official `install` or `uninstall` script? 
install
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue? not able to run 

## What you were trying to do (and why)
Just install brew
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

## What happened (include command output)

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R User:admin /usr/local/Homebrew

==> Downloading and installing Homebrew...
Updating files: 100% (2743/2743), done.
HEAD is now at d2857e0dd Merge pull request #12964 from danielnachun/new_binary_grep
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:0cb1cc7af109437fe0e020c9f3b7b95c3c709b140bde9f991ad2c1433496dd42
Already downloaded: /Users/User/Library/Caches/Homebrew/portable-ruby-2.6.8.yosemite.bottle.tar.gz
Error: Checksum mismatch.
Expected: 0cb1cc7af109437fe0e020c9f3b7b95c3c709b140bde9f991ad2c1433496dd42
  Actual: 0ca33597e9f7fd662e21c8da6fe72735c4c23441ee9ba6cd554263b0a9b0a364
 Archive: /Users/User/Library/Caches/Homebrew/portable-ruby-2.6.8.yosemite.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!
Failed during: /usr/local/bin/brew update --force --quiet

## What you expected to happen
Install brew 

## Step-by-step reproduction instructions (by running `brew` commands)

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by carlocab** [comment]
Do
```
rm /Users/User/Library/Caches/Homebrew/portable-ruby-2.6.8.yosemite.bottle.tar.gz
```
and try again.

**Comment by g1b3r** [comment]
I trying and this is not working

czw., 10 mar 2022 o 13:58 Carlo Cabrera ***@***.***>
napisał(a):

**Comment by carlocab** [comment]
Then there is likely a problem with your Internet connection. That's not something I can help you with, I'm afraid.

**Comment by g1b3r** [comment]
Its not related to my internet connection , because when i remove this file its downloaded again lots people have similiar issue. Its rather problem with portable ruby and different checksum. Please investigate and fix

**Comment by MikeMcQuaid** [comment]
Don't open the same issue in multiple places when it's already been closed or you will be blocked.

**Comment by g1b3r** [comment]
but this is still a issue so you are not willing to help with this issue ? :(

**Comment by MikeMcQuaid** [comment]
We are not able to help with this issue, correct.

**Comment by carlocab** [comment]
> Its not related to my internet connection , because when i remove this file its downloaded again lots people have similiar issue. 

Other people having the same problem does not rule out the possibility that there is an issue with your Internet connection. It's also possible, and, in my opinion, likely, that other people have the same connection problem that you're facing (assuming that these other people are indeed facing the same problem you are: that they are experiencing checksum mismatches too is not sufficient to conclude this).

> Its rather problem with portable ruby and different checksum.

I just downloaded portable ruby and I get the expected checksum: `0cb1cc7af109437fe0e020c9f3b7b95c3c709b140bde9f991ad2c1433496dd42`

**Comment by g1b3r** [comment]
Yes this was issue file have size 7kb but when i download manually have 9mb 

Thank you :)

**Comment by XuehaiPan** [comment]
Try:

```bash
HOMEBREW_CACHE="${HOME}/Library/Caches/Homebrew"
rm -f "${HOMEBREW_CACHE}/portable-ruby-2.6.8.yosemite.bottle.tar.gz"
wget -P "${HOMEBREW_CACHE}" https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.6.8/portable-ruby-2.6.8.yosemite.bottle.tar.gz
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by carlocab** [comment]
> Yes this was issue file have size 7kb but when i download manually have 9mb

This sounds exactly like a problem with your Internet connection.
