### ISSUE TITLE
If cloning the homebrew/core taps fails (like for a flaky network connection), `install.sh` will appear to succeed but `brew install` will fail

### ISSUE THREAD

**Issue by boblail** [Homebrew/install#633]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install Homebrew using the official script.

## What happened (include command output)

1. I interrupted the script while cloning the homebrew-core tap (or my Internet connection was interrupted).
2. I reran the script and it succeeded.
3. I tried to install a formula in the core tap and it failed.

<details>
  <summary>brew install homebrew/core/git</summary>
  <pre>
  ~ brew install homebrew/core/git
Warning: No available formula or cask with the name "homebrew/core/git".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
  </pre>
</details>

## What you expected to happen

I would've expected the second attempt to run `install.sh` to correct the problem _or_ to abort with an error like the one that `brew doctor` displays:
```
Warning: Homebrew/homebrew-core was not tapped properly! Run:
  rm -rf "/opt/homebrew/Library/Taps/homebrew/homebrew-core"
  brew tap homebrew/core
```

## Step-by-step reproduction instructions (by running `brew` commands)

1. `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
2. Press `Ctrl` `C` while it is tapping homebrew/core
3. `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
4. `brew install homebrew/core/git`

**Comment by osalbahr** [comment]
I'm trying to replicate this issue. At which step does tapping homebrew/core happen?

**Comment by osalbahr** [comment]
Did the behavior change that this is no longer an issue? It seems that tapping only happens at `brew install ...` or similar commands, and it tries to re-tap if I interrupt it:

```console
[dracula@fedora ~]$ brew install git
==> Tapping homebrew/core
Cloning into '/var/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1535573, done.
remote: Counting objects: 100% (1807/1807), done.
remote: Compressing objects: 100% (745/745), done.
^Cfetch-pack: unexpected disconnect while reading sideband packet

[dracula@fedora ~]$ brew install git
==> Tapping homebrew/core
Cloning into '/var/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1535573, done.
remote: Counting objects: 100% (1807/1807), done.
remote: Compressing objects: 100% (745/745), done.
^Cfetch-pack: unexpected disconnect while reading sideband packet

[dracula@fedora ~]$ 

```

**Comment by MikeMcQuaid** [comment]
Note this is only with `HOMEBREW_NO_INSTALL_FROM_API` set which is non-default and not recommended for end-users.
