### ISSUE TITLE
install.sh fail when the umask is not 0022

### ISSUE THREAD

**Issue by pcastellazzi** [Homebrew/install#637]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Installing brew on Debian 11 running on WSL 2 (Windows 10 Pro 21H2)

## What happened (include command output)

Installation failed

<details>
  <summary>Command output</summary>
  <pre>
bash install.sh
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew
==> The following new directories will be created:
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/etc
/home/linuxbrew/.linuxbrew/include
/home/linuxbrew/.linuxbrew/lib
/home/linuxbrew/.linuxbrew/sbin
/home/linuxbrew/.linuxbrew/share
/home/linuxbrew/.linuxbrew/var
/home/linuxbrew/.linuxbrew/opt
/home/linuxbrew/.linuxbrew/share/zsh
/home/linuxbrew/.linuxbrew/share/zsh/site-functions
/home/linuxbrew/.linuxbrew/var/homebrew
/home/linuxbrew/.linuxbrew/var/homebrew/linked
/home/linuxbrew/.linuxbrew/Cellar
/home/linuxbrew/.linuxbrew/Caskroom
/home/linuxbrew/.linuxbrew/Frameworks

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew
==> /usr/bin/sudo /bin/chown pcastellazzi:pcastellazzi /home/linuxbrew/.linuxbrew
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chmod ug=rwx /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chmod go-w /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> /usr/bin/sudo /bin/chown pcastellazzi /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/chgrp pcastellazzi /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/include /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share /home/linuxbrew/.linuxbrew/var /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew /home/linuxbrew/.linuxbrew/var/homebrew/linked /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Caskroom /home/linuxbrew/.linuxbrew/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew/Homebrew
==> /usr/bin/sudo /bin/chown -R pcastellazzi:pcastellazzi /home/linuxbrew/.linuxbrew/Homebrew
==> Downloading and installing Homebrew...
install.sh: line 898: cd: /home/linuxbrew/.linuxbrew/Homebrew: Permission denied
install.sh: line 898: return: can only `return' from a function or sourced script
/usr/.git: Permission denied
Failed during: git init -q
  </pre>
</details>

## What you expected to happen

I should get a running brew

## Step-by-step reproduction instructions (by running `brew` commands)

```!bash
$ umask 0077
$ bash install.sh # RESULT: Multiple permission denied errors

$ sudo rm -rf /home/linuxbrew/ # Used to start from scratch

$ umask 0022
$ bash install.sh # RESULT: SUCCESS
```

**Comment by MikeMcQuaid** [comment]
What do you propose as a solution? We could consider setting the `umask` in the script but then things will probably just break after installation?

**Comment by pcastellazzi** [comment]
I see two problems with the umask:

* There is the issue when `/home/linuxbrew/.linuxbrew` is created. The installer assumes the parent directory (`/home/linuxbrew`) would have 755 access, which is not the case when the umask is set to 0077. That's an easy fix, a simple chmod would do.

* From a security perspective, the installer and brew should make no assumptions about the umask, set it up to 7777 (no default privileges), and include the privilege information with each package in a similar way to what RPM, DPKG, and others do. This may be overkill.

About brew breaking after the installation, it did not happen in my tests, I have umask 0077 in both macos and wsl and brew work without issues on both (except for the reported failure to install).

Taking all of the above into consideration, I think the best solution would be to ensure `/home/linuxbrew` is created with the expected privileges, and in the case the umask the user is using is not supported (anything starting with 00 would work), abort with an explanation.

**Comment by pcastellazzi** [comment]
I think I made it work with a simple change. You can take a look [here](https://github.com/Homebrew/install/pull/643). 

I tried to run the tests workflow on my account but they failed with: 

```
...
HEAD is now at 96e87965b Merge pull request #13192 from Homebrew/update-man-completions
Updated Homebrew from 2d9bfc62b to 96e87965b.
Updated 5 taps (homebrew/core, homebrew/cask, homebrew/bundle, homebrew/services and aws/tap).
Error: invalid attribute for formula 'aws/tap/aws-sam-cli-nightly': version (nil)
Do not report this issue until you've run `brew update` and tried again.
...
```

I made a PR and its the workflows on your account, Ill take a look at the results later to make sure I did not break anything.
