### ISSUE TITLE
Installer fails - Ubuntu 22.04 on WSL

### ISSUE THREAD

**Issue by mpkonmbk** [Homebrew/install#638]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install homebrew inside WSL to keep my sanity :)
Windows 10 21H2 build 19044.1645
WSL2 with Ubuntu 22.04
everything stock and up to date

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  ➜  ~ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
[sudo] password for mpk:
==> /usr/bin/sudo /bin/chown -R mpk:mpk /home/linuxbrew/.linuxbrew/Homebrew
==> Downloading and installing Homebrew...
Updating files: 100% (2879/2879), done.
HEAD is now at a8bb0d658 Merge pull request #13174 from Bo98/gcc-major
To restore the stashed changes to /home/linuxbrew/.linuxbrew/Homebrew, run:
  cd /home/linuxbrew/.linuxbrew/Homebrew && git stash pop
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:cd7fffb18ef9338baa670fc5e8fce99b0e3cc0f0fd7627bcbb56f3c8d54161d4
Already downloaded: /home/mpk/.cache/Homebrew/portable-ruby-2.6.8.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.8.x86_64_linux.bottle.tar.gz
/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
Error: Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.8!
If there's no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.8 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again

Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force --quiet

  </pre>
</details>

## What you expected to happen

`brew` became available to use

## Step-by-step reproduction instructions (by running `brew` commands)

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by MikeMcQuaid** [comment]
CC @Homebrew/linux FYI

**Comment by gromgit** [comment]
>```
>/usr/bin/gzip: 1: ELF����: not found
>/usr/bin/gzip: 3: ���: not found
>/usr/bin/gzip: 4: Syntax error: "(" unexpected
>```

That's reminiscent of a corrupted `gzip` to me. What's the output of the following:
```
file /usr/bin/gzip
/usr/bin/gzip --help
```

**Comment by mpkonmbk** [comment]
Seems you are correct:
```
mpk@blade:~$ file /usr/bin/gzip
/usr/bin/gzip: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=09387e1f48c88dcc27c89d83dec42856690b93b0, for GNU/Linux 3.2.0, stripped
mpk@blade:~$ /usr/bin/gzip --help
-bash: /usr/bin/gzip: cannot execute binary file: Exec format error
```

**Comment by mpkonmbk** [comment]
Looks like, for some reason, I got WSL 1 installed instead of version 2 - no idea how. I'll retry on V2 and post results.

**Comment by mpkonmbk** [comment]
Works flawlessly now, thank you!
