### ISSUE TITLE
brew install php@8.0  Not Found httpd-2.4.52.tar.bz2,  How to specify the httpd version?

### ISSUE THREAD

**Issue by pooy** [Homebrew/install#641]
$ brew install php@8.0
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://ghcr.io/v2/homebrew/core/apr/manifests/1.7.0_2
Already downloaded: /Users/XXXX/Library/Caches/Homebrew/downloads/bea860ee12694d9b28c54323f66a2ed14e5b7b44c7fd2568ddd179b86f27829e--apr-1.7.0_2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/apr/blobs/sha256:4627416a5d9c651d2d4fbb7faa639d6f7a89c7c0558576eeac1f17a81a17f3bd
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/3d4af2c95a8ed746bc064514dbffe7d6b84eaee14c2b5aacfb42939545eb5a19--apr--1.7.0_2.mojave.bottle.tar.gz
==> Downloading https://www.openssl.org/source/openssl-1.1.1m.tar.gz
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/1fe651091c8b3c36a2f89a1bc970c0d3167db729f9ad9d8bde7b149d5f343c41--openssl-1.1.1m.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/apr-util/manifests/1.6.1_3
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/455c05bfd9638f75d0230e9d50505fabd95c7146ae3648d6bb047827bee1ca9e--apr-util-1.6.1_3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/apr-util/blobs/sha256:b3b8376d8f481164a34b891b926ab22acdc2903e77c4cfbc04c0ba6363ca7597
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/58bc95f13de1d85babb1706dc333c2ba48c8537671e374f30c52f1210a9add4c--apr-util--1.6.1_3.mojave.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/brotli/manifests/1.0.9
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/922ce7b351cec833f9bd2641f27d8ac011005f8b1f7e1119b8271cfb4c0d3cd7--brotli-1.0.9.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/brotli/blobs/sha256:d121eaa3e670d5ad972514a4cc000326249694c8b9691013e28b8dd52b87410d
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/c3be74ff31d34322a7803bd0ac191f2d7f492b66b553b40b660cb95addebbad5--brotli--1.0.9.mojave.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/ac691fc7ab8ecffba32a837e7197101d271474a3a84cfddcc30c9fd6763ab3c6--pkg-config-0.29.2_3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:0d14b797dba0e0ab595c9afba8ab7ef9c901b60b4f806b36580ef95ebb370232
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/8ec0df43df544eb23bf09290c43265593a3965b3862d56889c3de1c4ab7d672c--pkg-config--0.29.2_3.mojave.bottle.tar.gz
==> Downloading https://github.com/nghttp2/nghttp2/releases/download/v1.47.0/nghttp2-1.47.0.tar.gz
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/3091b9114b4aab989fcaa68d8f2b2a25eef751a4628eaf79df7e0a4ca4a8911d--nghttp2-1.47.0.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/pcre/manifests/8.45
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/4a3bba0e8d1899c13ac3442d2c49df6c1999948bdc0943f2f179693257d82545--pcre-8.45.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/pcre/blobs/sha256:a42b79956773d18c4ac337868cfc15fadadf5e779d65c12ffd6f8fd379b5514c
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/456b31dd91116840800d9cc2f35c6f2ebde8cfe8513e6d08dd6974f3309dc4f9--pcre--8.45.mojave.bottle.tar.gz
==> Downloading https://dlcdn.apache.org/httpd/httpd-2.4.52.tar.bz2

curl: (22) The requested URL returned error: 404
Trying a mirror...
==> Downloading https://downloads.apache.org/httpd/httpd-2.4.52.tar.bz2

**curl: (22) The requested URL returned error: 404 Not Found
Error: php@8.0: Failed to download resource "httpd"
Download failed: https://downloads.apache.org/httpd/httpd-2.4.52.tar.bz2**

I find  httpd  has  httpd-2.4.53.tar.bz2  version  (https://downloads.apache.org/httpd/)，How to use it ？

I tried to install php7.4, The same problem。 (brew install php@7.4)

thanks!

**Comment by Bo98** [comment]
Your homebrew-core installation is likely outdated. Check for errors when you do `brew update`.

If you're using a mirror for homebrew-core, try unset that or use an updated one.
