### ISSUE TITLE
Install script 404

### ISSUE THREAD

**Issue by Rajak4** [Homebrew/install#645]
Using the install script `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` returns a 404. I'm not sure where HEAD went to, but replacing it with `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"` works.

**Comment by Bo98** [comment]
We've raised the issue with GitHub as it change seems unexpected.

Looks like you've indeed found the workaround for now though.

**Comment by fredericsimard** [comment]
Same thing with the uninstall script. Just upgraded a user to have admin privileges, and tried to uninstall brew before reinstalling it for his user, got a 404 multiple times. Even when I changed `HEAD/` for `master/`.

**Comment by carlocab** [comment]
The uninstall script also references `HEAD`, unfortunately. You can download the script for now and edit it (or pipe it to `sed`) to fix the 404s.

**Comment by Vrajs16** [comment]
Does it matter if we don't use head and use master branch instead?

**Comment by Bo98** [comment]
No

**Comment by carlocab** [comment]
It doesn't matter now. It will matter if the branches are renamed at some point.

**Comment by gibfahn** [comment]
I believe the uninstall script is broken because of this:

https://github.com/Homebrew/install/blob/43864d6be72cff145babcc63b25eee30e19ea582/uninstall.sh#L275

**Comment by Bo98** [comment]
GitHub have rolled out a fix. Everything should be working now.

**Comment by fredericsimard** [comment]
Confirmed, it works as it did before.
