### ISSUE TITLE
Install command error

### ISSUE THREAD

**Issue by ashish-ad** [Homebrew/install#651]
https://github.com/Homebrew/install/blob/e9bf7b900e5153d4622b7dbc20b4a5eb35a34565/install.sh#L1010

Hey, Homebrew folks I found a problem that I think we need to change and as I can see there are no issues regarding this problem, I wanted to work on the above line code so that fixing it will be useful to many users.

Thank You.

**Comment by gromgit** [comment]
If you know exactly how to fix it, you should just open a PR with the proposed fix: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by ashish-ad** [comment]
OK thanks.
