### ISSUE TITLE
Suggestion: Support `NONINTERACTIVE=1` in the uninstall script

### ISSUE THREAD

**Issue by DannyBen** [Homebrew/install#654]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

```
$ uname -a
Linux 3fc3e70d9324 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

## What you were trying to do (and why)

Uninstall homebrew on a linux machine, non interactively, using the `uninstall` script:

```
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
```

## What happened (include command output)

The command stopped to ask me if I am sure.

<details>
  <summary>Command output</summary>
  <pre>

Warning: This script will remove:
/home/linuxbrew/.linuxbrew/Caskroom/
/home/linuxbrew/.linuxbrew/Cellar/
/home/linuxbrew/.linuxbrew/Homebrew/
/home/linuxbrew/.linuxbrew/Homebrew/.dockerignore
/home/linuxbrew/.linuxbrew/Homebrew/.editorconfig
/home/linuxbrew/.linuxbrew/Homebrew/.github/
/home/linuxbrew/.linuxbrew/Homebrew/.gitignore
/home/linuxbrew/.linuxbrew/Homebrew/.shellcheckrc
/home/linuxbrew/.linuxbrew/Homebrew/.sublime/
/home/linuxbrew/.linuxbrew/Homebrew/.vale.ini
/home/linuxbrew/.linuxbrew/Homebrew/.vscode/
/home/linuxbrew/.linuxbrew/Homebrew/CHANGELOG.md
/home/linuxbrew/.linuxbrew/Homebrew/CONTRIBUTING.md
/home/linuxbrew/.linuxbrew/Homebrew/Dockerfile
/home/linuxbrew/.linuxbrew/Homebrew/LICENSE.txt
/home/linuxbrew/.linuxbrew/Homebrew/Library//
/home/linuxbrew/.linuxbrew/Homebrew/README.md
/home/linuxbrew/.linuxbrew/Homebrew/bin/brew
/home/linuxbrew/.linuxbrew/Homebrew/completions/
/home/linuxbrew/.linuxbrew/Homebrew/docs/
/home/linuxbrew/.linuxbrew/Homebrew/manpages/
/home/linuxbrew/.linuxbrew/bin/brew -> /home/linuxbrew/.linuxbrew/Homebrew/bin/brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew -> /home/linuxbrew/.linuxbrew/Homebrew/completions/bash/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew -> /home/linuxbrew/.linuxbrew/Homebrew/docs
/home/linuxbrew/.linuxbrew/share/fish/vendor_completions.d/brew.fish -> /home/linuxbrew/.linuxbrew/Homebrew/completions/fish/brew.fish
/home/linuxbrew/.linuxbrew/share/man/man1/README.md -> /home/linuxbrew/.linuxbrew/Homebrew/manpages/README.md
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1 -> /home/linuxbrew/.linuxbrew/Homebrew/manpages/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew -> /home/linuxbrew/.linuxbrew/Homebrew/completions/zsh/_brew
/home/linuxbrew/.linuxbrew/var/homebrew/
/home/ubuntu/.cache/Homebrew/
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N]

  </pre>
</details>

## What you expected to happen

Expected the command to execute without stopping for user input, as if it was executed with `--force`.

## Step-by-step reproduction instructions (by running `brew` commands)

```bash
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
```

is expected to behave the same as:

```bash
wget https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
bash uninstall.sh --force
```

**Comment by MikeMcQuaid** [comment]
Good idea! Will review a PR for this.
