### ISSUE TITLE
Homebrew install

### ISSUE THREAD

**Issue by rajkumarmit** [Homebrew/install#658]
i have trying homebrew install on Apple M1 CHip laptop from below url /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
xcode 13.2.1 install already
and every time gives the error .
<img width="607" alt="Screenshot 2022-05-16 at 5 13 15 PM" src="https://user-images.githubusercontent.com/12801128/168585389-3efb02e9-1d98-458f-812e-c2c312578b6a.png">

Please tell me how the install homebrew without update xcode 

[](url)

**Comment by MikeMcQuaid** [comment]
> Please tell me how the install homebrew without update xcode

you cannot
