### ISSUE TITLE
Homebrew installation: Operation not permitted

### ISSUE THREAD

**Issue by alexbrueck1** [Homebrew/install#661]
MacOs version:  12.3.1 (MacBook Pro 14-inch, 2021)

## What you were trying to do (and why)

I was trying to install homebrew with the official command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

## What happened (include command output)

I was asked for my password and then pressed return: 

==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN/ENTER to continue or any other key to abort:

After pressing return I got a very long error message which basically said "Operation not permitted" to each and every single step. I will only paste the last couple of lines since the output was very long:

....
....
....
....
....

chown: /opt/homebrew/share/info/gdbm.info: Operation not permitted
chown: /opt/homebrew/share/info/dir: Operation not permitted
chown: /opt/homebrew/share/info/autoconf.info: Operation not permitted
chown: /opt/homebrew/share/info: Operation not permitted
chown: /opt/homebrew/share/ca-certificates: Operation not permitted
chown: /opt/homebrew/share/autoconf: Operation not permitted
chown: /opt/homebrew/share/doc/pkg-config: Operation not permitted
chown: /opt/homebrew/share/doc/mpdecimal: Operation not permitted
chown: /opt/homebrew/share/doc/homebrew: Operation not permitted
chown: /opt/homebrew/share/doc/xz: Operation not permitted
chown: /opt/homebrew/share/doc: Operation not permitted
chown: /opt/homebrew/share/zsh/site-functions/_brew: Operation not permitted
chown: /opt/homebrew/share/zsh/site-functions: Operation not permitted
chown: /opt/homebrew/share/zsh: Operation not permitted
chown: /opt/homebrew/share/fish/vendor_completions.d/brew.fish: Operation not permitted
chown: /opt/homebrew/share/fish/vendor_completions.d: Operation not permitted
chown: /opt/homebrew/share/fish: Operation not permitted
chown: /opt/homebrew/share/.keepme: Operation not permitted
chown: /opt/homebrew/share: Operation not permitted
chown: /opt/homebrew: Operation not permitted
Failed during: /usr/bin/sudo /usr/sbin/chown -R alexanderbruck_ep:admin /opt/homebrew
alexanderbruck_ep@MBPvonAlexander ~ %

**Comment by carlocab** [comment]
Is your Mac either a) work/school/etc-provided; or b) owned and/or managed by someone other than yourself? Do you have `sudo` access?

**Comment by alexbrueck1** [comment]
Hey Carlocab, It is my company laptop, but I am an admin, and thus, I assume I have sudo access by simply entering my Mac Account password?

**Comment by carlocab** [comment]
Possibly, but not always. Does using `sudo` directly work for you?

**Comment by alexbrueck1** [comment]
You mean if I can run sudo commands in the terminal? Yes, as far as I can tell it works ...

**Comment by carlocab** [comment]
Does `/opt/homebrew` exist? If it does, does doing
```
sudo chown -R "$(whoami):admin" /opt/homebrew
```
work?

**Comment by alexbrueck1** [comment]
If prompts me to enter my password and after doing so I get a permission denied: 

alexanderbruck_ep@MBPvonAlexander ~ % sudo chown -R "$(whoami):admin" /opt/homebrew

Password:

....
....
chown: /opt/homebrew/share/fish/vendor_completions.d: Operation not permitted
chown: /opt/homebrew/share/fish: Operation not permitted
chown: /opt/homebrew/share/.keepme: Operation not permitted
chown: /opt/homebrew/share: Operation not permitted
chown: /opt/homebrew: Operation not permitted


Does it mean, that I can't install homebrew with my Admin account? If yes, is there anything I can do (e. g. erase & reinstall my Mac)?

**Comment by carlocab** [comment]
This is determined by your IT admin's access policy. Only they can answer your questions; please follow this up with them.
