### ISSUE TITLE
Error when trying to install on ubuntu 22.04

### ISSUE THREAD

**Issue by UbayGD** [Homebrew/install#663]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install Homebrew using the official script

## What happened (include command output)

1 - Excute installation command
2 - Show error message

<details>
  <summary>Command output</summary>
  <pre>
remote: Enumerating objects: 208666, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (85/85), done.
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
error: 2340 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Failed during: git fetch --force origin
  </pre>
</details>

## What you expected to happen

Correct install

## Step-by-step reproduction instructions (by running `brew` commands)

- Ubuntu 22.04 (fresh install)
- Install build-essential, git and curl packages
- Execute homebrew install script

**Comment by MikeMcQuaid** [comment]
Regardless, this isn't something Homebrew can do anything about if your computer cannot connect to GitHub.

**Comment by UbayGD** [comment]
It seems that rather than a Wifi problem it was the wifi card itself. 

I have connected my phone and shared the connection via USB (the laptop detects it as ethernet) and it has been installed without problem. As a curiosity, my phone was connected to the same wifi that was giving me problems on the laptop...

Thank you very much and sorry for the inconvenience

**Comment by MikeMcQuaid** [comment]
No worries!
