### ISSUE TITLE
aarch64/Android/Termux/Ubuntu jammy 22.04/ homebrew-installer doesn't even try to install, i have Ruby 3.0.2, & need Homebrew to install working rbenv from github.

### ISSUE THREAD

**Issue by libweirdness** [Homebrew/install#667]
- [  yes ] your problem was from running the official `install` or `uninstall` script?
- [ never got that far ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)
I need a working rbenv

( the aarch64 port of rbenv in "jammy" is broken,
due to some screwy casting, apparently in C,
the jammy/apt rbenv install-process tells something
to consider all warnings as errors, and then it breaks,
with the jammy apt-installed rbenv,
so aarch64/jammy was apparently not tested for rbenv? )

so I need to install the *github* version of rbenv,
in order to have my learning-programming environment,
and the Ruby 2.5.x version that "The Well-Grounded Rubyist" is working with.

That *requires* Homebrew to work, to install rbenv.

## What happened (include command output)

I did the Homebrew homepage's installer thing,
which gave me on stderr:

```
Homebrew on Linux is not supported on ARM processors.
You can try an alternate installation method instead:
https://docs.brew.sh/Homebrew-on-Linux#arm
```
but, of course, there *are no* clear instructions
for how to do a proper installation from git,
*anywhere*, that I can find.

Are we supposed to do a git clone & then move everything
to a /usr/local/stow & use xstow to install symlinks?

( i use xstow to put Julia in my system )

## What you expected to happen

I wish it would at-least try,
so that any/all bugs in the process could
be hit, identified, & then removed,

or if not that, then explain, explicitly,
what we need to do to get it working on our platform.

The github version of rbenv isn't going to be working
on my learning environment until this happens, right?

I will try understanding what the homebrew-installer.sh script does,
& try muddling my way through things,
in the mean time...

Any success, or failure, if it'll help others,
will be added here.

## Step-by-step reproduction instructions (by running `brew` commands)

```
i do an export TODAY= `date +%F...` thing, to timestamp my logs, in my script.

nice  /bin/bash -c  \
"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  \
2>>  logs___rbenv/"$TODAY"___homebrew.err  \
|  tee  logs___rbenv/"$TODAY"___homebrew.log
```

Salut, Namaste, & Kaizen!

( :

**Comment by carlocab** [comment]
It seems simpler to just install `rbenv` without a package manager.

If you really must use Homebrew, you can try following these steps:
1. Install Ruby 2.6.8 and make sure it's available in your `PATH`.
2. Follow one of these [alternative installation methods](https://docs.brew.sh/Installation#alternative-installs).
3. Don't forget to add `brew` to your `PATH`.

I haven't tested these steps, so there might be one or two steps missing there to make it work.

The easiest way to do step 1 is probably using `rbenv`, so there might not even be a need for you to proceed any further. See https://github.com/rbenv/rbenv-installer#rbenv-installer.

**Comment by MikeMcQuaid** [comment]
We don't support it on ARM. If you can't figure out how to make it work: don't try, it is known to be broken in many ways.
