### ISSUE TITLE
Install script fails to detect version of glibc when ldd is not present

### ISSUE THREAD

**Issue by ogerardin** [Homebrew/install#670]
- [X] your problem was from running the official `install` or `uninstall` script?
- [X] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install Homebrew on Synology DSM.

## What happened (include command output)

Install script fails to detect version of glibc because there is no `ldd` command.

## What you expected to happen

glibc is present and you can get its version by executing it:
```
olivier@ds918plus:~$ /usr/lib/libc.so.6
GNU C Library (crosstool-NG 1.20.0) stable release version 2.20-2014.11, by Roland McGrath et al.
(...)
```
I was able to fool the installer by creating a fake `ldd` executable that echoes something that the script will accept:
```
olivier@ds918plus:~$ cat /usr/bin/ldd
#/bin/sh
echo "ldd 2.20"
```
With this the installer was able to install portable Ruby and complete the installation.

However it would be better if the install script didn't need this hack and would fall back to an alternative method when `ldd` is not present.

**Comment by gromgit** [comment]
It's a simple fix, but Homebrew seems to depend on a _working_ `ldd` (not just a version shim):
```
$ cd $(brew --repo) ; grep -Fwr ldd
vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/bundler/cli/doctor.rb:      Bundler.which("ldd")
vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/bundler/cli/doctor.rb:      output = `/usr/bin/ldd "#{path}"`.chomp
vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/bundler/cli/doctor.rb:      Bundler.which("ldd")
vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/bundler/cli/doctor.rb:      output = `/usr/bin/ldd "#{path}"`.chomp
os/linux/elf.rb:      ldd = DevelopmentTools.locate "ldd"
os/linux/elf.rb:      ldd_output = Utils.popen_read(ldd, path.expand_path.to_s).split("\n")
os/linux/glibc.rb:          version = Utils.popen_read("/usr/bin/ldd", "--version")[/ (\d+\.\d+)/, 1]
os/linux/glibc.rb:          version = Utils.popen_read(HOMEBREW_PREFIX/"opt/glibc/bin/ldd", "--version")[/ (\d+\.\d+)/, 1]
cmd/vendor-install.sh:  if [[ "$(/usr/bin/ldd --version)" =~ \ [0-9]\.[0-9]+ ]]
```
so I suspect your current Homebrew install may fail under certain circumstances.

**Comment by ogerardin** [comment]
> It's a simple fix, but Homebrew seems to depend on a _working_ `ldd` (not just a version shim):
> (...)
> so I suspect your current Homebrew install may fail under certain circumstances.

This trick is just needed to complete the install. Once it's done if you `brew install gcc` you will get a working `ldd`.

**Comment by ogerardin** [comment]
> if you `brew install gcc` you will get a working `ldd`.

Hmmm apparently not. But that doesn't seem to bother Homebrew, and I have installed a bunch of stuff.

**Comment by ogerardin** [comment]
Any chance the installer will be altered to detect glibc when ldd isn't present ?

**Comment by MikeMcQuaid** [comment]
We'll review a PR for this.
