### ISSUE TITLE
Can't uninstall homebrew

### ISSUE THREAD

**Issue by solita-michalguspiel** [Homebrew/install#674]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

### UNINSTALL HOMEBREW 

because:

My brew doctor states that 
```
Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
```

I can't seem to figure out how to change the prefix and therefore I'm trying to uninstall and re install homebrew in order to have it with the correct prefix.

## What happened (include command output)

```
/bin/bash: line 236: /usr/local/bin/brew: No such file or directory
Failed to locate Homebrew!

```

Even though homebrew exists on my machine.

## What you expected to happen

I expected homebrew to get uninstalled.

## Step-by-step reproduction instructions (by running `brew` commands)

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"`

**Comment by MikeMcQuaid** [comment]
`rm -rf $(brew --prefix)` should delete your Homebrew for you.

**Comment by carlocab** [comment]
Using
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
```
works only for the default prefix.

Since you're not using the default prefix, you need to download the script and pass `--path=/your/existing/prefix` to the script so that it can find your installation.
