### ISSUE TITLE
Is it possilble to install Linuxbrew on FreeBSD?

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [Homebrew/install#675]
Hello!

I tried to run the `brew` installation script on FreeBSD and got the error:
```
Homebrew is only supported on macOS and Linux.
```
https://github.com/Homebrew/install/blob/master/install.sh#L104

Is it possible to install `brew` on a BSD system somehow?

**Comment by Bo98** [comment]
Not currently, no. Even if you install it manually I'm not sure if anything will be installable.
