### ISSUE TITLE
Getting error when installing

### ISSUE THREAD

**Issue by addmorebass** [Homebrew/install#676]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x ] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

Getting this error:
HEAD is now at 86fe1f918 Merge pull request #13486 from Homebrew/dependabot/bundler/Library/Homebrew/sorbet-static-and-runtime-0.5.10127

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

HOMEBREW_VERSION: 3.4.4-27-ga7be469
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7be469995784fcad8775e00da5379e9cac9eb5c
Last commit: 3 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 656f04dce991a2b155b66abe22c44ed405e8ca43
Core tap last commit: 10 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.2.1 => /Users/chrisford/Desktop/Xcode.app/Contents/Developer
Rosetta 2: false

  </pre>
</details>

**Comment by gromgit** [comment]
Looks like you managed to at least install the `brew` command correctly, so run `/usr/local/bin/brew update-reset` to download the rest, then add the command `eval "$(/usr/local/bin/brew shellenv)"` to your shell's startup file (`~/.profile` if you're running bash, `~/.zprofile` if you're running zsh).

**Comment by addmorebass** [comment]
Getting this now @gromgit HEAD is now at 86fe1f918 Merge pull request #13486 from Homebrew/dependabot/bundler/Library/Homebrew/sorbet-static-and-runtime-0.5.10127
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by addmorebass** [comment]
Any ideas how to fix this?

Error: Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
Please create a new installation in /opt/homebrew using one of the
"Alternative Installs" from:
  https://docs.brew.sh/Installation
You can migrate your previously installed formula list with:
  brew bundle dump

**Comment by addmorebass** [comment]
Fixed by doing this https://stackoverflow.com/questions/64963370/error-cannot-install-in-homebrew-on-arm-processor-in-intel-default-prefix-usr
