### ISSUE TITLE
-bash: /home/aknight2015/.linuxbrew/bin/brew: No such file or directory

### ISSUE THREAD

**Issue by aknight2015** [Homebrew/install#679]
I ran the uninstall.sh and it ran without an issue. I start a new terminal and get:
-bash: /home/aknight2015/.linuxbrew/bin/brew: No such file or directory
How do I fix this?

**Comment by XuehaiPan** [comment]
Remove the line:

```
eval "$(/home/aknight2015/.linuxbrew/bin/brew shellenv)"
```

in your `~/.bash_profile` or `~/.profile`.
