### ISSUE TITLE
The uninstall.sh script can't uninstall homebrew on an ARM-based Mac when homebrew was initially installed on an Intel-based Mac

### ISSUE THREAD

**Issue by AvanteElectro** [Homebrew/install#680]
Hi !

I used Time Machine to install the OS of my ARM-based Mac from an Intel-based Mac backup. So homebrew is not installed where it is supposed to be and the script don't work : 

```
user@MacBook-Pro ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"  
/bin/bash: line 236: /opt/homebrew/bin/brew: No such file or directory
Failed to locate Homebrew!
```

How can I fix this issue please ?

Thx!

**Comment by apainintheneck** [comment]
You will need to download the [uninstall script](https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh) and specify the `--path=` option as explained here: https://github.com/Homebrew/install/issues/674#issuecomment-1164126766.
