### ISSUE TITLE
Invalid Formula

### ISSUE THREAD

**Issue by khoogheem** [Homebrew/install#682]
- [ x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

Ran on Xcode Cloud 

## What you were trying to do (and why)

Installing on Xcode Cloud
Script is:
```
# Install CocoaPods using Homebrew.
brew install cocoapods

# Install dependencies you manage with CocoaPods.
pod install
```

## What happened (include command output)

```
Cloning into '/Users/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
Updating files: 97% (6363/6537)
Updating files: 98% (6407/6537)
Updating files: 99% (6472/6537)
Updating files: 100% (6537/6537)
Updating files: 100% (6537/6537), done.
Error: Invalid formula: /Users/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libgccjit.rb
libgccjit: undefined method `on_arm' for #<Class:0x00007f992b718b50>
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing; `/Users/local/Homebrew/bin/brew tap homebrew/core` exited with 1.
```

**Comment by MikeMcQuaid** [comment]
You'll need to resolve this yourself.

**Comment by khoogheem** [comment]
little more info would be great..
`Error: Cannot tap homebrew/core: invalid syntax in tap!` 

Sure looks like an issue in homebrew... or that is a misleading error

**Comment by carlocab** [comment]
It's not an issue in Homebrew. It is an issue in the configuration of the machine you're running `brew` on. Try running `brew update` before doing `brew install`.

If that doesn't work, I have no further suggestions other than to check the output of `brew doctor` and to follow any advice that it shows.
