### ISSUE TITLE
Homebrew on Linux is only supported on Intel processors!

### ISSUE THREAD

**Issue by bckelley** [Homebrew/install#685]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] your problem was from running the official `install` or `uninstall` script? yes 
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?  no won't install

## What you were trying to do (and why)
won't install i get the aforementioned error, on WSL

![image](https://user-images.githubusercontent.com/15696431/183491899-a1873312-3880-45a3-b144-43f825eab2e3.png)
![image](https://user-images.githubusercontent.com/15696431/183491981-0a6c16f7-c4e3-4a64-a2ba-1d334375a37a.png)

Can homebrew not be installed on AMD? seriously it's 2022 come on!

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by dawidd6** [comment]
What is the output of `uname -m` on your machine?

**Comment by bckelley** [comment]
![image](https://user-images.githubusercontent.com/15696431/183499942-c7e1d78a-c5e4-4291-b5ac-235a53c0e625.png)

**Comment by gromgit** [comment]
> on WSL

WSL1, or WSL2? WSL1 has proven to be seriously problematic with Homebrew, though it usually manifests by inability to run just-installed binaries.

Try running:
```
/bin/bash -x -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 2>&1 | tee /tmp/install.log
```
then post the contents of `/tmp/install.log`. (Please post text output as text, _not_ screenshots as you've been doing so far.)

**Comment by meatballsong1** [comment]
Having the same problem, would appreciate a fix. 
armv71 is my output of uname -m

**Comment by gromgit** [comment]
> armv71 is my output of uname -m

That's a:
* 32-bit
* ARM CPU

so two strikes against official support. If you want to continue, you'll have to be prepared to put in a **_CRAP-TON_** of work, and figure out a lot of things by yourself.

As [the docs](https://docs.brew.sh/Homebrew-on-Linux#arm) say:
```
You may need to install your own Ruby using your system package manager, a PPA, or rbenv/ruby-build as we no longer distribute a Homebrew Portable Ruby for ARM.
```
At this writing, that means a Ruby *v2.6.8* install. I've had the most luck with using [rbenv](https://github.com/rbenv/rbenv)/[ruby-build](https://github.com/rbenv/ruby-build) as the docs suggest, but if your platform already has a precompiled Ruby of the right version, you can try using that instead.

Next, you'll have to build all formulae from source, no bottles for you. On a 32-bit ARM, toolchains like `gcc`, `rust` and even `go` will take a LONG time to build.

And many formulae may not even build on 32-bit CPUs in their current form. You'd have to figure out how these formulae need to be adjusted

You have been warned.
