### ISSUE TITLE
install.sh fails when POSIXLY_CORRECT is set

### ISSUE THREAD

**Issue by anths** [Homebrew/install#686]
- [x] your problem was from running the official `install` or `uninstall` script? yes
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I was trying to install homebrew using the instructions at the top of the homepage, on a new M2 mac running macOS 12.4.

## What happened (include command output)

The script fails with a syntax error:

<details>
  <summary>Command output</summary>
  <pre>

bash-3.2$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
/bin/bash: -c: line 394: syntax error near unexpected token `<'
/bin/bash: -c: line 394: `  done < <(which -a "$1")'

  </pre>
</details>

## What you expected to happen

Homebrew should be installed.

## Step-by-step reproduction instructions (by running `brew` commands)

Cannot be reproduced by running 'brew' commands (brew is not yet installed). To reproduce:
1. Execute bash
2. Execute the script suggested at the top of the homepage.

**Comment by anths** [comment]
This can be resolved locally by replacing the version of find_tool in install.sh with the one from 11 months ago:

https://github.com/Homebrew/install/commit/05c8d5a3682cce7c0917bacfccffb1dcf659502b?diff=split

I'd submit that change, but I have no idea why the change was made in the first place, and no ability to test it on other platforms.

**Comment by gromgit** [comment]
1. I'm not able to replicate your error
2. process substitutions a.k.a. `<( )` are definitely understood by bash v3.2
3. the line pointed to in your error is syntactically correct in context

What's the output of the following on your system?
```
ls -lL /bin/bash
/bin/bash -c '$echo $BASH_VERSION'
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /usr/bin/shasum -a 256
```

**Comment by carlocab** [comment]
We also regularly test this script with `/bin/bash` on macOS Big Sur. See the last run at https://github.com/Homebrew/install/runs/7394006553?check_suite_focus=true.

Big Sur ships the same version of `bash` as Monterey does (or, at least, it's definitely not _newer_), so the problem definitely isn't that the install script uses syntax that is too new.

**Comment by anths** [comment]
> bash-3.2$ ls -lL /bin/bash
> -r-xr-xr-x  1 root  wheel  1326576 May  7 22:20 /bin/bash
> bash-3.2$ /bin/bash -c 'echo $BASH_VERSION'
> 3.2.57(1)-release
> bash-3.2$ curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /usr/bin/shasum -a 256
> bcdaa4ade908e3766c74883f829c3dbb553a9808899bf58702651bd229d0c463  -

On this version of bash, the following fails:
> bash-3.2$ while read i; do echo $i; done < <(echo "$PATH")
> bash: syntax error near unexpected token `<'

Is that builder using Apple Silicon? I note the comments in the bash man page about when process substitution is available. It *sounds* like it ought to be available here, but isn't working.

**Comment by anths** [comment]
I've determined that some environment variable is causing bash to change its behavior. I'm currently trying to track down which.

**Comment by anths** [comment]
Okay: the culprit is POSIXLY_CORRECT. While this is set in the environment, bash doesn't recognize the process substitution syntax. Locally, this problem is caused by the fact that bash sets this automatically when invoked as sh (which happens earlier in my local startup) and never clears it when later invoked as bash. Just unsetting this environment variable makes the installer work.

I'm not sure what the preferred fix here is. Personally, I'd rather remove the explicit bashism, but a check, or just unsetting it like is done for HAVE_SUDO_ACCESS, would do the job just as well. Is there a preferred path?
