### ISSUE TITLE
uninstall does not work on M1 migrated from Intel

### ISSUE THREAD

**Issue by arhi** [Homebrew/install#690]
1. have brew working perfectly on your intel macmini
2. migrate this intel macmini to M1 macmini
3. brew is still in /usr/local/bin
```
minimac-m1:install bk$ which brew
/usr/local/bin/brew
```
4. decide to remove brew completly (so can install fresh one) but uninstall script is looking for brew in /opt
```
minimac-m1:BREW bk$ git clone https://github.com/Homebrew/install.git
Cloning into 'install'...
...
minimac-m1:install bk$ ./uninstall.sh 
./uninstall.sh: line 243: /opt/homebrew/bin/brew: No such file or directory
Failed to locate Homebrew!
minimac-m1:install bk$ which brew
/usr/local/bin/brew
minimac-m1:install bk$ 
```

**Comment by arhi** [comment]
ah, I see --path exists, sorry, stupid :(

maybe still add /usr/local to "Attempt to locate Homebrew" section :)

**Comment by carlocab** [comment]
> maybe still add /usr/local to "Attempt to locate Homebrew" section :) 

We're happy to review a PR for this.

**Comment by arhi** [comment]
> > maybe still add /usr/local to "Attempt to locate Homebrew" section :)
> 
> We're happy to review a PR for this.

here it is
https://github.com/Homebrew/install/pull/691
