### ISSUE TITLE
Uninstall script does rmdir /usr/local

### ISSUE THREAD

**Issue by perqa** [Homebrew/install#693]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ YES] your problem was from running the official `install` or `uninstall` script?
- [ N/A] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Uninstall the pre-M1 brew which came along from a Time Machine backup, with the intention to reinstall an M1-compatible brew version.

## What happened (include command output)

The uninstall script tried to remove my entire /usr/local/ directory!
<pre>
rmdir /usr/local
</pre>
<details>
  <summary>
Since the uninstall script path argument defaults to /opt/homebrew nowadays, I specified the old install path, /usr/local, which brew used on my M1 Mac.

</summary>
  <pre>
 sudo ./uninstall.sh --path=/usr/local
  Warning: This script will remove:
/Users/username/Library/Caches/Homebrew/
/Users/username/Library/Logs/Homebrew/
/usr/local/Caskroom/
/usr/local/Cellar/
/usr/local/bin/brew -> /usr/local/bin/brew
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] y
==> Removing Homebrew installation...
==> Removing empty directories...
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Homebrew /usr/local/Frameworks -name .DS_Store -delete
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Homebrew /usr/local/Frameworks -depth -type d -empty -exec rmdir {} ;
==> /usr/bin/sudo rmdir /usr/local
rmdir: /usr/local: Operation not permitted
Warning: Failed during: /usr/bin/sudo rmdir /usr/local
Warning: Homebrew partially uninstalled (but there were steps that failed)!
To finish uninstalling rerun this script with `sudo`.
The following possible Homebrew files were not deleted:
/usr/local/Frameworks/
/usr/local/Homebrew/
/usr/local/MacGPG2/
/usr/local/aws/
/usr/local/bin/
/usr/local/etc/
/usr/local/go/
/usr/local/include/
/usr/local/lib/
/usr/local/opt/
/usr/local/remotedesktop/
/usr/local/sbin/
/usr/local/share/
/usr/local/var/
You may wish to remove them yourself.

  </pre>
</details>

## What you expected to happen

I expected only Homebrew-related files and directories to be removed. The warning text listed a few directories which would be deleted, and usr/local was not one of them.

## Step-by-step reproduction instructions (by running `brew` commands)

<pre>
wget https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
chmod a+x ./uninstall.sh
sudo ./uninstall.sh --path=/usr/local
</pre>

**Comment by MikeMcQuaid** [comment]
> The uninstall script tried to remove my entire /usr/local/ directory!
> `sudo ./uninstall.sh --path=/usr/local`

I mean, you told it to remove that and it didn't succeed? I'm not sure I understand the issue here?

**Comment by perqa** [comment]
1. How should I have specified brew PATH for the uninstaller?
2. Why was usr/local not listed in the initial Warning when running the uninstaller? I could then have chosen to abort the operation.

**Comment by MikeMcQuaid** [comment]
@perqa `rmdir` only ever deletes empty directories so it was never trying to remove `/usr/local` unless everything else had already been removed from there.
