### ISSUE TITLE
Cant install homebrew due to side-effect of PR #13893 

### ISSUE THREAD

**Issue by daovietduy99** [Homebrew/install#696]
I tried to install homebrew in my new Macbook. Unfortunately, this error is throwing:

```
Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R duy.dao:admin /opt/homebrew
==> Downloading and installing Homebrew...
HEAD is now at 8de3e9371 Merge pull request #13893 from Homebrew/dependabot/github_actions/codecov/codecov-action-3.1.1
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

It seems there is some problem happened with the new `codecov-action-3.1.1` version, and the problem seems like caused by the #13893 revision.
Please help to check

**Comment by gromgit** [comment]
No, it's far more likely to be a network issue at your end, as this long-standing discussion thread indicates: https://github.com/orgs/Homebrew/discussions/666

**Comment by daovietduy99** [comment]
> No, it's far more likely to be a network issue at your end, as this long-standing discussion thread indicates: https://github.com/orgs/Homebrew/discussions/666

thank @gromgit for pointing out the issue. I have looked around, and it seems like the MAC issue. Let me update to the latest OS then try again. TIA

**Comment by daovietduy99** [comment]
The issue is caused I forgot ssh key for github. It should be closed.
