### ISSUE TITLE
fatal: unable to access 'https://github.com/Homebrew/brew/'

### ISSUE THREAD

**Issue by callmekofi** [Homebrew/install#708]
## What you were trying to do (and why)

Trying to install homebrew on macOS Monterey version 12.6

## What happened (include command output)
**fatal: unable to access 'https://github.com/Homebrew/brew/': Failed to connect to 127.0.0.1 port 1089 after 7 ms: Connection refused
Failed during: git fetch --force origin**

**Comment by MikeMcQuaid** [comment]
This is an issue with your internet connection.

**Comment by callmekofi** [comment]
My internet connection works perfectly.

**Comment by SMillerDev** [comment]
Clearly not because github.com should not be resolving to localhost port 1089.

**Comment by MikeMcQuaid** [comment]
Regardless: this is not a Homebrew issue but an issue with your local machine/setup/internet connection/anything.
