### ISSUE TITLE
Enable Pages for shorter install URL

### ISSUE THREAD

**Issue by abitrolly** [Homebrew/install#710]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script? yes
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue? not applicable

## What you were trying to do (and why)

Paste URL into char for unattended install. It turned out to be too long.

## What happened (include command output)

```
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

## What you expected to happen

```
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://homebrew.github.io/install/install.sh)" 
```

**Comment by SMillerDev** [comment]
Why is it too long?

**Comment by abitrolly** [comment]
Needs a scrollbar to read.

**Comment by abitrolly** [comment]
Ideally, it could be this.
```sh
sh <(curl brew.sh) -s -y
```

**Comment by SMillerDev** [comment]
If you remove the `NONINTERACTIVE=1` I don't need a scrollbar. But even if you don't, I fail to see how that is relevant to the install command.

**Comment by abitrolly** [comment]
@SMillerDev if you just enable GitHub Pages for `master` branch, the `install.sh` will automatically be available at alternative URL.

![image](https://user-images.githubusercontent.com/8781107/201641626-b9df1f37-11cc-4c21-9fc5-cd89bdf78220.png)

**Comment by SMillerDev** [comment]
I get what you are proposing as a fix, but how would "no scrollbar" improve the experience for all Homebrew users? I don't see how the GitHub UI having a scrollbar hinders Homebrew users in any way shape or form.

**Comment by MikeMcQuaid** [comment]
Passing on this.

**Comment by MikeMcQuaid** [comment]
> Fix for scrollbars are for GitHub users who have problems navigating/selecting/copying/pasting scrollbared content..

There's a button to copy with a single click. You can also select the entire field with a double click.

> For Homebrew users it will significantly improve the chance of memorizing the URL to type to install `brew` in a new environment, i.e. in remote workspace like Gitpod.

Memorising this doesn't something like something worth optimising for.

Similarly, a direct Git repository reference could be argued to be more secure than a GitHub Pages site here.

**Comment by abitrolly** [comment]
> Memorising this doesn't something like something worth optimising for.

Then optimize for inferring the URL from standard GitHub Pages URLs layout.

**Comment by abitrolly** [comment]
> Similarly, a direct Git repository reference could be argued to be more secure than a GitHub Pages site here.

Given that it is GitHub backend that deploys both, there is no difference. The difference can be if Pages don't fully support HTTPS or something.
