### ISSUE TITLE
Uninstalling Homebrew on a restored backup leads to attempting to delete `/usr/local/`

### ISSUE THREAD

**Issue by nadesai** [Homebrew/install#718]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
~- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?~

## What you were trying to do (and why)
- I restored an Apple Silicon Mac running macOS 12.5 from a backup of an Intel Mac that included Homebrew files. The backup was on a slightly older version of Mac OS.
- `brew doctor` indicated the Homebrew installation had been broken by the restore (in particular, the install was using `/usr/local` as is standard for Intel Macs, rather than `/opt/homebrew`) and should be completely uninstalled and reinstalled.
- I decided to use the official Homebrew uninstall script.

## What happened (include command output)
I ran the following command to uninstall Homebrew:
```
nikhildesai@nikhildesai ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
```

<details>
  <summary>Command output</summary>
  <pre>

```
/bin/bash: line 242: /opt/homebrew/bin/brew: No such file or directory
Warning: This script will remove:
/Users/nikhildesai/Library/Caches/Homebrew/
/usr/local/Caskroom/
/usr/local/Cellar/
/usr/local/bin/brew -> /usr/local/bin/brew
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] y
==> Removing Homebrew installation...
Warning: Failed to delete /usr/local/Caskroom
rm: /usr/local/Caskroom: Permission denied
Warning: Failed to delete /usr/local/Cellar
rm: /usr/local/Cellar: Permission denied
==> Removing empty directories...
Password:
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Caskroom /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks -name .DS_Store -delete
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Caskroom /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks -depth -type d -empty -exec rmdir {} ;
==> /usr/bin/sudo rmdir /usr/local
rmdir: /usr/local: Operation not permitted
Warning: Failed during: /usr/bin/sudo rmdir /usr/local
Warning: Homebrew partially uninstalled (but there were steps that failed)!
To finish uninstalling rerun this script with `sudo`.
The following possible Homebrew files were not deleted:
/usr/local/Frameworks/
/usr/local/Homebrew/
/usr/local/bin/
/usr/local/etc/
/usr/local/include/
/usr/local/lib/
/usr/local/opt/
/usr/local/sbin/
/usr/local/share/
/usr/local/texlive/
/usr/local/var/
You may wish to remove them yourself.
```

  </pre>
</details>

## What you expected to happen

Uninstall script does not attempt to delete `/usr/local`.

This may be simply an error in how the output message is constructed.

## Step-by-step reproduction instructions (by running `brew` commands)
Working on a M1 Mac initialized with a restored backup of an Intel Mac
````
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
```

**Comment by MikeMcQuaid** [comment]
> Uninstall script does not attempt to delete `/usr/local`.

Yes but what did you expect to be removed/not?



> * I restored an Apple Silicon Mac running macOS 12.5 from a backup of an Intel Mac that included Homebrew files. The backup was on a slightly older version of Mac OS.

Note that I think this is a niche enough case it's probably worth just handling yourself?
