### ISSUE TITLE
Install command is taking too long and responds with nothing

### ISSUE THREAD

**Issue by Parth589** [Homebrew/install#719]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

The provided install command [/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"] takes too long to install brew on linux machine (Popos 22)

## What happened (include command output)

Nothing happened for few minutes and following is the output

<details>
  <summary>Command output</summary>
  <pre>
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 130905 ms: Connection timed out

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew` commands)

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by SMillerDev** [comment]
This is a problem with your connection to GitHub. Nothing Homebrew can do about that.
