### ISSUE TITLE
wrong file mode for /usr/local/share/zsh

### ISSUE THREAD

**Issue by wiep** [Homebrew/install#72]
After installing homebrew on a fresh Sierra Mac, I noticed that homebrew's zsh side-functions don't get loaded.

executing compinit shows
```
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?
```

Running the compaudit returns the follows:
```
There are insecure directories:
/usr/local/share/zsh/site-functions
```

I could solve the problem for me by changing the file mode as follows:

```
sudo chmod -R 755 /usr/local/share/zsh
```

Maybe it is possible to update the installer, if this problem arises for many users.

**Comment by MikeMcQuaid** [comment]
When did you install Homebrew? The latest installer should have fixed this but it's perhaps a regression.

**Comment by wiep** [comment]
about 20 hours ago.

**Comment by MikeMcQuaid** [comment]
@wiep Thanks, definitely a bug on our side then. I'll try to reproduce and perhaps add a test to ensure this doesn't regress again.

**Comment by dreambottle** [comment]
I had the same issue, so I decided to fix this.

**Comment by MikeMcQuaid** [comment]
Was fixed in https://github.com/Homebrew/install/commit/d06d1d1ef3c5b0665fd534397ab28aa6c4a062dd
