### ISSUE TITLE
Mac M1 install failed chown: /Users/username: illegal user name

### ISSUE THREAD

**Issue by w4lle** [Homebrew/install#723]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

brew uninstall & reinstall
``/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"``
``/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"``

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
id: /Users/wanglinglong: no such user
==> The following existing directories will be made group writable:
/opt/homebrew/bin
/opt/homebrew/etc
/opt/homebrew/include
/opt/homebrew/lib
/opt/homebrew/sbin
/opt/homebrew/share
/opt/homebrew/opt
/opt/homebrew/var
/opt/homebrew/Frameworks
/opt/homebrew/var/homebrew
/opt/homebrew/var/homebrew/linked
==> The following existing directories will have their owner set to /Users/wanglinglong:
/opt/homebrew/bin
/opt/homebrew/etc
/opt/homebrew/include
/opt/homebrew/lib
/opt/homebrew/sbin
/opt/homebrew/share
/opt/homebrew/opt
/opt/homebrew/var
/opt/homebrew/Frameworks
/opt/homebrew/var/homebrew
/opt/homebrew/var/homebrew/linked
==> The following existing directories will have their group set to admin:
/opt/homebrew/bin
/opt/homebrew/etc
/opt/homebrew/include
/opt/homebrew/lib
/opt/homebrew/sbin
/opt/homebrew/share
/opt/homebrew/opt
/opt/homebrew/var
/opt/homebrew/Frameworks
/opt/homebrew/var/homebrew
/opt/homebrew/var/homebrew/linked
==> The Xcode Command Line Tools will be installed.

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chmod u+rwx /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/var /opt/homebrew/Frameworks /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked
==> /usr/bin/sudo /bin/chmod g+rwx /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/var /opt/homebrew/Frameworks /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked
==> /usr/bin/sudo /usr/sbin/chown /Users/wanglinglong /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/var /opt/homebrew/Frameworks /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked
chown: /Users/wanglinglong: illegal user name
Failed during: /usr/bin/sudo /usr/sbin/chown /Users/wanglinglong /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/opt /opt/homebrew/var /opt/homebrew/Frameworks /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked
------------------------------------------------------------
```
  </pre>
</details>

## What you expected to happen

install success

## Step-by-step reproduction instructions (by running `brew` commands)

``zsh: command not found: brew``

**Comment by gromgit** [comment]
What's the output of `id -a`?

**Comment by w4lle** [comment]
> 

 id -a                                                                                 wanglinglong@MacBook-Pro
uid=503(wanglinglong) gid=20(staff) groups=20(staff),1`2(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1)

**Comment by w4lle** [comment]
> What's the output of `id -a`?

 id -a                                                                                 wanglinglong@MacBook-Pro
uid=503(wanglinglong) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1)

**Comment by gromgit** [comment]
What's the output of `echo $USER`?

I'm guessing it's `/Users/wanglinglong`, when it should be just `wanglinglong`. Something is setting that variable incorrectly, probably in your shell startup script.

**Comment by chenrui333** [comment]
How about `$ env | grep wanglinglong `?

**Comment by w4lle** [comment]
```
echo $USER
/Users/wanglinglong
```

```
env | grep wanglinglong
PWD=/Users/wanglinglong
PATH=/opt/local/sbin:/opt/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/wanglinglong/.rvm/bin
HOME=/Users/wanglinglong
USER=/Users/wanglinglong
LOGNAME=wanglinglong
OLDPWD=/Users/wanglinglong
ZSH=/Users/wanglinglong/.oh-my-zsh
NVM_DIR=/Users/wanglinglong/.nvm
```
@chenrui333 @gromgit

**Comment by gromgit** [comment]
> ```
> echo $USER
> /Users/wanglinglong
> ```

As I said earlier, something is setting that incorrectly. For now, just `unset USER` and run the installer again, but once that's done, you really want to find out what's setting `USER`--that's one variable you should not be touching at all.

**Comment by w4lle** [comment]
> > ```
> > echo $USER
> > /Users/wanglinglong
> > ```
> 
> As I said earlier, something is setting that incorrectly. For now, just `unset USER` and run the installer again, but once that's done, you really want to find out what's setting `USER`--that's one variable you should not be touching at all.

yeah, in my .zshrc set``export USER=/Users/wanglinglong`` for PATH setting!

``unset`` is useful, thanks bro.

**Comment by w4lle** [comment]
and the export USER can be deleted.

**Comment by gromgit** [comment]
> yeah, in my .zshrc set`export USER=/Users/wanglinglong` for PATH setting!

Almost everyone I know uses `$HOME` for that, since that's literally your home directory.

**Comment by w4lle** [comment]
> > yeah, in my .zshrc set`export USER=/Users/wanglinglong` for PATH setting!
> 
> Almost everyone I know uses `$HOME` for that, since that's literally your home directory.

😂 I have changed from $USER to $HOME.
