### ISSUE TITLE
Short flag doesn't support space after option

### ISSUE THREAD

**Issue by n8henrie** [Homebrew/install#724]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Remove an old Intel (`/usr/local`) installation from an M1 that's working great from `/opt/homebrew`

## What happened (include command output)

``` console
$ wget -q https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
$ sha256sum uninstall.sh
83cbc1ce42adac22a53edcfa4cd11907c0da747d00ad556ec2ea6c84d331e602  uninstall.sh
$ bash uninstall.sh -n -p /usr/local
Warning: Unrecognized option: '/usr/local'
...
```

## What you expected to happen

It seems conventional to allow an optional space after a short flag (`--foo=bar` and `-f bar`); I expected `-p /usr/local/` to work the same as `--path=/usr/local/` or `-p/usr/local` (both of which work).

## Step-by-step reproduction instructions (by running `brew` commands)

As per above

I'd be happy to make a PR to this effect if it would be helpful; I think all that would be required would be an extra case statement for the short and long `-p`:

```
    case "${opt}" in
      -p)
        homebrew_prefix_candidates+=("$2")
        shift
        ;;
      --path)
        homebrew_prefix_candidates+=("$2")
        shift
        ;;
      # continue with -p*)
```

**Comment by SMillerDev** [comment]
If you have a fix a pull request would be appreciated
