### ISSUE TITLE
Unable to install Brew on Mac M2 Chip 

### ISSUE THREAD

**Issue by sourav-sportsbuzz** [Homebrew/install#726]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

I was trying to install homebrew on my MacBook Pro m2 chip and it is throwing me error on curl. 

After I tried running `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)` to install Homebrew.

<details>
  <summary>Command output</summary>
  <pre>
`curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75246 ms: Operation timed out`
  </pre>
</details>

## What you expected to happen

I expected homebrew to get installed onto my system.

## Step-by-step reproduction instructions (by running `brew` commands)

Unable to install. No brew command can be used.

**Comment by SMillerDev** [comment]
This is a problem with your internet connection. Nothing Homebrew can do about that.

**Comment by SMillerDev** [comment]
You might be doing multiple things, but this is a connection issue nonetheless. Curl is very clear about that: `Failed to connect to raw.githubusercontent.com`

**Comment by suneeltechnew** [comment]
I am also getting same issue. my internet is also good.
I am using macOS with M1 chip.

**Comment by suneeltechnew** [comment]
@sourav-sportsbuzz , @SMillerDev 
I have resolved the issue by following https://www.debugpoint.com/failed-connect-raw-githubusercontent-com-port-443/
