### ISSUE TITLE
Unable to Install Homebrew

### ISSUE THREAD

**Issue by iron-coder12** [Homebrew/install#730]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [yes ] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I was trying to install homebrew on my pc (windows WSL)

## What happened (include command output)

rikter@MY-PC22:~$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
[sudo] password for rikter:
==> /usr/bin/sudo /bin/chown -R rikter:rikter /home/linuxbrew/.linuxbrew/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 812, done.
remote: Counting objects: 100% (622/622), done.
remote: Compressing objects: 100% (189/189), done.
remote: Total 812 (delta 453), reused 575 (delta 422), pack-reused 190
Receiving objects: 100% (812/812), 712.31 KiB | 4.91 MiB/s, done.
Resolving deltas: 100% (507/507), completed with 100 local objects.
From https://github.com/Homebrew/brew
 * [new branch]          dependabot/bundler/Library/Homebrew/concurrent-ruby-1.2.0 -> origin/dependabot/bundler/Library/Homebrew/concurrent-ruby-1.2.0
   3e257890d..8f419180c  master     -> origin/master
 * [new tag]             3.6.20     -> 3.6.20
HEAD is now at 8f419180c Merge pull request #14406 from Homebrew/dependabot/bundler/Library/Homebrew/rubocop-1.44.0
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
error: 4241 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Error: Fetching /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core failed!
fatal: invalid upstream 'origin/master'
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force --quiet

## What you expected to happen

I expected homebrew to be installed so i can start using it

## Step-by-step reproduction instructions (by running `brew` commands)

rikter@MY-PC22:~$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by MikeMcQuaid** [comment]
This is a network issue connecting to GitHub. Try again.

**Comment by MikeMcQuaid** [comment]
We can't help you, sorry.

**Comment by bluewire-solutions** [comment]
can confirm that issue, network is fine
