### ISSUE TITLE
Remove the need for cloning the entire world's history during install

### ISSUE THREAD

**Issue by Hermholtz** [Homebrew/install#731]
The install script copies the entire 563 + 67 MiB of data and it takes good 10 minutes to install homebrew (majority of which is downloading data and git resolving deltas). How do you envision that process in another 3 years from now given that you decline to use `--depth=1` (#195)? Is it going to take 20 minutes? Is this software like a blockchain that needs to have all past commits for it to work? Ignoring #195 was maybe possible back in 2019, but now it becomes PITA all the way.

You may not be aware of the issue, because you don't install this tool anymore yourself. But the installation is broken.

Of course it may be needed to reengineer `brew update`, which should be no more than usual overwrite of the latest version over what's on my computer...

- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)
Install homebrew the novice way.

## What happened (include command output)
It took a good 10 minutes on a fairly powerful MacBook Pro.

Output not relevant to the issue, however `git` outputted a lot of tags, 1.404.012 objects and 536.39 MiB.

## What you expected to happen
Fast installation.

## Step-by-step reproduction instructions (by running `brew` commands)
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh"`

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Installation#skip-tap-cloning-beta
