### ISSUE TITLE
version information: Homebrew/homebrew-core N/A

### ISSUE THREAD

**Issue by califodream** [Homebrew/install#738]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

### **WHY**

I've installed the old version of homebrew(2.x.x) a long time ago. 

### **WHAT**

And then I decided to uninstall it using the command below
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"` as suggested. 

Next, I reinstall a new homebrew using the command below
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` as suggested.

And nothing **ERROR** or **WARNING** I've got.

### **THEN**

Finally, I want to check which version I just installed. So I type `brew --version` which returns a funny response as below
```
➜  ~ brew --version
Homebrew 4.0.1
Homebrew/homebrew-core N/A
```

### **INCLUDE**
```
➜  ~ brew --version
Homebrew 4.0.1
Homebrew/homebrew-core N/A
➜  ~ brew config
HOMEBREW_VERSION: 4.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17c872fb5275d87922a56416587cb439a5064354
Last commit: 19 hours ago
Core tap JSON: 17 Feb 08:07 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
http_proxy: http://127.0.0.1:8001
https_proxy: http://127.0.0.1:8001
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.0.1
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/js_native_api.h
......
 all below is paths with prefix of /usr/local/include/node/xxx.h
......
```

## What happened (include command output)
```
➜  ~ brew --version
Homebrew 4.0.1
Homebrew/homebrew-core N/A
```

<details>
  <summary>Command output</summary>
  <pre>
 ➜  ~ brew --version
Homebrew 4.0.1
Homebrew/homebrew-core N/A
  </pre>
</details>

## What you expected to happen

**I just wanna get the version information like that instead of N/A**
```
brew -v
Homebrew 2.2.2
Homebrew/homebrew-core (git revision 71aa; last commit 2020-01-07)
Homebrew/homebrew-cask (git revision 84f00; last commit 2020-01-07)
```

## Step-by-step reproduction instructions (by running `brew` commands)
```
➜  ~ brew --version
Homebrew 4.0.1
Homebrew/homebrew-core N/A
```

**Comment by SMillerDev** [comment]
4.0.0 switched to an API instead of a git repo for formulae by default. There will never be a version there.

**Comment by carlocab** [comment]
We should get rid of that line when the core repo isn't tapped though.
