### ISSUE TITLE
MacOS doesn't trust the `.pkg` from Github Actions

### ISSUE THREAD

**Issue by Jubeki** [Homebrew/install#739]
- [ ] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

OS Version: MacOS Ventura 13.1

## What you were trying to do (and why)

I tried to upgrade homebrew using the provided `.pkg` from Github Actions:
> [Homebrew 4.0.0 Anouncement](https://brew.sh/2023/02/16/homebrew-4.0.0/)  
> 
> [macOS .pkg files are generated for each Homebrew release](https://github.com/Homebrew/brew/pull/14265). You can help us test this beta feature by [downloading the generated package artifact from the relevant GitHub Actions release events](https://github.com/Homebrew/brew/actions/workflows/build-pkg.yml?query=event%3Arelease).

## What happened (include command output)

I got the following error:

<img width="263" alt="Screenshot 2023-02-17 at 09 54 03" src="https://user-images.githubusercontent.com/15707543/219599713-23269310-1125-451b-8256-028ba60c5b97.png">

## What you expected to happen

It should install the newer Homebrew version

## Step-by-step reproduction instructions (by running `brew` commands)

1. Download from https://github.com/Homebrew/brew/actions/workflows/build-pkg.yml?query=event%3Arelease (Or directly 4.0.1: https://github.com/Homebrew/brew/suites/11021830810/artifacts/559392738 )
2. Unzip the download
3. Try to install Homebrew

**Comment by SMillerDev** [comment]
Yeah, we still need to figure out signing.

**Comment by TETRA2000** [comment]
I submitted a draft PR for this issue. 😃
https://github.com/Homebrew/brew/pull/14708
