### ISSUE TITLE
brew install neo4j adding unrecognized config 

### ISSUE THREAD

**Issue by sirosc** [Homebrew/install#741]
@hwkns-plumbr Our stalebot closed it regardless as part of a triage process given not many folks seems to care about it and it's still unclear to me that it's a Homebrew problem. We'll review PRs to address any problem here but no maintainers are working on this (hence the close).

_Originally posted by @MikeMcQuaid in https://github.com/Homebrew/homebrew-core/issues/114553#issuecomment-1341126451_
            
The original thread covers the details well.  This is still failing with the latest version of neo4j 5.5.

To answer the question of whether this is a homebrew issue, these are the lines that caused neo4j to complain about unrecognized settings in neo4j.conf (the first two, which I commented out to get neo4j working):

```
#********************************************************************
# Other Neo4j system properties
#********************************************************************
#wrapper.java.additional=-Djava.awt.headless=true
#wrapper.java.additional.4=-Dneo4j.ext.udc.source=homebrew
dbms.directories.data=/opt/homebrew/var/neo4j/data
dbms.directories.logs=/opt/homebrew/var/log/neo4j

```

**Comment by SMillerDev** [comment]
Wrong repository. We'll consider a pull request to Homebrew/core that fixes this.
