### ISSUE TITLE
Asks for password even if the current user has passwordless sudo access.

### ISSUE THREAD

**Issue by Lwrless** [Homebrew/install#746]
- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Executing brew install script on Ubuntu 22.04.1 LTS (created with [Multipass](https://github.com/canonical/multipass)). Current user `ubuntu` has passwordless `sudo` access, and by default this user does not have a password.

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
==> Checking for `sudo` access (which may request your password)...
[sudo] password for ubuntu:
  </pre>
</details>

## What you expected to happen

Skip making `sudo` ask for a password if the user already has passwordless `sudo` access, this could be checked with the following command: `sudo -n true`.

**Comment by gromgit** [comment]
Prepending `NONINTERACTIVE=1` to the installer invocation:
```
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
is the easy workaround.

**Comment by MikeMcQuaid** [comment]
> Skip making `sudo` ask for a password if the user already has passwordless `sudo` access, this could be checked with the following command: `sudo -n true`.

We'll review a PR for this.
