### ISSUE TITLE
cannot install xcode command line tools

### ISSUE THREAD

**Issue by jfindlay** [Homebrew/install#77]
I'm unsure if this is the correct place to report this issue, so please redirect me if I am incorrect.

I am trying to install brew on a newly provisioned parallels El Capitan VM.
```console
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
touch: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress: Operation not permitted
Failed during: /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
```

It seems that nothing can modify the contents of `/tmp` (`/private/tmp`).
```console
$ touch /tmp/file
touch: /tmp/file: Operation not permitted
$ sudo touch /tmp/file
touch: /tmp/file: Operation not permitted
```
as the extended attributes suggest
```console
$ xattr /private /private/tmp
/private: com.apple.FinderInfo
/private/tmp: com.apple.rootless
```

**Comment by MikeMcQuaid** [comment]
Can you do `touch $TMPDIR/file`?

**Comment by jfindlay** [comment]
I wondered about this, but will writing to `$TMPDIR/.com.apple.dt.CommandLineTools.installondemand.in-progress` be able to convince macOS to install the command line tools?
```console
$ touch $TMPDIR/file
$ ls -l $TMPDIR/file
-rw-r--r--  1 jenkins  staff  0 Oct 18 09:08 /var/folders/pr/fy0gqkzx1ss1_qngkfjry2xw0000gn/T//file
$ xattr $TMPDIR
$ xattr $TMPDIR/file
```

**Comment by ilovezfs** [comment]
What's the output of `sw_vers`?

**Comment by jfindlay** [comment]
```console
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1004
```

**Comment by ilovezfs** [comment]
Does the problem survive a reboot?

**Comment by jfindlay** [comment]
Yes, I've rebooted several times; same result.

**Comment by ilovezfs** [comment]
Can you come on IRC on freenode? Channel is #machomebrew
https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23machomebrew

**Comment by jfindlay** [comment]
Thanks to @ilovezfs for helping me debug some kind of misconfiguration or corruption with the VM.  For anyone who may find this issue in the future, these are the actions allowed the command line tools to be installed:
- [reboot](http://kb.parallels.com/en/116526) into recovery mode
- open a terminal and run
  - `csrutil disable`
  - `/usr/libexec/repair_packages --verify --standard-pkgs --volume /Volumes/<my volume>` where `<my volume>` is the volume where you installed macOS.
- reboot into system and install brew+command line tools, `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
- reboot into recovery and run `csrutil enable`
- reboot into system
- `brew install htop`

Recreating a clean VM should solve the problem for me.
