### ISSUE TITLE
Cannot request a version tag

### ISSUE THREAD

**Issue by ctrlcctrlv** [Homebrew/install#771]
Consider applying https://github.com/ctrlcctrlv/Homebrew-AUR-installer/commit/a2184e0356a7f11fa40bc178db1fc7068eeb1f77.

**Comment by SMillerDev** [comment]
We don't support installing specific versions, passing on this.

**Comment by ctrlcctrlv** [comment]
if policies do not change most likely the AUR package will be the first and last, and Arch the only major Linux distro that even attempts to package linuxbrew, as the AUR has the laxest rules of any mainstream package repo, but we still require non -git packages to install a real version, and not to install into the user's /home, among other highly sensible requirements.

regardless, i'm happy with the package.

![image](https://github.com/Homebrew/install/assets/838783/4bf8fe60-1758-4abf-83ad-ac41e752ff0b)

**Comment by SMillerDev** [comment]
I can't really imagine there's any reason for an AUR package though. Homebrew shares it's packaging philosophy with arch so you'll just have similar packages.

**Comment by ctrlcctrlv** [comment]
well hardly.

as you can probably tell i do a lot of packaging which is why i even wanted `brew` around.

i want to package something else on the AUR which only supports brew building. now that pkg can have brew as a makedepend, and it's not allowed in the `package()` or `build()` blocks to get root as u ahve fakeroot (thus my addition of `HOMEBREW_ROOT_OKIE_DOKIE` envvar)

**Comment by ctrlcctrlv** [comment]
with my way i never have to even install any package w/brew. so the extent to which it's broken barely matters. i can brew a bottle, and then use the bottle to install.

**Comment by ctrlcctrlv** [comment]
(and it's quite broken. `brew doctor` will trash the system)

**Comment by ctrlcctrlv** [comment]
i have also on my archtop dpkg, apt, rpm, yum, and emerge.

![image](https://github.com/Homebrew/install/assets/838783/15fbeb42-e4fc-43f5-af5f-4d2f54e521c5)

**Comment by reitermarkus** [comment]
> package something else on the AUR which only supports brew building

What does that even mean? When would something only build with Homebrew but not with the package manager you are using for AUR?

**Comment by ctrlcctrlv** [comment]
because they're incompetent and only distribute a brew build file and not a makefile/cmakelists etc

**Comment by ctrlcctrlv** [comment]
now, potentially, yes i can figure out how to build it. but why...when brew is free software and easily usable for the task, esp if i tell it ignore deps.

**Comment by reitermarkus** [comment]
> only distribute a brew build file and not a makefile/cmakelists etc

Can you point to an example?

**Comment by ctrlcctrlv** [comment]
https://github.com/pflouret/overdrive-m4b

**Comment by MikeMcQuaid** [comment]
> if policies do not change most likely the AUR package will be the first and last

@ctrlcctrlv That's fine with us.

> because they're incompetent and only distribute a brew build file

Adjust your tone in our issue tracker. That's not an appropriate way to speak about other open source maintainers here.
