### ISSUE TITLE
Install script CentOS 7 can't find git

### ISSUE THREAD

**Issue by osalbahr** [Homebrew/install#773]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?
```
[osalbahr@vclvm177-222 ~]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[osalbahr@vclvm177-222 ~]$ uname -a
Linux vclvm177-222.vcl.ncsu.edu 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[osalbahr@vclvm177-222 ~]$ 
```

## What you were trying to do (and why)

I was trying to install Homebrew so I can `brew install neofetch`.

## What happened (include command output)

<details>
  <summary>You must install Git before installing Homebrew</summary>
  <pre>
[osalbahr@vclvm177-222 ~]$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm177-222 ~]$ 
  </pre>
</details>

## What you expected to happen

<details>
  <summary>I expected the install script to go through, since I do have git installed:</summary>
  <pre>
[osalbahr@vclvm177-222 ~]$ git --version
git version 1.8.3.1
[osalbahr@vclvm177-222 ~]$ which -a git
/usr/bin/git
[osalbahr@vclvm177-222 ~]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/osalbahr/.local/bin:/home/osalbahr/bin
[osalbahr@vclvm177-222 ~]$ sudo yum install -y git
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: linux-mirrors.fnal.gov
 * epel: forksystems.mm.fcix.net
 * extras: distro.ibiblio.org
 * updates: centos.mirror.constant.com
Package git-1.8.3.1-24.el7_9.x86_64 already installed and latest version
Nothing to do
[osalbahr@vclvm177-222 ~]$ sudo dnf install -y git
Last metadata expiration check: 0:03:10 ago on Wed 17 May 2023 11:12:33 AM CDT.
Package git-1.8.3.1-24.el7_9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[osalbahr@vclvm177-222 ~]$ 
  </pre>
</details>

<details>
  <summary>The same happens after `sudo yum update && sudo reboot` </summary>
  <pre>
[osalbahr@vclvm177-222 ~]$ sudo yum update
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: coresite.mm.fcix.net
 * epel: download-ib01.fedoraproject.org
 * extras: mirrors.lug.mtu.edu
 * updates: mirror.wdc2.us.leaseweb.net
No packages marked for update
[osalbahr@vclvm177-222 ~]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[osalbahr@vclvm177-222 ~]$ uname -a
Linux vclvm177-222.vcl.ncsu.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[osalbahr@vclvm177-222 ~]$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm177-222 ~]$ 
  </pre>
</details>

I'm not sure what [`find_tool`](https://github.com/Homebrew/install/blob/master/install.sh#L405) does.

#574 might be related. If this is a case of git version issue, the install script might benefit from a different error message.

## Step-by-step reproduction instructions (by running `brew` commands)

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by osalbahr** [comment]
I see. Shouldn't "Unexpected Git version ..." be printed then?

**Comment by reitermarkus** [comment]
Yeah, would make sense to improve the error message.

**Comment by Bo98** [comment]
Yes it should. Looking at the install script, the message logic does not look correct at all.

**Comment by osalbahr** [comment]
I get the same error message if I `sudo yum remove -y git`
```
[osalbahr@vclvm176-217 ~]$ git --version
bash: git: command not found...
[osalbahr@vclvm176-217 ~]$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm176-217 ~]$ 
```

**Comment by osalbahr** [comment]
Well, this is interesting
```
[osalbahr@vclvm176-217 install]$ ./install.sh 
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
==> Found Git: git
==> Found cURL: git
==> Setting HOMEBREW_DEVELOPER to use Git/cURL not in /usr/bin
==> Downloading and installing Homebrew...
HEAD is now at f7b3225 Merge pull request #15447 from carlocab/all-github-vars
Error: Please update your system curl or set HOMEBREW_CURL_PATH to a newer version.
Minimum required version: 7.41.0
Your curl version: 1.8.3.1
Your curl executable: 
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force --quiet
```

All I did was
```
[osalbahr@vclvm176-217 install]$ git diff install.sh 
diff --git a/install.sh b/install.sh
index 2fa9330..425cd3a 100755
--- a/install.sh
+++ b/install.sh
@@ -419,6 +419,7 @@ find_tool() {
       echo "${executable}"
       break
     fi
+  echo "git"
   done < <(which -a "$1")
 }

 ```

And as a sanity check
```
[osalbahr@vclvm176-217 install]$ git checkout .
[osalbahr@vclvm176-217 install]$ ./install.sh 
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm176-217 install]$ 
```

.... Even though
```
[osalbahr@vclvm176-217 install]$ which -a git
/usr/bin/git
[osalbahr@vclvm176-217 install]$ git --version
git version 1.8.3.1
[osalbahr@vclvm176-217 install]$ 
```

**Comment by osalbahr** [comment]
> Seems like `test_git` is never called.

I thought so too. But it is called

```
[osalbahr@vclvm176-217 install]$ ./install.sh 
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
Warning: foo /usr/bin/git bar
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm176-217 install]$ git diff
diff --git a/install.sh b/install.sh
index 2fa9330..d66f5c4 100755
--- a/install.sh
+++ b/install.sh
@@ -378,6 +378,7 @@ test_curl() {
 }
 
 test_git() {
+  warn "foo $1 bar"
   if [[ ! -x "$1" ]]
   then
     return 1
[osalbahr@vclvm176-217 install]$ 
```

**Comment by osalbahr** [comment]
I added some `warn` messages, it looks like it goes to the `else` block (which doesn't exist)

```
[osalbahr@vclvm176-217 install]$ git diff
diff --git a/install.sh b/install.sh
index 2fa9330..223459e 100755
--- a/install.sh
+++ b/install.sh
@@ -387,7 +387,11 @@ test_git() {
   git_version_output="$("$1" --version 2>/dev/null)"
   if [[ "${git_version_output}" =~ "git version "([^ ]*).* ]]
   then
+    warn "${git_version_output}"
     version_ge "$(major_minor "${BASH_REMATCH[1]}")" "$(major_minor "${REQUIRED_GIT_VERSION}")"
+    ret=$?
+    warn "ret=$ret"
+    return $ret
   else
     abort "Unexpected Git version: '${git_version_output}'!"
   fi
@@ -411,6 +415,7 @@ find_tool() {
   local executable
   while read -r executable
   do
+    warn "exectuable=${executable}"
     if [[ "${executable}" != /* ]]
     then
       warn "Ignoring ${executable} (relative paths don't work)"
@@ -418,6 +423,8 @@ find_tool() {
     then
       echo "${executable}"
       break
+    else
+      warn "else"
     fi
   done < <(which -a "$1")
 }
[osalbahr@vclvm176-217 install]$ ./install.sh 
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
Warning: exectuable=/usr/bin/git
Warning: git version 1.8.3.1
Warning: ret=1
Warning: else
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm176-217 install]$ 
```

**Comment by maxim-belkin** [comment]
Could you please check if the install script before commit c699c940172c768de8600566e1dc263c22c62e22  works as expected?

```sh
git checkout c699c940172^
bash ./install.sh
```

**Comment by maxim-belkin** [comment]
> All I did was
> 
> ```
> [osalbahr@vclvm176-217 install]$ git diff install.sh 
> diff --git a/install.sh b/install.sh
> index 2fa9330..425cd3a 100755
> --- a/install.sh
> +++ b/install.sh
> @@ -419,6 +419,7 @@ find_tool() {
>        echo "${executable}"
>        break
>      fi
> +  echo "git"
>    done < <(which -a "$1")
>  }
> ```

`find_tool` is a tool-agnostic function. By echo-ing `git` unconditionally, you made it report `git` as an executable it found when it was asked to look for something else.

**Comment by osalbahr** [comment]
Do all `brew` commands also use `find_tool` or do they grab the first `git` in `PATH`? Because if it was the latter, the way `find_tool` is written might be problematic if an older version appears before a newer version in `PATH`.

**Comment by maxim-belkin** [comment]
> The current version of `find_tool` doesn't tell the different between a tool not existing and the tool existing but of a bad version. This might be intentional, I don't know.

it is.

> I was also able to find a one-line fix.

What do you mean by that?



> Bad Git version: 'git version 1.8.3.1'!

There is nothing wrong with that version of Git. The error message that was provided tells the user which version is necessary and I'm not sure we need to report which version is installed (user should know this).


@MikeMcQuaid
@gromgit
@ChillerDragon
Looks like #756 introduced a bug, which is causing the issue reported here.

**Comment by osalbahr** [comment]
> What do you mean by that?

Oh, it just means that it fixes the error by changing one line. But nevermind, I misunderstood the purpose of `find_tool`. The current implementation is fine as long as `brew` does something similar to skip bad versions of tools that happen to come before a good version in `PATH`. This might be a rare case, I'm not sure.

> There is nothing wrong with that version of Git. The error message that was provided tells the user which version is necessary and I'm not sure we need to report which version is installed (user should know this).

True, it was only a placeholder message. We probably don't *need* to report the current version of `git`, but that wouldn't be consistent with the current check for `curl`:
```
Minimum required version: 7.41.0
Your curl version: 1.8.3.1
```

**Comment by osalbahr** [comment]
> Looks like #756 introduced a bug, which is causing the issue reported here.

I think the issue existed before

```
[osalbahr@vclvm176-217 install]$ git checkout 6df4f60d30f5acab648ba79d7fc4c262e3c4d305
HEAD is now at 6df4f60... Merge pull request #760 from b8rky/support-oci-containers
[osalbahr@vclvm176-217 install]$ ./install.sh 
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/chown -R osalbahr:NCSU /home/linuxbrew/.linuxbrew/Homebrew
You must install Git before installing Homebrew. See:
  https://docs.brew.sh/Installation
[osalbahr@vclvm176-217 install]$ git checkout c699c940172^
Previous HEAD position was 6df4f60... Merge pull request #760 from b8rky/support-oci-containers
HEAD is now at 95648ef... Merge pull request #751 from gromgit/use-usable-git
[osalbahr@vclvm176-217 install]$ ./install.sh 
The version of Git that was found does not satisfy requirements for Homebrew.
Please install Git 2.7.0 or newer and add it to your PATH.
[osalbahr@vclvm176-217 install]$ 
```

**Comment by ChillerDragon** [comment]
I will pr a hotfix in a second. Did I understand the issue correctly? You are saying the error messsage is hidden correct? So your installer should fail either way but it should be nicer when telling you why.

**Comment by maxim-belkin** [comment]
> Did I understand the issue correctly? You are saying the error messsage is hidden? So your installer should fail either way but it would be nicer if it was telling you why.

The problem is in the logic. What @osalbahr is reporting is that on his platform Git is available but is old. And Homebrew install script reports that Git is not installed. Before #756 it was reporting correctly.

Ideally, we need to bisect to confirm that this is caused by #756 -- @osalbahr, if you're familiar with `git bisect` please do that. But looking at the main points in git history when this logic changed -- it was in #756.

_Unrelated: @osalbahr, did you, by any chance, attend UIUC in Champaign, IL?_

**Comment by ChillerDragon** [comment]
> > Did I understand the issue correctly? You are saying the error messsage is hidden? So your installer should fail either way but it would be nicer if it was telling you why.
> 
> 
> 
> The problem is in the logic. What @osalbahr is reporting is that on his platform Git is available but is old. And Homebrew install script reports that Git is not installed. Before #756 it was reporting correctly.
> 
> 
> 
> Ideally, we need to bisect to confirm that this is caused by #756 -- @osalbahr, if you're familiar with `git bisect` please do that. But looking at the main points in git history when this logic changed -- it was in #756.
> 
> 
> 
> _Unrelated: @osalbahr, did you, by any chance, attend UIUC in Champaign, IL?_

Thanks for clarifying. And you did find the correct commit already. I did open a pr with a fix. Sorry for causing this confusion that's on me.

**Comment by osalbahr** [comment]
> @osalbahr, if you're familiar with git bisect please do that.

I haven’t used bisect before, but I’d be happy to learn

> Unrelated: @osalbahr, did you, by any chance, attend UIUC in Champaign, IL?

Yes :). I think I remember you now. You were giving me lectures in Python iirc
