### ISSUE TITLE
SSL: peer not verified:  RecoverableTrustFailure

### ISSUE THREAD

**Issue by Rashie** [Homebrew/install#776]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ y] your problem was from running the official `install` or `uninstall` script?
- [ MacOS 12.6.5 : 
<img width="563" alt="image" src="https://github.com/Homebrew/install/assets/10414892/9e883251-c011-4734-8134-8d3e105d2d90">
] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue? 

## What you were trying to do (and why)

I was trying to install homebrew using command
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

I am installing because i have python 3.10 on my mac and i want also to have 3.9/3.8 and i am following this medium post

https://medium.com/macoclock/how-to-install-and-manage-multiple-python-versions-on-macos-ca01a5e398d4#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjYwODNkZDU5ODE2NzNmNjYxZmRlOWRhZTY0NmI2ZjAzODBhMDE0NWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODU5NTAxNjksImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwMDI1NTIzMjc1NTU3MjI3MjQ2MCIsImVtYWlsIjoia2l0d2FnaW5ueUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiMjE2Mjk2MDM1ODM0LWsxazZxZTA2MHMydHAyYTJqYW00bGpkY21zMDBzdHRnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwibmFtZSI6IlJhc21pdGhhIFZhZGxhcHVkaSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQWNIVHRkdE1XT09ZQkw0QWFTNUN3UTFHNEduYmlGcGhITXh1VVAxT0JEWXJBPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IlJhc21pdGhhIiwiZmFtaWx5X25hbWUiOiJWYWRsYXB1ZGkiLCJpYXQiOjE2ODU5NTA0NjksImV4cCI6MTY4NTk1NDA2OSwianRpIjoiZDUwYTIyZTc1OTQwODRkMDdmOGQ5OGM0YzI5NDJiNjU0NGNhNzgzMSJ9.zOAgMnfOKiirDi9Q17oMS6BHnxVNFrFPsnrQ_abf0bMCBAdSSfkJaiODb1SXto3k1IzKtHCYXDDKyXz6sXWneYiqiK-HIp6VZjsHr0-Go8XHJkpJJ_gTduElTyOnmst01nLm4VDZEbySFByg1SCVvY_Jo0MqKFhCLNgCt1hxBDB09a0pkvA8lMw2U1IgTuS8cnogfCi4Pk4ptQEDxuhsCpTD0J3vIFP0RTsFgQRDavgZKUaoBISQTIdHKI6Ji95_Q_51mbT9M4cQSkA2RguDVlRafpma-1l7RydnR8LAj29xaLkT59k7OrxVEsXnkRTd-rVl0r6Kcr14nGOwK9sTmA

<img width="564" alt="image" src="https://github.com/Homebrew/install/assets/10414892/d348dff4-a444-49ee-aca3-0122ebf080c0">

## What you expected to happen

It should install homebrew

## Step-by-step reproduction instructions (by running `brew` commands)
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 running this command in macos terminal

**Comment by MikeMcQuaid** [comment]
You have an issue connecting to GitHub. Nothing we can do about that, you'll have to figure it out yourself.
