### ISSUE TITLE
syntax error near unexpected token `)' when adding homebrew to PATH

### ISSUE THREAD

**Issue by mogulcoder26** [Homebrew/install#779]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

After installing Homebrew via WSL , In order to add Homebrew to PATH , I plugged this code from the prompt in terminal to install Homebrew to path present at `install.sh` at line 1021
```
- Run these two commands in your terminal to add Homebrew to your ${tty_bold}PATH${tty_reset}:
    (echo; echo 'eval "\$(${HOMEBREW_PREFIX}/bin/brew shellenv)"') >> ${shell_profile}
    eval "\$(${HOMEBREW_PREFIX}/bin/brew shellenv)"
```

## What happened (include command output)

On running `echo 'eval "\$(${HOMEBREW_PREFIX}/bin/brew shellenv)"') >> ${shell_profile}`
I get :

<details>
  <summary>Command output</summary>
  <pre>

`-bash: syntax error near unexpected token ')'`

  </pre>
</details>

## What you expected to happen

Was expecting for Homebrew to get added to path.

## Step-by-step reproduction instructions (by running `brew` commands)

- Install Homebrew using wsl via cURL :
` /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)`

- The installer will tell you how to add brew to the PATH. Copy the commands they list and run them one by one.

**Comment by carlocab** [comment]
That's because you can't just lift the code verbatim from `install.sh`. Instead, you should use the commands that were actually printed in your terminal:
```
- Run these two commands in your terminal to add Homebrew to your PATH:
    (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.profile
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
```
See https://github.com/Homebrew/install/actions/runs/5254185706/jobs/9492482307#step:10:426.

**Comment by mogulcoder26** [comment]
I was just pointing out the code in the `install.sh`.
Indeed I ran this :
`'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.profile`
And this command output the bash : syntax error.

I figured out that the command should be 
`'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)")' >> /home/runner/.profile`
and not the one you gave.

**Comment by XuehaiPan** [comment]
> I was just pointing out the code in the `install.sh`. Indeed I ran this : `'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.profile` And this command gave output:` bash : syntax error.`

@mogulcoder26 You should run this:

```bash
(echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.profile
```

You have missed `(echo;` which leads to a syntax error.

**Comment by XuehaiPan** [comment]
@mogulcoder26 You missed the left parenthesis `(`. The command is:

```bash
(echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.profile
```

**Comment by mogulcoder26** [comment]
Got it,Thanks a lot @XuehaiPan !
