### ISSUE TITLE
Unable to install Homebrew in my Ubuntu System.

### ISSUE THREAD

**Issue by captain-Akshay** [Homebrew/install#782]
- [ ] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue?
OS :-  ubuntu 23.03
## What you were trying to do (and why)
I was trying to install brew in my system

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 130555 ms: Connection timed out

  </pre>
</details>

## What you expected to happen
To be able to see installation processes in the terminal

## Step-by-step reproduction instructions (by installation script in terminal)

<pre>https://raw.githubusercontent.com/Homebrew/install/master/install</pre>
i'm not being able to connect to this via browser
and

<pre>/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" </pre>
the server are down for 2 days now that's why i think it may be a problem here!

**Comment by dawidd6** [comment]
Works for me:

```
~ ➜  curl -IfsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
HTTP/2 200 
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
etag: "33915772b0421d28251734b74c5997f76b43d9753c30eb770b7eb7bc4e63dea8"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: D6E4:8451:3D4F53:3F95F5:648BAA55
accept-ranges: bytes
date: Wed, 21 Jun 2023 06:38:27 GMT
via: 1.1 varnish
x-served-by: cache-fra-eddf8230020-FRA
x-cache: HIT
x-cache-hits: 1
x-timer: S1687329507.445821,VS0,VE1
vary: Authorization,Accept-Encoding,Origin
access-control-allow-origin: *
cross-origin-resource-policy: cross-origin
x-fastly-request-id: 5253bf71ecf46c580b2929f0a17a8d190e1a6510
expires: Wed, 21 Jun 2023 06:43:27 GMT
source-age: 11
content-length: 30205
```

Looks like it is a network issue on your end.

**Comment by captain-Akshay** [comment]
Ahh ok..
I have being going through a lot of issue in the NVM package as well looks like i need to change my dns setting or my Ipv !!
Thanks for letting me know that the github server are working fine..
let me try to fix it !
do you have any idea about it then please share highly appreciated.
