### ISSUE TITLE
can't install dmd on apple silicon Mac

### ISSUE THREAD

**Issue by greggjaskiewicz** [Homebrew/install#798]
# Can't install DMD (D compiler)

- [x] your problem was from running the official `install` or `uninstall` script?
- [x ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Trying to install D compiler, DMD. Binary and source compilation. 
Both fail with the same error.

## What happened (include command output)

fails to install, even when requested installation from sources! 

<details>
  <summary>Command output</summary>
  <pre>

dmd: The x86_64 architecture is required for this software.
Error: dmd: An unsatisfied requirement failed this build.

  </pre>
</details>

## What you expected to happen

I was expecting to at least be able to rebuild it from sources for apple silicon platform.

## Step-by-step reproduction instructions (by running `brew` commands)

brew install dmd 
brew install -s --force dmd

**Comment by vitorgalvao** [comment]
You’re in the wrong repository, this one is for the scripts to (un)install Homebrew itself, not packages. You’re [looking for Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/issues/new?assignees=&labels=bug&projects=&template=bug.yml).

**Comment by SMillerDev** [comment]
As is documented in https://dlang.org/download.html, you can't install dmd on Apple silicon. Homebrew can't change the way software developers write their tools.

**Comment by osalbahr** [comment]
You might want to look more into dmd-specific resources for M1, such as https://forum.dlang.org/thread/fguiwurobxeafwqetrax@forum.dlang.org (https://www.google.com/search?q=running+dmd+on+m1).

I’m not sure how it would play with Rosetta, but that’s something else to look into. Not sure how it plays well with dmd (you can start a discussion on their forum). If so, you might be able to use a `brew`ed x86 dmd.
