### ISSUE TITLE
[Bug] Apple not hosting latest CLI tools on software update servers?

### ISSUE THREAD

**Issue by rainyskye** [Homebrew/install#799]
## What you were trying to do (and why)

Installing Homebrew on the latest macOS Sonoma Beta - 14.0 Beta (23A5301h)

## What happened (include command output)

Due to what I assume is apple not yet updating their software update server with the latest CLI tools packages, the `xcode-select --install` command fails with a generic error about not being able to find a compatible version.

## What you expected to happen

Xcode Command Line tools to properly install

## Step-by-step reproduction instructions (by running `brew` commands)

N/A

## Resolution/Mitigation

At the current time, manually installing the command line tools from [developer.apple.com] is the easiest way.
This could be implemented as a note to the user if they're running Sonoma? (e.g: "You appear to be running macOS 14, please note that if the GUI popup fails to install the command line tools, you can download the .pkg manually from developer.apple.com")?

**Comment by SMillerDev** [comment]
Beta versions of macOS are not supported by Homebrew so any issues you're experiencing are expected to be resolved by you alone.
