### ISSUE TITLE
Brew PKG installer failing

### ISSUE THREAD

**Issue by Korothi** [Homebrew/install#800]
brew installer doesn't work for me.
<img width="608" alt="Zrzut ekranu 2023-08-14 o 14 19 22" src="https://github.com/Homebrew/install/assets/88345690/71904f1c-33d4-415d-ae63-bee89f8c5ca7">
is there a fix?

**Comment by SMillerDev** [comment]
Not without knowing what failed, check `/private/var/log/install.log` for that.

**Comment by MikeMcQuaid** [comment]
Closing until we have more information, can't do anything with what we've got here, sorry.
