### ISSUE TITLE
Can you make should_install_command_line_tools() more gentle?

### ISSUE THREAD

**Issue by xycabcd** [Homebrew/install#804]
Can you let should_install_command_line_tools() just check the tools that Homebrew need, instead of checking the whole Command Line Tools.
And let the script ask the user to install the tools, instead of installing the Command Line Tools forcedly.
Also ask the user don't uninstall Xcode if they use Command Line Tools of the Xcode.

**Comment by MikeMcQuaid** [comment]
> if they use Command Line Tools of the Xcode.

These are not sufficient.

**Comment by xycabcd** [comment]
So why not sufficient?

**Comment by xycabcd** [comment]
So why not sufficient?

**Comment by MikeMcQuaid** [comment]
Go read the many other threads explaining why this is the case.
