### ISSUE TITLE
Cannot install via .pkg installer

### ISSUE THREAD

**Issue by alexnesh** [Homebrew/install#814]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I can successfully run the install script. However, I'm trying to install a specific version of homebrew instead of whatever version the script chooses. The reason for this is so that we can standardize our CI and development environment on consistent versions of our dependencies without having to rely on "whatever the script chooses". Hence, I'm trying to run the .pkg installer downloaded from the releases page, specifically for version 4.1.16. Please note that if there is a way to run the script and elect for a specific version, LMK and I can give that a try - I'm sure it'd work given that the script works for me in general, I just cannot control the version. 

I'm running macOS Sonoma 14.0 on an Intel Mac. I did not run the script and obviously did not run `brew config` and `brew doctor` post-installation b/c the installation failed. 

## What happened (include command output)

When I run the installer, it eventually fails with just the output: 

The installation failed. The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. 

<details>
  <summary>Command output</summary>
  <pre>

no cmd line output - I'm running the .pkg installer. 

  </pre>
</details>

## What you expected to happen

Installs homebrew successfully :) 

## Step-by-step reproduction instructions (by running `brew` commands)

no commands, again. Just downloaded the 4.1.16 .pkg installer and ran it.

**Comment by SMillerDev** [comment]
Older versions of the installer are just as unsupported as older versions of the script. Homebrew only supports the latest versions of its tools.

Anything could be wrong with that older version.
