### ISSUE TITLE
Stuck at Installing homebrew

### ISSUE THREAD

**Issue by joaopinacio** [Homebrew/install#817]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)
Trying to run the command at terminal:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

## What happened (include command output)
I tried to run the command above and its stuck (showing this):
```
==> Checking for "sudo" access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R joao:admin /opt/homebrew
==> Downloading and installing Homebrew...
HEAD is now at 275078dd7 Merge pull request #16204 from Bo98/coverage-fixes
```

## What you expected to happen
Install normally and do not be stuck there

## Step-by-step reproduction instructions (by running `brew` commands)
just run:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by joaopinacio** [comment]
i didn't solve the problem but i used the ".pkg" installer and added to the PATH variable manually.

Link to the ".pkg" brew installer:
[Brew](https://github.com/Homebrew/brew/releases/tag/4.1.19)

**Comment by MikeMcQuaid** [comment]
This is an issue with your machine.
