### ISSUE TITLE
Install .pkg from terminal ?

### ISSUE THREAD

**Issue by tdesaules** [Homebrew/install#819]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] your problem was from running the official `install` or `uninstall` script?
- [ ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Install the last pkg installer from the terminal

## What happened (include command output)

```
tdesaules@thibaults-mbp Repositories % installer -pkg Homebrew-4.1.20.pkg -target /
installer: Error - the package path specified was invalid: 'Homebrew-4.1.20.pkg'.
```

<details>
  <summary>Command output</summary>
  <pre>
    installer: Error - the package path specified was invalid: 'Homebrew-4.1.20.pkg'.
  </pre>
</details>

## What you expected to happen

not sure yet, get the pkg get installed ?

## Step-by-step reproduction instructions (by running `brew` commands)

`tdesaules@thibaults-mbp Repositories % installer -pkg Homebrew-4.1.20.pkg -target /`

**Comment by vitorgalvao** [comment]
Why try to install the PKG from the Terminal? If you’re already on the Terminal you should be using the install script, which is the main, tested, officially supported method.

**Comment by SMillerDev** [comment]
It seems like you're pointing the installer tool to a path that doesn't exist. Try copying the full path of the file, or using the installer script, since I think this install method will skip some user information you could get from the installer UI

**Comment by tdesaules** [comment]
Yes at this time I use the installer script to bootstrap my Mac.
Was  more a test to check if the package should work, sometime it is easier to manage a versioned package than a cli without an interactive terminal.
Anyway, I also try with the full path, I get the same issue but if the pkg wasn't tested to work like that, we can move on :)
