### ISSUE TITLE
Brew install is hanging

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/install#82]
_From @corysimmons on October 28, 2016 21:8_

### Bug reports:

```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/lib
==> The following existing directories will have their owner set to webad:
/usr/local/lib
==> The following existing directories will have their group set to admin:
/usr/local/lib
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/etc
/usr/local/opt
/usr/local/sbin
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var

Press RETURN to continue or any other key to abort
# hangs for 15+ minutes....
```

### Propose a feature:

Fix this, or add some progress indicator to let me know it's actually doing something.

Fresh Mac Sierra install. XCode 8.1 CLI tools installed.

_Copied from original issue: Homebrew/brew#1390_

**Comment by corysimmons** [comment]
?

**Comment by bfontaine** [comment]
@corysimmons I moved your issue here because that’s the repo of the installer script.

**Comment by corysimmons** [comment]
Ah I see. Thanks.

**Comment by MikeMcQuaid** [comment]
> Press RETURN to continue or any other key to abort

@corysimmons I assume you pressed return or some other key?

**Comment by corysimmons** [comment]
After waiting for 15 minutes without any sort of response. I've installed Brew before and it usually only takes a minute or so, so I assume something is wrong.

**Comment by corysimmons** [comment]
Holy god I'm stupid...

For some reason I kept reading it as "Press RETURN or any other key to abort"

I'm going to go sit in the corner now...

**Comment by ilovezfs** [comment]
@corysimmons your time out is over :)
