### ISSUE TITLE
uninstall warning

### ISSUE THREAD

**Issue by core-code** [Homebrew/install#822]
```
~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

/bin/bash: line 250: /opt/homebrew/bin/brew: No such file or directory
```

yes i'd like to remove everything because after using the "Migration Assistant" moving from an Intel to an ARM Mac, everything is in the wrong place.

**Comment by SMillerDev** [comment]
Run it under Rosetta or run the `--help` option of the uninstall script
