### ISSUE TITLE
Homebrew package installer does not work with Xcode alone

### ISSUE THREAD

**Issue by fraserhess** [Homebrew/install#831]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Run the Homebrew package installer on a Mac (macOS 13.6) with Xcode installed.

## What happened (include command output)

An error is thrown when running trying to install the package:

<img width="732" alt="Homebrew 1" src="https://github.com/Homebrew/install/assets/57939/32ea9e7c-ce91-4877-aebc-fbaf0630ee0e">

## What you expected to happen

Homebrew would install successfully.

The [Distribution.xml](https://github.com/Homebrew/brew/blob/ff899e5b3ff6731208564ef502db237e2627e8ba/package/Distribution.xml#L36) checks for the presence of `/Library/Developer/CommandLineTools/usr/bin/git` but not for `/Applications/Xcode.app/Contents/Developer/usr/bin/git`. This is in contrast to the [postinstall](https://github.com/Homebrew/brew/blob/ff899e5b3ff6731208564ef502db237e2627e8ba/package/scripts/postinstall#L22) that extends `PATH` for both `/Library/Developer/CommandLineTools/usr/bin` and `/Applications/Xcode.app/Contents/Developer/usr/bin`

## Step-by-step reproduction instructions (by running `brew` commands)

1. Install Xcode to /Applications
2. Download Homebrew package installer
3. Open package

**Comment by Bo98** [comment]
CLT is a requirement for non-latest macOS (so macOS 13.6 counts), so this is expected. The latest Xcode.app does not ship MacOSX13.sdk but the CLT does.

**Comment by MikeMcQuaid** [comment]
This is a known limitation. I was not able to find an approach that worked consistently for Xcode alone _and_ checked for the necessary version. Given what @bo98 said and that our Bash-based installer requires the CLT globally: considering this not a bug but something we'll review a PR for if you can fix it. Sorry!
