### ISSUE TITLE
Unable to install because a remote branch was renamed or deleted

### ISSUE THREAD

**Issue by RobbyCBennett** [Homebrew/install#843]
- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I tried to install using `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

## What happened (include command output)

I couldn't install because a remote branch was renamed or deleted.

System and software information:
- Architecture: arm64
- MacOS: 12.2
- zsh: 5.8
- bash: 3.2.57
- git: 2.32.1

<details>
  <summary>Command output</summary>
  <pre>

==> Updating Homebrew...
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /opt/homebrew/Library/Taps/dart-lang/homebrew-dart failed!
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:d783cbeb6e6ef0d71c0b442317b54554370decd6fac66bf2d4938c07a63f67be
####################################################################################################################################################### 100.0%
==> Pouring portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
Installing from the API is now the default behaviour!
You can save space and time by running:
  brew untap homebrew/core
  brew untap homebrew/cask
Updated 1 tap (leoafarias/fvm).
Error: Some taps failed to update!
The following taps can not read their remote branches:
  dart-lang/dart
This is happening because the remote branch was renamed or deleted.
Reset taps to point to the correct remote branches by running `brew tap --repair`
Failed during: /opt/homebrew/bin/brew update --force --quiet
  </pre>
</details>

## What you expected to happen

I expected the installer to work.

## Step-by-step reproduction instructions (by running `brew` commands)

Install using `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by MikeMcQuaid** [comment]
Homebrew is already installed.

**Comment by RobbyCBennett** [comment]
It's installed for another user as a ZSH plugin, but it's not installed for the whole system or my user.

```
> brew
zsh: command not found: brew
```

```
> find / -name brew 2>/dev/null
/System/Volumes/Data/Users/OTHER_USER/.oh-my-zsh/plugins/brew
/Users/OTHER_USER/.oh-my-zsh/plugins/brew
```
