### ISSUE TITLE
Cannot install homebrew on iOS 11

### ISSUE THREAD

**Issue by TGreat2014** [Homebrew/install#846]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ YES] your problem was from running the official `install` or `uninstall` script?
- [ YES] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What happened (include command output)

<details>
  <summary>Unable to download Homebrew </summary>
  <pre>

  

  </pre>
</details>

**Comment by SMillerDev** [comment]
That is correct. It requires macOS or Linux
