### ISSUE TITLE
Administrator Password

### ISSUE THREAD

**Issue by Moonlight1220** [Homebrew/install#863]
**Hello Homeberew Community,**

When Installing Homebrew With The Command:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
I was prompted to input my password, from there on it would not let me input my password and after 3 more attempts it resulted in the output of:
`Need sudo access on macOS (e.g. the user alexanderdorman needs to be an Administrator)!`

Please advise on how to move foward!

**Comment by SMillerDev** [comment]
Make sure you're an administrator on the computer

**Comment by Moonlight1220** [comment]
Hello Again,

This bug comes from a linux and macOS security feature, the password does not display in the terminal however if you just type in your password it should work perfectly fine.
