### ISSUE TITLE
Installation script does not handle unknown parameters well

### ISSUE THREAD

**Issue by sttcns** [Homebrew/install#919]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your problem was from running the official `install` or `uninstall` script?
- [x] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

Download the installation script and run it with an unknown parameter.

```bash
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o install.sh
./install.sh ASDF
```

## What happened (include command output)

The script fails, because `warn` function is used on line 58 before its declaration on line 97.

<details>
  <summary>Command output</summary>
  <pre>

```
./install.sh: line 58: warn: command not found
Homebrew Installer
Usage: [NONINTERACTIVE=1] [CI=1] install.sh [options]
    -h, --help       Display this message.
    NONINTERACTIVE   Install without prompting for user input
    CI               Install in CI mode (e.g. do not prompt for user input)
```

  </pre>
</details>

## What you expected to happen

The error handled gracefully.

## Step-by-step reproduction instructions (by running `brew` commands)

```bash
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o install.sh
./install.sh ASDF
```

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by ZhongRuoyu** [comment]
Thanks for reporting; this should be fixed by #920.
