### ISSUE TITLE
node_modules not removed

### ISSUE THREAD

**Issue by jakirkham** [Homebrew/install#96]
It appears the uninstall script is not removing `node_modules`. We are seeing a bunch of stuff in `/usr/local/lib/node_modules` after running the uninstall script.

cc @gqmelo

**Comment by jakirkham** [comment]
Would add that `npm` appears to be in `/usr/local/bin` as well.

**Comment by MikeMcQuaid** [comment]
Did you see either `Homebrew partially uninstalled (but there were steps that failed)!` or `The following possible Homebrew files were not deleted:`? I'm pretty sure you will have seen the latter in which case this isn't a bug; we don't aim to remove every possible file that could be installed by Homebrew formulae.
