### ISSUE TITLE
symlinks generated by cask are not removed

### ISSUE THREAD

**Issue by gqmelo** [Homebrew/install#97]
This is minor and I'm not sure if it is addressable, but I've noticed that on travisci with the xcode 6.4 image the uninstall script leaves symlinks to ```oclint``` on ```/usr/local/bin``` as can be seen on the ```before_install.2``` step of this [build](https://travis-ci.org/gqmelo/psutil-feedstock/jobs/210581632).

[oclint formula](https://github.com/oclint/homebrew-formulae) says that some travisci images has ```oclint``` installed with cask, so I think this is why the symlinks were left behind. ```/usr/local/Caskroom/oclint``` was removed though, making the symlinks broken.

**Comment by jakirkham** [comment]
Also probably relevant is PR ( https://github.com/Homebrew/install/pull/95 ).

**Comment by MikeMcQuaid** [comment]
Did you see either `Homebrew partially uninstalled (but there were steps that failed)!` or `The following possible Homebrew files were not deleted:`? I'm pretty sure you will have seen the latter in which case this isn't a bug; we don't aim to remove every possible file that could be installed by Homebrew formulae or Casks.

**Comment by gqmelo** [comment]
I removed the ```-q``` options and ran the job again. At the end homebrew gives this message:

```
The following possible Homebrew files were not deleted:
/usr/local/bin/
/usr/local/etc/
/usr/local/lib/
/usr/local/share/
/usr/local/var/
You may wish to remove them yourself.
```

**Comment by gqmelo** [comment]
Ok, thanks!
