### ISSUE TITLE
postgres remnants not uninstalled

### ISSUE THREAD

**Issue by jakirkham** [Homebrew/install#99]
It appears the uninstall script is not removing some `postgres` remnants. We are seeing a bunch of stuff in `/usr/local/var/postgres` after running the uninstall script.

**Comment by MikeMcQuaid** [comment]
Did you see either `Homebrew partially uninstalled (but there were steps that failed)!` or `The following possible Homebrew files were not deleted:`? I'm pretty sure you will have seen the latter in which case this isn't a bug; we don't aim to remove every possible file that could be installed by Homebrew formulae.
